### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by NVentimiglia** [RevenantX/LiteNetLib#1]
I spent the day testing LiteNetLib, and came up with these results :

`````
Uptime : 1.33 min
Connected : 1
Errors 0
Total Messages : 422
Requests Per Second : 316.45
Latency : 188.87 ms
Mem 20, VMem 192, Threads 19

`````

Additional, when trying to connect any more than 2 clients on my machine, the test failed. Currently this same test over websockets is yielding 700,000 ops with latency of 10ms handling 5000 connections. I feel one of us is doing something very incorrect.

My test includes an initial opening handshake followed by a endless echo of 256 length streams. I am using unreliable transportation.

I cant yield my full code as it is part of a larger transport-agnostic framework, but have included the implementation below. Specifically, I have polling on a tight loop on the server and the client (I did have a yield statement in there, but it was not helping.

Transport level Code : https://gist.github.com/NVentimiglia/2534ab5dac563565887ee2e9b9ebd3dc

If you could either point out something I am doing wrong, or provide a console-app stress test that I can compare against, that would be great.

**Comment by NVentimiglia** [comment]
Ive created a new unity based benchmark. Similar results.

OPS 60.21 lag 16.00 time 0.25

https://gist.github.com/NVentimiglia/9cd027ac74fb3245ed09eae030f038ba

**Comment by RevenantX** [comment]
> If you could either point out something I am doing wrong, or provide a console-app stress test that I can compare against, that would be great.

Hi! In LiteNetLib i use Queue for all packets (except library logic packets). This is need for flow control.
And you sending messages in OnNetworkReceive event that invoked when you call PollEvents (for sync threads).
For better results you can send many packets in some thread (or in Update method).
I can add unsynced method for receiving packets (receiving logic works in separate thread).

**Comment by RevenantX** [comment]
Added experimental flag to Client and Server - UnsyncedEvents.
In that mode you don't need to call PollEvents. But for Unity3d (and for other application) you must manually sync your data (if needed) because events called in separate thread,

**Comment by RevenantX** [comment]
And i can add Flush method to instantly send data after call.

**Comment by NVentimiglia** [comment]
Thanks for the update. Ill give it a run this weekend.

**Comment by RevenantX** [comment]
Added one more improvement. If there is no flow control - Unreliable packets will be sent immediately.

**Comment by RevenantX** [comment]
Do you have some updates?) Can i resolve issue?)

**Comment by NVentimiglia** [comment]
yes thank you
