### ISSUE TITLE
Thread deadlock while calling NetClient.Stop()

### ISSUE THREAD

**Issue by federicodangelo** [RevenantX/LiteNetLib#10]
I have found a strange deadlock in NetClient.Stop(),  it happens when NetClient.Stop() is called from the "main thread" while the "socket thread" receives a disconnect packet from the server, and since both call CloseConnection(), the call to _threadv4.Join() in NetSocket never finishes because the "socket thread" is locked in the "lock (_connectionCloseLock)" inside CloseConnection.

**Comment by RevenantX** [comment]
Thanks for bug report :) I will fix this.

**Comment by RevenantX** [comment]
I added Disconnect method. Client can now connect and disconnect multiple times. Without calling stop.
NetServer and NetClient now not stopped if receiving error or NetClient receives disconnect event. Now Stop will only be called by user.
