### ISSUE TITLE
NetPacket.Sequence property limitation using ushort type

### ISSUE THREAD

**Issue by gubicsz** [RevenantX/LiteNetLib#101]
Hi,

I came across a limitation with the ushort data type of the NetPacket.Sequence property and I wanted to ask your opinion about this. NetConstants defines the MaxSequence const which only allows 32768 sequenced packets to be received. If I send position updates on the Sequenced channel 60 times per second that would mean about 9 minutes of continuous data transfer then the MaxSequence is reached and the SequencedChannel blocks incoming packets using the NetUtils.RelativeSequenceNumber method.

Should I rewrite all ushort types to uint if I need more than 32768 packets per session or is there any other trick I could use without rewriting anything?

Thank you!

**Comment by RevenantX** [comment]
Hi! Oh. There is error in that code. I will fix this)

**Comment by gubicsz** [comment]
No problem. I thought this was intentional. Will the fix allow me to send unlimited number of sequenced messages or it will still be limited by the max value of the ushort data type?

**Comment by RevenantX** [comment]
@gubicsz - unlimited as in reliable channel)

**Comment by gubicsz** [comment]
Great, thanks!
