### ISSUE TITLE
NatPunchModule Reliability

### ISSUE THREAD

**Issue by dt665m** [RevenantX/LiteNetLib#102]
Do you currently use the NatPunch feature in production?  I've written a small client -> server -> client command line demo to test this feature and it doesn't seem to be too reliable at the moment.  I'm running into two issues.  

1.) Dropped datagrams.   If the two clients receive the HandleNatIntroduction from the server, there is still a chance that the NatPunchMessage will fail to arrive.   Since your demo and the way the NatPunchModule is written is all done with _single_ unreliable datagrams, the chance of a successful punch is very low.

2.) On Successful NatPunchMessage arrival, if both clients are listening with NatIntroductionSuccess and both try to do client.Connect(Endpoint), sometimes the two clients will get stuck sending each other "ConnectRequest" packets and not handle the ConnectAccept message.  I was able to prevent this issue if I only allowed one client to call client.Connect(Endpoint) on successful punch through.  

If this is still a demo feature, I'm try to add a few reliability features and provide sample code of it working.  We have some experience doing this with our own library.  Otherwise, I might be attempting to use your library incorrectly and maybe you can give me some feedback.  

My proposal is to add another event for "HandleNatIntroduction" success so the _application_ can decide how often and how much to send the internal/external punch.  Usually if you get to this point in the negotiations, spamming the punch packet a few times should increase the chance for punch success.  In our experience, the punch packets need to arrive almost at the same time on two clients, so sending just one rarely works in a production environment.

Let me know what you think!  Thanks sharing such a great library.

**Comment by RevenantX** [comment]
@dt665m Hi!
NAT punch packets is unreliable by design. You must control this by hands. Punch example resends NAT punch packets if peer requests them (small simple reliability).
> Do you currently use the NatPunch feature in production? 

Yes)

**Comment by dt665m** [comment]
Yes I understand its unreliable by design, our library does something very similar.  I would like to know for your use case, do you have your clients request the NatIntroduction, which will trigger a NatPunch "N times until giving up"?

In your production experience, how often does this succeed and how big is your "N"?

**Comment by RevenantX** [comment]
> I would like to know for your use case, do you have your clients request the NatIntroduction, which will trigger a NatPunch "N times until giving up"?

Yes)

> In your production experience, how often does this succeed and how big is your "N"?

It depends on your needs. In one mobile game that use LiteNetLib we send NAT requests 2-3 times per second in 5-10 seconds.

**Comment by dt665m** [comment]
Thanks for the feedback.  After turning on DEBUG_MESSAGES, I'm seeing that punchthrough works most of the time, but sometimes two clients will get stuck in "ConnectRequest" loop.  They are both able to send to each other but both clients send the ConnectRequest until MaxConnectAttempts.  

This is on 0.7.5.  Any idea why this happens?

**Comment by dt665m** [comment]
Here's the output of the two clients:

https://pastebin.com/p5BNBpBQ
https://pastebin.com/yG01p3Hb
