### ISSUE TITLE
Packet 'leaks'

### ISSUE THREAD

**Issue by cswiedler** [RevenantX/LiteNetLib#103]
In NetManager.ReceiveFromPeer, events are queued up with the data from a received packet. However, the packet is not recycled in this case, which results in unnecessary garbage collection. I've made a local change to pass the packet inside the queued event and recycle it once the event is processed, which appears to fix the problem.

**Comment by RevenantX** [comment]
I think this must be optional. Better will be `Recycle` method (like in lidgren)

**Comment by RevenantX** [comment]
Ah. I found what you mean. I will investigate this and fix.

**Comment by RevenantX** [comment]
Thanks for report!)

**Comment by RevenantX** [comment]
@cswiedler there was no leak :( You will get corrupted packets. Because Receive from peer called in two places:
```csharp
                //Send to process
                _peerListener.ReceiveFromPeer(resultingPacket, _remoteEndPoint);

                //Clear memory
                _packetPool.Recycle(resultingPacket);
```
and
```csharp
                _peerListener.ReceiveFromPeer(p, _remoteEndPoint);
                _packetPool.Recycle(p);
```

**Comment by cswiedler** [comment]
I'm confused. It certainly looks like the places in NetManager that call DataReader.SetSource set up a shallow reference to the packet's buffer, and so to recycle the packet properly we need to know when the event has been processed.

My patch:
[patch.txt](https://github.com/RevenantX/LiteNetLib/files/1372753/patch.txt)

**Comment by RevenantX** [comment]
In method `ReceiveFromPeer` there is dataReader.SetSource(packet.GetPacketData()) method that makes copy of packet data.
