### ISSUE TITLE
"Undefined packet received" when using SendOptions.ReliableOrdered

### ISSUE THREAD

**Issue by zanval** [RevenantX/LiteNetLib#105]
When sending a packet via ReliableOrdered, some packets can not be Deserialized.
In my example, I send one packet per update with a counter.

Every 200-400 Packets fail at Deserialization.
When using other SendsOptions, I cannot reproduce this behaviour.

![image](https://user-images.githubusercontent.com/2341890/31321461-c48f1ad4-ac86-11e7-9a61-5a76c0a022ce.png)

**Comment by RevenantX** [comment]
Hi! Can you show packet structure that you sending? Or maybe minimal code that reproduces that problem?

**Comment by zanval** [comment]
I will setup a minimal working example to showcase this and get back to you.
Might take a couple days :)

**Comment by zanval** [comment]
Okay I just got the OK from my colleagues to just upload the actual project (nothing too fancy in it yet)
https://github.com/zanval/aleron-test

The folder "Aleron" contains the Unity project, the folder "AleronSolution" contains the Solution file which includes the Unity-Generated projects.
[Set to SendOptions.ReliableOrdered in Line 65](https://github.com/zanval/aleron-test/blob/master/Aleron/Assets/Sources/GameServer/Network/NetGameServer.cs)
Simply starting the Unity Project will suffice to trigger the error after switching to ReliableOrdered.

**Comment by RevenantX** [comment]
Thanks! I will look at this bug later.

**Comment by RevenantX** [comment]
One thing - 
```csharp
~NetGameServer()
{
    _netManager.Stop();
}
```
this will not work. Call stop in unity3d method "OnApplicationQuit".
And
```csharp
 foreach (NetPeer netPeer in _netPeers)
{
```
NetManager contains method `SendToAll` :)

**Comment by RevenantX** [comment]
@zanval checked your project. Cannot reproduce. 
Started with unreliable - all ok.
Changed to ReliableOrdered - all ok.
Scene - Scenes/Start

**Comment by zanval** [comment]
Okay, so I looked into both Unity Versions and got the same results with both,
but testing different Operating Systems yielded different results :)

macOS Sierra 10.12.6: Occurs every ~20.000 Packets
Windows: Occurs every ~20.000 Packets
Linux (Ubuntu 16.04):  Occurs every ~400 Packets

Reaching the Windows and macOS Numbers within the editor is unrealistic due to the low performance, but Development Builds of the Player are faster by ~200-400 times for me.
Also, the Exception pops up in the Development Build:
![image](https://user-images.githubusercontent.com/2341890/31357020-7f158e1a-ad40-11e7-97d2-b7f9365b1151.png)

**Comment by zanval** [comment]
And thanks for the hint on the Finalizer. Was going to test that, because it is outside of a Monobehaviour, but then I ran into this issue I reported here.

**Comment by RevenantX** [comment]
@zanval Found that epic bug instantly after sleeping. Try latest version.

**Comment by RevenantX** [comment]
@zanval this was introduced by my mistake day ago :(

**Comment by zanval** [comment]
Sleeping is really powerful :D Thanks, I'll be able to test it on the weekend.

**Comment by zanval** [comment]
Tested today, was not able to reproduce this issue anymore. 10.000 packets on linux without corruption.
Thanks a lot!
