### ISSUE TITLE
Unity3D Client Build Not Sending Packets

### ISSUE THREAD

**Issue by Remixful** [RevenantX/LiteNetLib#107]
I don't know what's going on... It works perfectly fine in the Game View, but not when I build it. The client connects, but does not send packets from the server... What's going on?

**EDIT**: Did a bit more testing, and it seems like it's the other way around, the client is not sending packets.

**Comment by Remixful** [comment]
Ugh.. figured out that setting the API Compatibility Level to .NET 2.0 fixes it.
Thank god.

**Comment by jamesbrooks** [comment]
This likely doesn't help your use case but I can confirm that I haven't had a problem with this using .NET 4.6 API Compatibility Level.
