### ISSUE TITLE
is NetPeer.Send thread safe?

### ISSUE THREAD

**Issue by friuns2** [RevenantX/LiteNetLib#109]
hello is NetPeer.Send thread safe can i do like that?

```csharp

public NetPeer peer;
     public void OnMessage(NetDataReader br)
        {
            Task.Run(() =>
            {
                var id = br.GetInt();
               ..............
                peer.Send(nw, SendOptions.ReliableOrdered);
            });
        }

**Comment by RevenantX** [comment]
Hi! No Send is not thread safe (especially for fragmented messages). But if you need i can make it thread safe (it almost done))

**Comment by friuns2** [comment]
cool thanks!

**Comment by pax83** [comment]
I plane to move my server from lidgren3 to LiteNetLib.  I have rooms realization and each room has own thread. If it is not thread-safe, then in what thread should I use to send messages?

**Comment by RevenantX** [comment]
@pax83 i will make thread safe send fix soon. 
Use any thread but just one) You can do this using locks for now.
```csharp
public void MyThreadSafeSend(byte[] data)
{
    lock(this)
    {
        netPeer.Send(...)
    }
}
```

**Comment by RevenantX** [comment]
Fixed in next version branch (packetprocessor)

**Comment by RevenantX** [comment]
@friuns2 merged into main branch.

**Comment by pha3z** [comment]
> Fixed in next version branch (packetprocessor)

Are you saying that NetPacketProcessor is threadsafe, but the rest of the API is not?

So I must use NetPacketProcessor.Send(Peer, Packet, DeliveryMethod) and not peer.send() if I want to call it from multiple threads?

**Comment by RevenantX** [comment]
@pha3z this fixed in master branch for now. (merged from packetprocessor branch, not class)

**Comment by sebas77** [comment]
Hi, sorry resuming this post (blame google for it :D).

is NetPeer.Send now thread safe? From what I can see from the code, it doesn't seem like
