### ISSUE TITLE
Memory leaks on reliable packets?

### ISSUE THREAD

**Issue by tarmylan** [RevenantX/LiteNetLib#111]
reliable packet memories will not be gc after peers disconnect

I have an example on my game that the server side keep producing reliable packets while the client side( running in bg ) does not consume any,  and its ping/pong is ok,  then the server memory keeping allocating, and they were not released after the peer disconnect.

**Comment by RevenantX** [comment]
@tarmylan i will check this. Maybe this because of packet pooling but not sure about your situation (with disconnect)

**Comment by tarmylan** [comment]
@RevenantX thx !
I mean the client side just shutdown the peer connection after long time not handling the reliable packet, the server side received disconnetion evts of them but did not handle the left packets in the outgoing stack or released them.
I followed into the code and found than the outgoing keep increasing after the pendings not be sent, maybe we need a return status on peer.Send to notify the application layer to stop before the outgoing size is too large(run out memory), or other enhancement?

**Comment by TraditoreZ** [comment]
I have a similar problem, when the amount reached one hundred thousand / sec, resulting in a large number of memory leaks

**Comment by TraditoreZ** [comment]
Now I follow up the code to packet pooling. It's not very good at work

**Comment by TraditoreZ** [comment]
The packages created are always more than the recycled packages

**Comment by RevenantX** [comment]
@tarmylan fixed memory consumption
https://github.com/RevenantX/LiteNetLib/commit/dfd2d27e6f2cf91f7336b3953add33de4d78fd7c
