### ISSUE TITLE
Socket error on Client.Start() in unity project

### ISSUE THREAD

**Issue by bamdad-b** [RevenantX/LiteNetLib#113]
Hi, I'm using LiteNetLib for a unity project, on the client side I have:
```csharp
listener = new EventBasedNetListener();
client = new NetManager(listener, "p1");
client.UnsyncedEvents = true;
client.Start();
client.Connect("127.0.0.1", 32064);
```
But a **SocketException** is thrown in line 4:
`An address incompatible with the requested protocol was used.`

I used this code in a WinForm application and it worked fine, so my server side code is working fine too.

**Comment by RevenantX** [comment]
@bamdad-b Hi!
Are you using compiled version? LiteNetLib.dll? Or sources?

**Comment by bamdad-b** [comment]
@RevenantX I'm using the dll on Unity 4.7.2
I also used it on Unity 5.5 and didn't work.
Should I use the source? I used the dll for my WinApps too with no problems.

**Comment by RevenantX** [comment]
@bamdad-b 
> Should I use the source? I used the dll for my WinForms app too with no problems.
Yes. Unity has specific compiler with some bugs. Also add define symbol UNITY to compilation options.

**Comment by bamdad-b** [comment]
@RevenantX Worked out.
I suggest you to change \LiteNetLib-master\LiteNetLib\NetUtils.cs:239 to:
UnityEngine.Debug.Log(string.Format(str, args));
because we don't have LogFormat() in older versions of Unity.
Thanks for your useful library.
