### ISSUE TITLE
LiteNetLib vs TCP for streaming data

### ISSUE THREAD

**Issue by mgamache** [RevenantX/LiteNetLib#114]
I realize this is probably not a typical use-case for the library, however...

I am currently streaming data over the internet via TCP. I am evaluating switching to the LiteNetLib (using ReliableOrdered), however, It seems like I am getting much better throughput using TCP. For example, I can get sustained 40mbs/sec using standard .net TCP code, but only 13mbs using LiteNetLib (before the Queues start to backup).  Is this expected, due to the packet checking? I've set the UpdateTime to 4 and the PollEvents to 4ms.  My test is sending 100 packets/sec.

Note, I am able to get 20-30mbs/sec using iperf UDP:
- 0% packet loss at 20mbs
- 3.8% packet loss at 30mbs

**Comment by RevenantX** [comment]
@mgamache i know about this thing. This because i not implemented "sliding" window technology.
And
>I realize this is probably not a typical use-case for the library...

yes. In almost all cases - transfering large amount of data will be better with TCP. 
This issue is same as https://github.com/RevenantX/LiteNetLib/issues/110
