### ISSUE TITLE
Sending messages in the Connect call

### ISSUE THREAD

**Issue by Skippeh** [RevenantX/LiteNetLib#115]
Hi, is it possible to send along an optional message to the server when connecting?

For example

``` csharp
NetDataWriter writer = ...
client.Connect("127.0.0.1", 8080, writer);
```

On the server it would be accessed by either an additional argument in the `PeerConnectedEvent` or as a property on the NetPeer itself (similar to lidgren).

**Comment by RevenantX** [comment]
@Skippeh this feature is WIP (work in progress). Look at https://github.com/RevenantX/LiteNetLib/issues/29
