### ISSUE TITLE
Replace locks with a concurrent queue

### ISSUE THREAD

**Issue by NVentimiglia** [RevenantX/LiteNetLib#117]
Locking to pass messages between threads is a performance bottleneck. Instead, we should replace this mechanism with a FIFO queue such as the ConcurrentQue which does not require thread locking.

https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1?view=netframework-4.7.1

https://github.com/dave-hillier/disruptor-unity3d

What are your thoughts?

**Comment by RevenantX** [comment]
For now locking is not bottleneck of library. And ConcurrentQueue doesn't work in Unity with old mono.

**Comment by NVentimiglia** [comment]
Whats wrong with the source code example? Are you saying this implementation does not work?

https://github.com/dave-hillier/disruptor-unity3d/blob/master/DisruptorUnity3d/Assets/ConcurrentQueue.cs

**Comment by RevenantX** [comment]
@NVentimiglia with source code all ok. I don't want use other libraries with LiteNetLib.
ConcurrentQueue not always can be faster than locks. Look at benchmarks.
