### ISSUE TITLE
There is no way to distinguish if I send multi-connect at the same time.

### ISSUE THREAD

**Issue by watsonsong** [RevenantX/LiteNetLib#118]
The NetManager.Connect has no any userdata or context can pass with it. So if I have multi-connection, I can not tell which connection is callback, and which connection is failed with error.
I build a dictionary with NetEndPoint as key, I don't know whether it is a right way.

**Comment by RevenantX** [comment]
@watsonsong ok. I will add peer to Connect result.

**Comment by watsonsong** [comment]
BTW, how about the OnNetworkError?
I don't know which peer has error except I build the endpoint lookup table to find peer.

**Comment by RevenantX** [comment]
@watsonsong network error for now is just for logs.

**Comment by watsonsong** [comment]
But the only way I can tell whether a connect is failed is only from the OnNetworkError.
If I start a connect and I want a callback on success or failed, the only way I can get failed is from OnNetworkError.

**Comment by RevenantX** [comment]
@watsonsong no. You will receive OnPeerDisconnected with DisconnectReaseon.ConnectionFailed

**Comment by RevenantX** [comment]
Partially fixed by
https://github.com/RevenantX/LiteNetLib/commit/2ecd24ffe2dfe6988e2f38f28321846ff5abf3a2

**Comment by RevenantX** [comment]
@watsonsong and in disconnectInfo there also is SocketErrorCode which you can use for errors.
