### ISSUE TITLE
GC too much

### ISSUE THREAD

**Issue by TraditoreZ** [RevenantX/LiteNetLib#119]
I have a problem at the moment when a number of transmission operations in the same frame will produce a large number of GC, and how can this be solved?
    void Update()
    {
        if (this.peer != null)
        {
            for (int i = 0; i < 1000; i++)
            {
                this.peer.Send(b, SendOptions.ReliableOrdered);
            }
        }
        netManager.PollEvents();
    } 
like this.
![1](https://user-images.githubusercontent.com/18109168/33846409-b426efa4-dee1-11e7-8753-514271f8cf9b.png)

**Comment by TraditoreZ** [comment]
My server will now eat all the memory in a few minutes . How to do it, please!

**Comment by RevenantX** [comment]
@TraditoreZ this happens every frame?

**Comment by TraditoreZ** [comment]
every frame . on the contrary, I don't think the reliableordered agreement is in time to go back to the  NetPacketPool

**Comment by TraditoreZ** [comment]
When a reliable transmission reaches a certain magnitude, you can easily reclaim the problem.

**Comment by RevenantX** [comment]
i found mistake. Get latest version. This bug must be fixed. https://github.com/RevenantX/LiteNetLib/commit/dfd2d27e6f2cf91f7336b3953add33de4d78fd7c
