### ISSUE TITLE
Unity3d example cannot execute

### ISSUE THREAD

**Issue by chwuchang** [RevenantX/LiteNetLib#12]
SocketException: 使用了与请求的协议不兼容的地址。

System.Net.Sockets.Socket..ctor (AddressFamily family, SocketType type, ProtocolType proto)
LiteNetLib.NetSocket.Bind (Int32 port) (at C:/Files/LiteNetLib/LiteNetLib/NetSocket.cs:112)
LiteNetLib.NetBase.Start (Int32 port) (at C:/Files/LiteNetLib/LiteNetLib/NetBase.cs:188)
LiteNetLib.NetBase.Start () (at C:/Files/LiteNetLib/LiteNetLib/NetBase.cs:173)
GameClient.Start () (at Assets/GameClient.cs:19)

**Comment by RevenantX** [comment]
You are using latest version? 0.6.1 or master?

**Comment by chwuchang** [comment]
Yes 0.6.1，  sorry I cant speek english，In NetSocket.cs 113line ，IPv6Support =true ,but " _udpSocketv6 = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.Udp);" is error

**Comment by RevenantX** [comment]
@chwuchang what unity3d version you are using?

**Comment by chwuchang** [comment]
Oh Thx ，It's ok, the lib is verygood ,I will  add my  project  ，Thx very much
