### ISSUE TITLE
Library fails to load under referenced .net standard project

### ISSUE THREAD

**Issue by tomzorz** [RevenantX/LiteNetLib#120]
Hi!

With the following project setup:

.net core console app -> references .net standard library -> references LiteNetLib via NuGet

![image](https://user-images.githubusercontent.com/6363312/33846418-0eda6344-dea7-11e7-83bb-495719554140.png)

the library fails to load.

![image](https://user-images.githubusercontent.com/6363312/33846398-fb1ce020-dea6-11e7-8e6c-8a55e709b393.png)

The same issue doesn't happen when I use newtonsoft.json's .net standard version for example, so the issue is probably with the .net standard release in the NuGet package.

EDIT 1:

I'm not 100% sure that the issue is with LiteNetLib here, but that's my best guess at this point. Two more bits of information:

 * The issue also persists if I add the LiteNetLib NuGet package to the .net core "NugetTest" project as well.
 * Using the sysinternals Process Monitor I couldn't find any attempts at all to read the actual .dll file.

**Comment by RevenantX** [comment]
@tomzorz Hi! Please check what libraries in same folder with executable.

**Comment by RevenantX** [comment]
@tomzorz and give me full logs.

**Comment by tomzorz** [comment]
@RevenantX what kind of logs do you want? Stacktrace is empty, it just says what you see above in the exception popup. I'll supply build logs tomorrow if that helps.

**Comment by RevenantX** [comment]
@tomzorz all text from Ouput windowd (right bottom corner)

**Comment by RevenantX** [comment]
@tomzorz i created new netcore project and importet library from nuget and all works.
Are you using newtonsoft.json in your library?

**Comment by tomzorz** [comment]
@RevenantX Create a **.net core project - console app**. Create a second **.net standard library** in the solution. Add LiteNetLib to the .net standard project, and add a project reference to the .net core project for the library. The error will show up when you use any LiteNetLib stuff in the .net core app from the .net standard library.

**Comment by tomzorz** [comment]
BTW it seems like that the issue is related to this https://github.com/dotnet/standard/issues/481

**Comment by tomzorz** [comment]
I tried doing the recommended binding redirects in the .csproj file, but it didn't work (or I did something wrong):

```
  <PropertyGroup>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
```

**Comment by tomzorz** [comment]
Here is a sample output:

```
'dotnet.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'D:\Projects_development\Temporary\DllHellFix\DllHellFix\bin\Debug\netcoreapp2.0\DllHellFix.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'D:\Projects_development\Temporary\DllHellFix\DllHellFix\bin\Debug\netcoreapp2.0\HellishStandardLibrary.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.IO.FileNotFoundException' in DllHellFix.dll
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in DllHellFix.dll
Could not load file or assembly 'LiteNetLibStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

**Comment by RevenantX** [comment]
@tomzorz i don't see that json library is loaded? is newtonsoft.json code is used in your .net standard library?

**Comment by tomzorz** [comment]
I just used it as a sample that a different library works if I use it the same way, essentially checking if the issue is with every nuget package referenced this way or with just LiteNetLib.

**Comment by tomzorz** [comment]
Here's the complete exception, nothing useful :( 

![image](https://user-images.githubusercontent.com/6363312/33888481-7bb900a0-df4d-11e7-9900-057ecc9f345f.png)

**Comment by tomzorz** [comment]
Attached sample .sln to reproduce the issue: [DllHellFix.zip](https://github.com/RevenantX/LiteNetLib/files/1551837/DllHellFix.zip)

**Comment by terrajobst** [comment]
I can reproduce the error. This isn't a problem with .NET Standard but it seems the package is authored incorrectly. It seems LiteNetLib uses different assembly names between .NET Core and .NET Standard:

![image](https://user-images.githubusercontent.com/5169960/33898813-536a68c0-df1e-11e7-8fb7-8da75382d948.png)

That shouldn't be done because it breaks transitive dependencies @tomzorz project (a .NET Core application is referencing a .NET Standard library that in turn references LiteNetLib). The expected behavior for these sort of configurations is that the .NET Standard library is compiled against `lib/netstandard/LiteLibNet.dll` while the .NET Core application deploys `lib/netcoreapp/LibLiteNet.dll`. This allows the package author to have additional functionality in the .NET Core version of the library while still providing a .NET Standard compatible version. This practice is dubbed "bait & switch". However, in this case the assembly names are different between the .NET Core and the .NET Standard version.

@RevenantX is there a reason why you chose different assembly names?

**Comment by RevenantX** [comment]
@terrajobst no there is no reason. I just don't know that this can break something.

**Comment by tomzorz** [comment]
@RevenantX I submitted a PR with the fixes https://github.com/RevenantX/LiteNetLib/pull/121 :)

**Comment by tomzorz** [comment]
@RevenantX Thank you for the merge. Could you update the NuGet as well? It's a blocking issue for us at the moment.

**Comment by RevenantX** [comment]
@tomzorz i will update nuget later (when i will come home)

**Comment by tomzorz** [comment]
@RevenantX Awesome, thank you!

**Comment by RevenantX** [comment]
@tomzorz check package at nuget. (0.7.6.3)

**Comment by tomzorz** [comment]
![image](https://user-images.githubusercontent.com/6363312/33959934-5a817af0-e049-11e7-8794-448b2a7bdedb.png)

Confirmed as fixed \o/

I really appreciate your quick help, thanks!
