### ISSUE TITLE
All cost delivery method

### ISSUE THREAD

**Issue by nxrighthere** [RevenantX/LiteNetLib#122]
I found this delivery method very useful in my game which currently uses UNET. Does LiteNetLib have something similar?
> AllCostDelivery: Fairly similar to Reliable qos, but there is a difference. The reliable channel will resend undelivered messages based on round trip time value (RTT) which is a dynamic parameter while AllCostDelivery will automatically resend messages after a period of time (configured value). This can be useful for small important messages: “I shot player A in the head” or “Mini-game starts”.  Example: Game events such as firing bullets

**Comment by Saishy** [comment]
I don't think that is a good thing actually. You either have server
authority, trust clients or do lockstep, and none would need that kind of
channel.

**Comment by nxrighthere** [comment]
I use this delivery method in UNET to send important data that must be delivered from a dedicated server  to the client with the minimum possible delay. Even if the client has a poor network connection with high latency and packet loss, it still gets acceptable visual results. I can't achieve the same results with just a reliable channel since undelivered messages are resend based on round trip time.

**Comment by toreau** [comment]
> I use this channel in UNET to send important data that must be delivered from a dedicated server to the client with the minimum possible delay.

Can you give an example or two?

> I can't achieve the same results with just a reliable channel since undelivered messages are resent based on round trip time.

Based on the description of `AllCostDelivery` above, I can't really see why it's extremely useful, except maybe as a helper for desperate people. 😄

**Comment by nxrighthere** [comment]
For example, character animation states. The character starts running - server sends animation state = 1 to observers. The character stops running - server sends animation state = 0, but data not delivered to observers and as result character stands still, but with the run animation.

**Comment by Saishy** [comment]
Ya know, either you send that animation together with the one that starts
the movement, or you do the animation client-side.
Networks should have approximately 0% packet drop, and reliable will always
deliver, so that worry is unfunded.

**Comment by nxrighthere** [comment]
In my case, both these methods are impossible due to some game mechanics.

**Comment by Saishy** [comment]
anyway, reliable should already be the best.
Even AAA engines and solutions will not provide anything like a super
message that is repeated until the ok is received :2

**Comment by nxrighthere** [comment]
Well, Unity provides it as well as a reliable/unreliable sequenced methods that I also use by the way.

**Comment by toreau** [comment]
> For example, character animation states. The character starts running - server sends animation state = 1 to observers. The character stops running - server sends animation state = 0, but data not delivered to observers and as result character stands still, but with the run animation.

This is hardly a problem, and as long as you send the data reliably, the new animation state(s) will _eventually_ reach the observers.

You also contradict yourself by saying that the player stops running, but not its running animation. One way to deal with that is to send the animation state with the player movement state, but only if it has changed since last time. Or something like that.

One of the problems I have with UNET, and many other network libraries, is that they are bloated with functionality that easily can be in the application code/logic instead. This bloated functionality, which tries to solve "everything for everyone", leads to huge projects, lots of bugs, and eventually the projects dies.

I'm not saying that seq channels is a bad idea, and that it shouldn't be implemented, but they aren't super-important in my eyes.

**Comment by nxrighthere** [comment]
> This is hardly a problem, and as long as you send the data reliably, the new animation state(s) will eventually reach the observers.

Yes, it is, but you don't hear me. As I mentioned before, data with the new animation state must be delivered to the client with minimum possible delay. For example, when the client has 150 ms latency and 20% packet loss, new animation state will be delivered with a huge delay because this is how reliable channel works. All cost delivery solves this problem because the message can be resent with a 20 ms timeout (this value can be changed) regardless of the round trip time.

> You also contradict yourself by saying that the player stops running, but not its running animation. One way to deal with that is to send the animation state with the player movement state, but only if it has changed since last time. Or something like that.

You're talking about the dirty mask. And no, this is not an option, because using this technique bandwidth usage will be increased dramatically and it way more costly than just use all cost delivery channel. It works well when you need to send efficiently the updated data of position, rotation and velocity in a single message, for example. In my case, animation state must be sent independently of character's movement for many reasons.

> One of the problems I have with UNET, and many other network libraries, is that they are bloated with functionality that easily can be in the application code/logic instead. This bloated functionality, which tries to solve "everything for everyone", leads to huge projects, lots of bugs, and eventually the projects dies.

If you are dealing with high-level networking libraries then yes, you are right. But I'm working with a low-level API.

> I'm not saying that seq channels is a bad idea, and that it shouldn't be implemented, but they aren't super-important in my eyes.

For the developers, they solve much more headaches than you can imagine.
