### ISSUE TITLE
Windows [C#] to Android [Java] real time communication

### ISSUE THREAD

**Issue by grill2010** [RevenantX/LiteNetLib#123]
Hi, I found your library and it looks really useful when you need sequenced or reliable udp communication.
I'm currently developing a C# program which is able to capture the screen of the Windows PS4 Remote Play program of Sony in 60fps or 30fps. I developed a quick and dirty prototype which is able to send compressed jpg images over udp to an Android device without any noticable delays.

However this prototype does not consider MTU but instead it just sends the whole image at once in one single udp packet which is not acceptable for the real application later on. I was thinking of building my own protocol but then I found this project which deals with almost every problem like sequenced packets and reliability. However the Android app is written in Java so I have to port your receiving code from C# to Java.

I'm experienced in C# and in Java so it should be possible. Do you think your library is the right choice for this purpose? If the answer is yes, is there any documentation about the protocol? If not, no problem which classes I have to check for the corresponding response logic? Thank you for your help.

**Comment by RevenantX** [comment]
> Do you think your library is the right choice for this purpose?

Hard question) You can use TCP for this program. OBS Studio works with TCP when streaming)

>  If the answer is yes, is there any documentation about the protocol?

There no documentation about protocol( Classes: NetPacket, NetPeer, NetManager (in some places), SequencedChannel, ReliableChannel )

I don't think that this is easy task to port this library) 
You can try write Android application using Xamarin. And library must work without rewriting)

**Comment by grill2010** [comment]
I think TCP is putting too much overhead because I've just access to a single frame and not an h.265 video stream or any similar video format.

I know that it will not be that easy but everything about real time streaming is not easy.  I would prefer to develop the Android app in Java because I've already some major parts written in Java. Anyway, thank you for your help. I will check what are my possibilities to achieve my goal.
