### ISSUE TITLE
A way to detect if the connection originates from the same application.

### ISSUE THREAD

**Issue by Saishy** [RevenantX/LiteNetLib#127]
So, is there a way to know if the connection originates from the same application? For example in unity this would be a listen server.

But not for the same computer or network, since the user could open multiple instances of the application.

I'm having a huge problem trying to differentiate if a client is from the same origin or not.

**Comment by RevenantX** [comment]
You can send additional info about peer (including some randomly generated (once) application id) after connecting.

**Comment by Saishy** [comment]
No chance to have that included in the lib huh?

**Comment by RevenantX** [comment]
> No chance to have that included in the lib huh?

I can add if you really need this.

> I kinda needed that info at the point of OnPeerConnected :2

Soon you will get this super feature)

**Comment by Saishy** [comment]
Woa, thanks! 💙

**Comment by Saishy** [comment]
I saw you added a way to send arbitrary data on connection request, is there a way to send a guid then so I know if the request is from same application?

If yes, could you give me an example?

**Comment by RevenantX** [comment]
@Saishy 
```csahrp
//client
NetDataWriter writer = new NetDataWriter();
writer.Put("gameKey");
writer.Put(someGuid);
client.Connect("192.168.1.126", 5050, writer);

//server
public void OnConnectRequest(ConnectionRequest request)
{
    var dataReader = request.Data;
    string key = dataReader.GetString();
    string guid = dataReader.GetString();
    //use guid.
    if(key == "gameKey")
        request.Accept();
}
```
But i see this can be better)

**Comment by RevenantX** [comment]
@Saishy added that method `request.Accept()` returns new peer so you can use peer.Tag to store some information)

**Comment by RevenantX** [comment]
@Saishy updated example.

**Comment by RevenantX** [comment]
@Saishy i can close this?

**Comment by Saishy** [comment]
Seems to be working!
