### ISSUE TITLE
Null Reference Error 

### ISSUE THREAD

**Issue by NVentimiglia** [RevenantX/LiteNetLib#128]
I am testing some network code. The nature of the tests requires rapid connection/reconnections. Doing this I think I may have broken LitNet.

> NetHost - Detach 1 DISCONNECTED
> NetHost - BroadcastOthers UserDisconnectSignal
> NetHost - BroadcastOthers EntityDisconnectSignal
> UdpHostMiddleware - OnPeerDisconnected Peer:636499487745762458 0 DisconnectPeerCalled
> UdpHostConnection - Disconnect ID:1 SEND:False
> UdpHostConnection - Disconnect aborted, is DISCONNECTED
> [R]Error: ThreadLogic - System.NullReferenceException: Object reference not set to an instance of an object.
>    at LiteNetLib.NetPeerCollection.RemoveAt(Int32 idx) in F:\Projects\LiteNetLib\LiteNetLib\NetPeerCollection.cs:line 61
>    at LiteNetLib.NetManager.RemovePeerAt(Int32 idx) in F:\Projects\LiteNetLib\LiteNetLib\NetManager.cs:line 343
>    at LiteNetLib.NetManager.UpdateLogic() in F:\Projects\LiteNetLib\LiteNetLib\NetManager.cs:line 469
>    at LiteNetLib.NetThread.ThreadLogic() in F:\Projects\LiteNetLib\LiteNetLib\NetThread.cs:line 100

I modified the NetThread to be like this to catch the exception. Catching leaves the host in a zombie state.

```

            try
            {
                while (_running)
                {
                    _callback();
                    Thread.Sleep(SleepTime);
                }
            }
            catch (Exception ex)
            {
                NetUtils.DebugWriteError("[R]Error: {0} - {1}", "ThreadLogic", ex.ToString());
            }
```

NetPeerCollection.RemovePeerAt is being called twice.

The First stack looks like this

> NetPeerCollection.RemoveAt 61
> NetPeerCollection.Remove 73
> NetManager.DisconnectPeer 315
> NetManager.DisconnectPeer 1078
> NetManager.DisconnectPeer 1044
> UdpHostConnection.DisconnectInternal (My Code)
> NetManager.NetEvent 394

The Second stack looks like this

> NetPeerCollection.RemoveAt 61
> NetPeerCollection.RemovePeerAt 343
> NetManager.UpdateLogic 469
> NetThread.ThreadLogic 100

Please advise on the best way to solve this. 

My Setup, running on DNC  :
            Manager = new NetManager(this, Options.MaxConnections, Options.Key);
            Manager.DiscoveryEnabled = true;
            Manager.NatPunchEnabled = true;
            Manager.MergeEnabled = true;
            Manager.UpdateTime = 16;
            Manager.UnsyncedEvents = true;

**Comment by NVentimiglia** [comment]
```
public void RemoveAt(int idx)
        {
            NetPeer peer = _peersArray[idx];

            if (peer == null)
                return;

            if (!_peersDict.ContainsKey(peer.EndPoint))
                return;

            // move all down ?
            _peersDict.Remove(peer.EndPoint);
            _peersArray[idx] = _peersArray[_count - 1];
            _peersArray[_count - 1] = null;
            _count--;
        }
```

Working mod. Worried about any side effects this might cause.

**Comment by NVentimiglia** [comment]
I solved the bug in my code.

My manager was handling the disconnect event and telling the peer instance to close. The peer was closing and detaching from the manager, causing a call to my manager (loop).

Leaving issue open, might be nice to idiot proof this.

**Comment by RevenantX** [comment]
@NVentimiglia there is some places (i think one) where that can be. But this code refactored in new branch (very unstable for now, but i almost fixed) and this bug will be fixed.

**Comment by RevenantX** [comment]
@NVentimiglia try new branch "packetprocessor". There is better peer handling code (but can be some new bugs). Also i need heavy testing of all new features)

**Comment by RevenantX** [comment]
I think fixed by https://github.com/RevenantX/LiteNetLib/commit/0250bd358979800c661b3a452ad56f4c8143a257
Reopen if not)
