### ISSUE TITLE
Endless Loop in ReliableChannel

### ISSUE THREAD

**Issue by liwei8257** [RevenantX/LiteNetLib#129]
I implement LiteNetLib in a  game server running at 15 fixed rates per sec with 2 packet per frame;
Logging in with 40 clients, I closed 20 of them.
After that the logic thread enter an endless loop in ReliableChannel's function "SendNextPackets()"

currentPacket has formed an heap loop and this function goes forever :(

Can anyone notice this problem?
I doubt if the cause is when the pendingPacket got removed and somehow its pre or next isn't clear?
```csharp
if (pendingPacket == _headPendingPacket)
{
    _headPendingPacket = null;
}
NetPacket removed = pendingPacket.GetAndClear();
```

cheers

**Comment by RevenantX** [comment]
Hm.. I will investigate this bug.
Try release version instead of master for now.

**Comment by liwei8257** [comment]
emmm , well ,there is another bug in Latest Release Verion's ReliableChannel 
Same in SendNextPacket() function
Here is how I got this bug:

assume: _queueIndex==_localSeqence % _windowSize 0
In SendNextPacket():
packet seq 100 send succuess  _queueIndex:1 _localSeqence 1
packet not find _queueIndex:2 _localSeqence 1
packet not find _queueIndex:3
pending seq 101 102:
_localSeqence 2 _localSeqence 3

packet find 102 in  _queueIndex:3!!! where 101 got skipped and client get a bad seq packet.

**Comment by RevenantX** [comment]
@liwei8257 but reliability works?

**Comment by liwei8257** [comment]
after 102 was skipped it I got 103 104 ... but never 102 for this client

**Comment by RevenantX** [comment]
@liwei8257 this is very strange. This method always worked. On my shooter game for month. How do you cause this? 
You sending data from one thread?

**Comment by liwei8257** [comment]
@RevenantX  I send all my data for all clients in the one thread inside logic tick.

After one of the packet( "102" in my case sometimes 2 or 3 packets) got skipped during sending , all following packets was considered as bad sequence on Client without ack therefore the server will resend all packets after 102 and finally crashed the socket.

I though the cause is that _queueIndex moved 1 per frame without find a packet while _localSeqence moved 2 or more in one call. As result the "SendNextPacket():" function will send the packet in a wrong sequence;

**Comment by RevenantX** [comment]
@liwei8257 try latest version from master.

**Comment by liwei8257** [comment]
@RevenantX 
emm... still got and endless loop. 
There are 20 threads for my 20 clients and each of them will have a NetPeer.send() call. But finally data will be send in main thread's logic tick. Was there any thread-safe problem? I wonder if the Linked-list for pending packet is not clearly enough to manage as we cannot get a directly look at what is going-on anytime.

**Comment by RevenantX** [comment]
Yeah. There is thread safety problem in NetPeer.Send that fixed in next version ( i think ). I will try backport thread safe fix.

**Comment by RevenantX** [comment]
@liwei8257 try latest version.

> I wonder if the Linked-list for pending packet is not clearly enough to manage as we cannot get a directly look at what is going-on anytime.

This is 64 element array. With linked-list-like elements) So you can debug easily.

**Comment by RevenantX** [comment]
@liwei8257 any news?

**Comment by liwei8257** [comment]
Sorry, I haven't go any further for I have replaced UDP solution to LidgrenNetwork and it worked well.
It must be thread-safe bug and I guess I will try to find out the problem when the manager didn't push me and I got more time.

**Comment by OnlyNoob** [comment]
My issue is the same, i think lib stuck after few packets >MTU if any part of packet will drop he doesnt resend it. To reproduce you need send 10-20 big packets (bigger than MTU) as reliable with SimulatePacketLoss and it stuck. Аs far as i can remember, this bug appeared after d16c5a564e5a55e5c3a3f1a10d0d919973b7d776

**Comment by RevenantX** [comment]
Oh guys. I found real mistake. thanks @OnlyNoob for reproduce)))

**Comment by OnlyNoob** [comment]
thanks for fix) @RevenantX
