### ISSUE TITLE
Encryption for packets 

### ISSUE THREAD

**Issue by mgamache** [RevenantX/LiteNetLib#13]
Does LiteNetLib support encrypting packets? I love your library, but need to have the data encrypted on the wire.

**Comment by NVentimiglia** [comment]
If you want encryption, I would obfuscate the payload outside of the transportation layer.

**Comment by mgamache** [comment]
I guess, I am not confident in my skill level regarding crypto. I was hoping for an implementation of DTLS.

**Comment by NVentimiglia** [comment]
For a game developer speed is at a premium and encryption is notably heavy. I personally do not wany any encryptions and would fork and remove this feature if implemented. If I needed security there are other ways to obfuscate the stream and that should be done at your serialization layer.

**Comment by mgamache** [comment]
Of course I wouldn't 'force' DTLS encryption on people who want to run without it.  

There's overhead due to the encryption headers (which can be large percentage of the packet size if you are sending lots of small packets. There's also CPU overhead, but I think that is handled by TPM hardware (like for TLS), right?  I suspect any added latency would be minimal. Also, I am not using this for a game (although I understand that's the most common use-case).  It looks like I'll have to encrypt the packets or use a TCP transport.

thanks for your comments,

**Comment by RevenantX** [comment]
This library oriented on speed. For high ping dependent games. I'm not pro at encryption too. And encryption in .NET not compatible with all versions of .NET implementations (unity3d mono as example).
I think if you need some encryption you can use TCP connection) Or do as @NVentimiglia said)

**Comment by mgamache** [comment]
Great point about the encryption compatibility across the different .net implementations. My product is mostly desktop, and requires encryption, so it's not your target use.  However, there's a point of view that *all* internet traffic needs to be encrypted. Just a thought, but I really like your library.

**Comment by mgamache** [comment]
Have you seen this lib? 
https://github.com/adamcaudill/libsodium-net

Does that provide a cross platform (Unity) encryption solution?

**Comment by RevenantX** [comment]
@mgamache this is wrapper and needs native library (.dll, .so)

**Comment by RevenantX** [comment]
Basic encryption (Xor) now is almost done by @Kaladrius2trip . After some checks i will merge this code into master https://github.com/RevenantX/LiteNetLib/tree/encryption

**Comment by mgamache** [comment]
that's good news.

**Comment by boonkerz** [comment]
but an encryption with private/public keypair is not possible with this construct or?
because we need any key exchange methods?

**Comment by mgamache** [comment]
not an expert, but you'll need some type of 'pad' that is used as a key. My understanding is the type of pad its storage/exchange is where the Xor encryption is most vulnerable.

**Comment by timematcher** [comment]
Maybe RSA key exhange (or a newer better key exchange algorithm's) support should be implemented?

**Comment by RevenantX** [comment]
@timematcher maybe. But now i don't have time to implement encyption fully

**Comment by trippleflux** [comment]
@RevenantX 
Any chance for this branch becoming mature?

**Comment by RevenantX** [comment]
@trippleflux sorry =(. Very busy right now at main work.

**Comment by trippleflux** [comment]
@RevenantX 
Sorry if i keep asking the question, how about now?.

**Comment by RevenantX** [comment]
@trippleflux encryption for now is not first priority. You can always encrypt sensitive data from your side.

**Comment by xmedeko** [comment]
Sometimes, encryption is a must even for gaming, e.g. see [IT Hare's UDP for games – security](http://ithare.com/udp-for-games-security-encryption-and-ddos-protection/).

But different projects may have different security requirements. Some are happy with just signing the packets. Some need just symmetric crypto (AES) because they are able to exchange keys securely (HTTPS). Others need full DTLS implementation. 

I am not aware of some small, C#, multiplatform DTLS only library. [BouncyCastle](https://github.com/bcgit/bc-csharp) has DTLS. However, the BouncyCastle has received some criticism in the past. The [Inferno](http://securitydriven.net/inferno/) claims to be better than BouncyCastle, but does not have DTLS.

[MLAPI](https://github.com/MidLevel/MLAPI/) project uses own [crypto](https://github.com/MidLevel/MLAPI/tree/master/MLAPI/NetworkingManagerComponents/Cryptography), which should be easy to separate and use for LiteNetLib only. But do not know about the quality of their solution.

Generally, implement security right is not simple. I would also prefer some existing code than building my own solution. (More eyes see more.) It may be some separate project, does not need to be in the LiteNetLib itself.

**Comment by xmedeko** [comment]
I've found the [Unity-Netcode.IO](https://github.com/KillaMaaki/Unity-Netcode.IO) project, looks promising.

Finally, we have decided to do UDP communication in our project unencrypted, all sensitive data will be transferred by HTTPS. Anyway, if there would be some easy to use, simple and fast encryption, like the Xor one in https://github.com/RevenantX/LiteNetLib/tree/encryption we will use it.

**Comment by Vonak** [comment]
Up this topic, i'm developing a game and have interest in DTLS support. This is a security mandatory requirement on some console platforms.

**Comment by Mun1z** [comment]
> Up this topic, i'm developing a game and have interest in DTLS support. This is a security mandatory requirement on some console platforms.

I also need encrypted packages, thinking of upgrading the encriptatin branch to the current version and using it. I will perform some tests later.

**Comment by RevenantX** [comment]
@Mun1z encryption branch is entirely broken and old (and incompatible with new code).

**Comment by RevenantX** [comment]
Added simple XOR encryption. 
So you can write wrapper around your favorite encryption like XorEncryption and use it.
