### ISSUE TITLE
NetDataReader Lifecycle

### ISSUE THREAD

**Issue by NVentimiglia** [RevenantX/LiteNetLib#130]
I noticed that the NetDataReader is pooled, very cool.

What is the life cycle of a NetDataReader instance? Is the NetDataReader single frame? Will I need to copy the bytes If I plan to queue them for use later? In my scenario I may need to handle the threading myself (Non-Unity environment)

**Comment by RevenantX** [comment]
@NVentimiglia yes its lifetime is one frame. You don't need to copy bytes. You can just create new data reader from exising. (Also i added clone method that doesn't copy data)

**Comment by NVentimiglia** [comment]
@RevenantX  How would I go about returning a cloned reader to the pool ? I worry about memory leaks from consumers hanging onto pooled readers and not returning them.

That said, Its no problem for me to copy the stream to a buffer to pass it to my logic layer (I already need to do this for my WS transport).
