### ISSUE TITLE
Clearing _netEventsQueue in NetManager.Start() not entirely threadsafe

### ISSUE THREAD

**Issue by GitFlip** [RevenantX/LiteNetLib#131]
https://github.com/RevenantX/LiteNetLib/blob/438e1cbda31f1e1af1658ee4ce1f7d61db1f0a94/LiteNetLib/NetManager.cs#L919

Please correct me if I'm wrong, but if I stop my Client's connection to a server and switch to another server very quickly essentially calling Client.Stop() and then Client.Start() right after the OnPeerDisconnect Event is fired I will receive an error on line 919 that the _netEventsQueue is already equal to zero.

I haven't fully figured it out, but I'm guessing that I still have some events in the queue, thus I'm in that while loop. Then another thread of mine is calling Start() since I've processed the Disconnect event. Now the _netEventsQueue has been cleared while being processed since I called Start().

Currently my trigger for switching servers is having a thread wait for the client to receive the disconnected event and then connect to the next server, but it seems like I may in fact need to wait until all events have been processed, not just the disconnect. Either that, or their should be a lock around _netEventsQueue.Clear() in Start().

Any suggestions?

**Comment by RevenantX** [comment]
> I will receive an error on line 919 that the _netEventsQueue is already equal to zero.

Yes. This is just bug) Thanks for report)
