### ISSUE TITLE
Determine the channel type in NetworkReceiveEvent

### ISSUE THREAD

**Issue by nxrighthere** [RevenantX/LiteNetLib#132]
It's possible to determine the channel type (reliable or not) in NetworkReceiveEvent, without sending additional data?

**Comment by RevenantX** [comment]
@nxrighthere no. Only internally. You need this feature?

**Comment by nxrighthere** [comment]
Yes, it would be great to have this feature.

**Comment by RevenantX** [comment]
Implemented in new version (0.8) with other big changes.

**Comment by nxrighthere** [comment]
That was fast! Thank you!

**Comment by RevenantX** [comment]
@nxrighthere but this branch (master) for now unstable) Please report any bugs)

**Comment by nxrighthere** [comment]
Sure. Currently, I'm working on [console application](https://github.com/nxrighthere/BenchmarkNet) for benchmarking the reliable UDP networking libraries. Here is the LiteNetLib results (master branch):

64 clients
https://i.imgur.com/y7AqlxG.png

500 clients
https://i.imgur.com/zisFF8c.png

1000 clients
https://i.imgur.com/CFgNN0h.png

**Comment by RevenantX** [comment]
@nxrighthere wow cool. This can help me to fix some possible performance issues.

**Comment by nxrighthere** [comment]
It will be released very soon. I'm just waiting until Unity devs will fix some huge problems with memory leaks in UNet.

**Comment by nxrighthere** [comment]
[BenchmarkNet](https://github.com/nxrighthere/BenchmarkNet) has been released. Feel free to test it by yourself.

**Comment by nxrighthere** [comment]
You can find the latest results [here](https://forum.unity.com/threads/benchmarknet-stress-test-for-enet-unet-litenetlib-lidgren-and-miniudp.512507/).
