### ISSUE TITLE
Example on NAT Punch

### ISSUE THREAD

**Issue by NFMynster** [RevenantX/LiteNetLib#133]
Very sorry if I should't be making an issue for this!
Is there someplace that has an example for how to use the NAT punch with this library?

**Comment by RevenantX** [comment]
@NFMynster there is mini sample: https://github.com/RevenantX/LiteNetLib/blob/master/LibSample/HolePunchServerTest.cs
but i plan add better example project)

**Comment by NFMynster** [comment]
Ah awesome, thank you very much.
