### ISSUE TITLE
System.Net.Sockets.SocketException since 0.7.7

### ISSUE THREAD

**Issue by Kamiperat0r** [RevenantX/LiteNetLib#135]
Hello,
Please excuse me for this bad English, it's a Google translation.

Since the relase 0.7.7
I have the following exception that happens randomly:

{"A message sent on a datagram socket was larger than the internal message buffer or another network boundary or the buffer used to receive a datagram was smaller than the datagram itself"} System.Net.Sockets .SocketException.

This exception occurred on line 203 of NetSocket.cs

After this exception occurs 1-5 times, the connection stops working but is not disconnected.

Do you have an idea of where this can come from?

Full Exception:
`System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=Un message envoyé sur un socket datagramme était plus volumineux que le tampon de messages interne ou qu’une autre limite réseau ou bien le tampon utilisé pour recevoir un datagramme était plus petit que le datagramme lui-même
  Source=System
  Arborescence des appels de procédure :
   à System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP) dans f:\dd\NDP\fx\src\net\System\Net\Sockets\Socket.cs :ligne 1689
`

**Comment by RevenantX** [comment]
Thanks for bug report!)
