### ISSUE TITLE
Debug Logger @ NetUtils.cs error CS0117

### ISSUE THREAD

**Issue by Fyffe** [RevenantX/LiteNetLib#139]
Hello, I've noticed there is a small bug in NetUtils.cs DebugWriteLogic function. on Unity It's easy to fix but I thought I'll just put it here to let you know.

`
if (NetDebug.Logger == null)
                {
#if UNITY
                    UnityEngine.Debug.Log(string.Format(str, args));
#elif WINRT
                    Debug.WriteLine(str, args);
#else
                    Console.ForegroundColor = color;
                    Console.WriteLine(str, args);
                    Console.ForegroundColor = ConsoleColor.Gray;
#endif
                }
                else
                {
                    NetDebug.Logger.WriteNet(color, str, args);
                }
`

#if UNITY should be #if UNITY_EDITOR

**Comment by RevenantX** [comment]
@Fyffe no this is correct. I 0.7.x versions you must add "UNITY" define. In 0.8.x versions i added more precise define for newer unity versions.

**Comment by Fyffe** [comment]
@RevenantX No idea why I'm getting error on Unity 2017.2.0f3 then, I'll stick with it for now and wait for 0.8

**Comment by RevenantX** [comment]
@Fyffe add to define symbols UNITY.

**Comment by RevenantX** [comment]
Player settings ->
![](https://forum.unity.com/proxy.php?image=https%3A%2F%2Fi.imgur.com%2FwXw3uPZ.png&hash=c26a082cd17fe99053db6d7df60a70d8)

**Comment by Fyffe** [comment]
@RevenantX Ah, right. Got it, thanks!
