### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NVentimiglia** [RevenantX/LiteNetLib#14]
I`m going through the code and one thing that is lacking is comments. A simple three slash (summary) comment on the head of public methods and classes would go a long way.

Maybe we could start with the interfaces?

Take INetEventListener : Super important... Yet, I can only guess at what OnNetworkReceiveUnconnected is or about any of the implementation details behind it.

**Comment by RevenantX** [comment]
I agree. Right now i'm very busy with main work. But when i get some free time i will create doc for this classes.

**Comment by RevenantX** [comment]
Added more documentation.

**Comment by DreadBoy** [comment]
I'd like to add that `NetDataReader.GetString` shall be called only once inside `OnNetworkReceive`. I'm not sure whether this is assumed knowledge but I've spent quite some time on this behaviour and it might be useful to add that to method's description.

**Comment by RevenantX** [comment]
@DreadBoy why it should be called only inside ```OnNetworkReceive```? 
Maybe you about that ```NetDataReader``` ( that is argument in OnNetworkReceive ) shall be used only from that method - becuse data after ```OnNetworkReceive``` ended - will be erased?

**Comment by DreadBoy** [comment]
No, I meant only **once**. Consider the code below:

    public void OnNetworkReceive(NetPeer peer, NetDataReader reader)
    {
        Debug.Log("Got " + reader.GetString(1000));
        OnCommandReceived(reader.GetString(1000));
    }

Second call to `GetString` will throw error because `_position = _data.length`.

**Comment by boonkerz** [comment]
any getxxx method remove the returned value.
when you have 2 getstring methods you must send an message with 
NetDataWriter with 2 put commands

as example:
https://github.com/boonkerz/teamscreen/blob/master/Network/Messages/Connection/ResponseScreenshotMessage.cs

**Comment by RevenantX** [comment]
documentation now in better state and i constantly update it.
