### ISSUE TITLE
Help deciding between this, and custom network built on top of WebRTC

### ISSUE THREAD

**Issue by miketheprogrammer** [RevenantX/LiteNetLib#140]
( Any mention of WebRTC below strictly refers to the DataChannels spec )
I am trying to decide on whether to utilize LiteNetLib or my own networking library on top of WebRTC as a dll. 

WebRTC utilizes STUN for udp punchthrough and boasts a ~96% success rate ( Googles quoted numbers ), it utilizes TURN as a relay for the other ~4%.

What to your knowledge is the reliability of your NAT HolePunch technique.

Another question I have is do you think i will encounter a problem with packet overhead with WebRTC. WebRTC encrypts all communications end 2 end. I am trying to determine how much of a standard practice this is in games. 

Whereas your framework boasts tiny packet overheads.

Awesome I also just realized you implement Send Mechanics similar to SCTP which is the protocol used by WebRTC and very important to my need for fine grained mechanics.

```
Different send mechanics
Reliable with order
Reliable without order
Ordered but unreliable with duplication prevention
Simple UDP packets without order and reliability
```

If I utilize your network, the signaling server from my webrtc implementation, just becomes a matchmaking server, that returns an ip and a port to connect to.

As I am writing this, I am realizing the true extent of your genious. It seems that if i utilize this library i can get most of the advantages of webrtc
```
P2P
NAT Punch Through
SCTP like Send Mechanics

I am guessing congestion control is implemented by using 
 - Reliable without order
 - Ordered but unreliable with duplication prevention
```

**Comment by NVentimiglia** [comment]
Out of curiosity, is there a C# WebRTC library you can reference ? Ive seen a few JS libraries, which wont work for me as I have a common C# logic layer.

**Comment by miketheprogrammer** [comment]
@NVentimiglia - I have implemented by own webrtc bindings in C++, with a C# wrapper using P/Invoke. The intent was to use it in the Unity engine for game development. I was going to sell it after it matured, but I don't think I have the skill level or time to properly maintain a cross platform native binding. If you want I can share some of the current OSX source with you, or at the very least point you in the direction of how to begin implementing it.

I spent many many hours just trying to get a basic osx build working and importing in to unity. Havent event started on windows / android yet.

Additionally I have only implemented the DataChannels without Video / Audio.

However, data channels rock, I was able to connect to a web page, and control a game object from the browser.

**Comment by miketheprogrammer** [comment]
@NVentimiglia - I forgot, there is one C# UWP library, that works with windows. https://github.com/webrtc-uwp/webrtc-windows

**Comment by RevenantX** [comment]
@miketheprogrammer i think you must decide by yourself. Compare features and things that you need. I don't used WebRTC and don't know much about it.

**Comment by miketheprogrammer** [comment]
@RevenantX  Thanks I will close the issue, I think I have already decided to use yours, and contribute back to it.
@NVentimiglia - Feel free to contact me via email, but this issue is closed now.
