### ISSUE TITLE
PeerDisconnectedEvent Called twice

### ISSUE THREAD

**Issue by Skinz3** [RevenantX/LiteNetLib#143]
Hi, im using your library, and when i call on my client myNetPeer.Disconnect();

The server is calling PeerDisconnectedEvent(); a first time, and a second time, 5000ms later, its the DisconnectTimeout, but why is this event called twice and why the client isnt removed from PeerClientCollection _peers when i disconnect at the first time?

Thanks

**Comment by RevenantX** [comment]
@Skinz3 master branch not well tested) If you want more stable version use https://github.com/RevenantX/LiteNetLib/tree/0.7 
This is just bug) I will fix it)

**Comment by Skinz3** [comment]
Okay :) Thanks, btw your library is well done ^^
