### ISSUE TITLE
Connection source type

### ISSUE THREAD

**Issue by Eideren** [RevenantX/LiteNetLib#146]
Hey, thanks a whole bunch for this lib, it's really nice to work with !
So, this is a small feature request, I have a P2P network setup and it would be helpful if I knew whether the connection I received on a peer came from a response to a request he sent or is actually coming from a request of another peer to connect to him.

I could just log the connection the peer tried to establish and when I receive the connection see if I sent a request but that won't work when two peers connect to each other at the same time, on my side I would see that the peer sent a connection request but I wouldn't know that what I received, instead of a reply to my request, might just be another connection request coming from the remote peer. I need that information to properly synchronize a shared state.

Thanks !

**Comment by RevenantX** [comment]
@Eideren are you using 0.7.x version? In 0.8 there new event. So by using this you can determine what you want. 
```csharp
listener.ConnectionRequestEvent += request =>
{
    request.AcceptIfKey("SomeConnectionKey");
};
```

**Comment by Eideren** [comment]
Yep, I was using the latest release. I ported my code over to 0.8 and this event is just what I need, thanks again !
