### ISSUE TITLE
static reference of the NetManager instance or converting everything to static design

### ISSUE THREAD

**Issue by alexr1221** [RevenantX/LiteNetLib#147]
Hello,

```csharp
netPeer.NetManager
```
I was wondering if the .NetManager property of the NetPeer class was useful and even if it was a bad idea. Since there is only one instance of NetManager in runtime, the NetManager property will always return this instance. I'm not sure that it's meaningful to have NetManager linked to each peer since it's not their NetManager. 
For all of the stuff linked to the peer's netManager, maybe an idea would be to create a static instance NetManager.Instance. It would be also easier to access to the instance. At the moment, if we are using unity, we have to create a sort of networkManagement class where our instance is defined but it's more trickier to access to it. If we want to send the position of an object from another class it'll be not hard but not ergonomic, whereas we could access to the instance from everywhere through NetManager.Instance. 

But what about converting everything to a static design? I think it would be more suited to this class. I really like the way Photon's library is designed. Then it could look like this:

```csharp
//  client
NetManager.ConnectToServer("127.0.0.1", 5000);
NetManager.Update = 5;

// server / host client
NetManager.CreateServer(5000, 128);

// random actions
foreach (NetPeer n in NetManager.ConnectPeerList)
{
    NetManager.Send(new byte[]{}, n);
}

// under a Monobehavior class
NetManager.Send("pos|" + transform.position.ToString() + "|"); 
...
```

**Library version**: [commit id (9f2a1d1a8244510d9ec502cc002bfdddba666d09) or release version (0.7.7.1)]

**Comment by RevenantX** [comment]
@alexr1221 hi!) Application can have many instances of NetManager. This is okay and used in some places.

> But what about converting everything to a static design? 

No. This is bad idea. Just make singleton in your game with needed properties available to other classes.

**Comment by alexr1221** [comment]
In fact you are right because I just remembered we could not create multiple "rooms" with this system. But what about the .NetManager property of the NetPeer class?

**Comment by RevenantX** [comment]
@alexr1221 this is just handy sometimes.

**Comment by alexr1221** [comment]
Ok so since the beginning there is something like 4 - 0 concerning who is right between you and me, but don't you think it's ambiguous to have a NetManager attached to each NetPeer?

**Comment by RevenantX** [comment]
@alexr1221 imagine that you create player like this
```csharp
class Player
{
    private readonly NetPeer _peer;
    public Player(NetPeer peer)
    {
        _peer = peer;
    }
}
```
And in some place you want send message to all players.
```csharp
class Player
{
    //...
    public void SendMessageToAll()
    {
        _peer.NetManager.SendToAll(/* ... */);
    }
}
```
Just as example.

**Comment by wobes1** [comment]
Does it mean that A client can omit the Server and send a message to every single peer? So there is no Dedicated server model?

**Comment by RevenantX** [comment]
> Does it mean that A client can omit the Server and send a message to every single peer?

No) Client `NetManager` will have one peer. And SendToAll method just will send message to server.

**Comment by alexr1221** [comment]
Thanks for the replies but I still don't understand the interest _peer.NetManager.SendToAll(/* ... */); since you said it'll perforce be sent from to the host peer. It's maybe useful for the host or server but a simple _netMangerServer.Send(msg, _peer) would be enough and would avoid having this NetManager property on each peer

**Comment by RevenantX** [comment]
@alexr1221 if you writing code without singletons or static data (for example many instances of game in same application) and use manual dependency injection (by passing components that you need in constructor). You will have less code.

> _netMangerServer.Send(msg, _peer)

_peer.Send(msg) =)

>  It's maybe useful for the host or server

Yes. Each peer must have `NetManager` because of implementation. So why it can't be public?

**Comment by alexr1221** [comment]
@RevenantX So if I understood, it's for the case where we have multiple NetManagers and that we want to resend a message to this special peer, without having to know from which NetManager it comes?

**Comment by RevenantX** [comment]
@alexr1221 there are many places where you can use this property) If you don't like it - just don't use)

**Comment by alexr1221** [comment]
Ok thanks for the replies

**Comment by NVentimiglia** [comment]
As someone with an integration tested enterprise architecture -  That is a requirment for many NetManagers inside a single process, I would like to point out that reliance on a static helper method could cause issue. If you need a static helper, you should write your own ServiceHost / IOC.
