### ISSUE TITLE
Is it possible to improve NetSerializer so it can serialize boxed-object property?

### ISSUE THREAD

**Issue by sorencoder** [RevenantX/LiteNetLib#149]
I know that net serializer only supports basic types. I want to know is it possible to improve this serializer to be able to serialize basic types that are boxed?

```
public class SamplePacket
{
        public object Prop { get; set; }

        public SamplePacket(object prop)
        {
            Prop = prop;
        }

        public SamplePacket()
        {

        }
}
```
...
`var packet = new SamplePacket("abc");`

as you can see the `Prop` in the `packet` is a string object, but NetSerializer cannot serialize such a property.

**Comment by RevenantX** [comment]
@sorencoder 
>  I want to know is it possible to improve this serializer to be able to serialize basic types that are boxed?

No. This serializer generates delegates with precalculated types once when you call `Subscribe` for faster speed.

**Comment by sorencoder** [comment]
> No. This serializer generates delegates with precalculated types once when you call Subscribe for faster speed.

I could find a way to serialize `object` properties, but it doesn't work for `object[]`. 

should I submit a PR?

**Comment by sorencoder** [comment]
@RevenantX 
take a look at this PR: #151
