### ISSUE TITLE
Why this library is not on Unity Assetstore?

### ISSUE THREAD

**Issue by sorencoder** [RevenantX/LiteNetLib#152]
This library works perfectly with unity and even performs better than Unet. Why it's not on assetstore?
It's much easier to update library from assetstore in a unity project.

**Comment by Eideren** [comment]
The lib is too low level for users of the asset store, they probably would expect a bunch of monobehaviours included to help them out. It's also a pain for publishers to update their assets through Unity's API and it often takes too long (~4 days) for updates to be available on the store.
While just pointing to a repo would actually give people more incentives to contribute to it than an asset on the store would and updating through git is safer.
All of this is going to require additional resources to maintain, now RevenantX can do whatever he wants but I personally don't think it's worth it.

**Comment by sorencoder** [comment]
> It's also a pain for publishers to update their assets through Unity's API and it often takes too long (~4 days) for updates to be available on the store.

I didn't know that it takes this long. surely cloning git repo and deleting unnecessary files will take less than 4 days 😄

**Comment by nxrighthere** [comment]
Submitting something to the Assets Store (especially if your asset is updated often) it's a pain in the ass. An extensive time to validation is just the beginning of a headache that awaits you further.
