### ISSUE TITLE
NTP Functionality

### ISSUE THREAD

**Issue by hyperion51** [RevenantX/LiteNetLib#154]
There's mention of NTP time requests in the readme.

I hate to make an issue of this, but I seriously can't find the relevant code, though to be fair all I tried was looking through the samples and hoping to stumble upon it via Intellisense (isn't there any documentation?). Where do I find LiteNetLib's NTP functionality?

As an aside, I'm using LiteNetLib for game networking, and it's very important for me to establish a common time basis synchronized as closely as possible. Am I right in assuming NTP is the best way to go about this?

**Comment by NVentimiglia** [comment]
https://github.com/RevenantX/LiteNetLib/blob/1c1aae653ed9c4cc19a0fbf8f88bd287bbcf47e2/LibSample/Program.cs
