### ISSUE TITLE
Unity compilation for UWP doesn't work with LiteNetLib plugin

### ISSUE THREAD

**Issue by Upd4ting** [RevenantX/LiteNetLib#155]
Information about bug or feature

Compilation doesn't work https://gyazo.com/a340f9e07653cba91dd2a60534c158de
Any things to do in Unity to make it work?

**Library version**: Last release version

**Framework**: Unity

**OS**: Windows

**Comment by RevenantX** [comment]
@Upd4ting try place [LiteNetLibNetCore-0.8.250.zip](https://ci.appveyor.com/api/buildjobs/559exq1349n18ve8/artifacts/LiteNetLibNetCore%2Fbin%2FLiteNetLibNetCore-0.8.250.zip) this dll in your project instead of source for UWP.

**Comment by RevenantX** [comment]
@Upd4ting or try use ".Net Core" in compilation overrides for UWP

**Comment by RevenantX** [comment]
https://docs.unity3d.com/Manual/class-PlayerSettingsWSA.html

**Comment by RevenantX** [comment]
@Upd4ting and if you use last release version (0.7.7.1) add define WINRT

**Comment by Upd4ting** [comment]
@RevenantX So I tried to add define WINRT and i was already using .Net Core in compilation overrides for UWP and I have still these assembly missings errors. Does that matter that i'm compiling for Hololens?

**Comment by RevenantX** [comment]
This is strange. Because when WINRT defined (in 0.7.7.1 version) there no usings of System.Net.Sockets.

**Comment by Upd4ting** [comment]
Yeah that's strange as you can see I defined the things https://gyazo.com/250635d695e5538e0b45c06f65f4a617

and I have still this error: https://gyazo.com/7e919846d2586f6651bec8f547335f92

As you can see that's not only the System.Net assembly that it's missing and all the missings assembly come from LiteNetLib.dll that I compiled manually with the last release source

**Comment by RevenantX** [comment]
@Upd4ting you define in wrong place...

**Comment by RevenantX** [comment]
https://docs.unity3d.com/uploads/Main/ScriptDefines.png

**Comment by Upd4ting** [comment]
@RevenantX Uh sorry but where should I put this define? In the dll before compiling it?

**Comment by RevenantX** [comment]
https://docs.unity3d.com/Manual/PlatformDependentCompilation.html

**Comment by Upd4ting** [comment]
Hmm still have errors, is that the correct way to define it? 
https://gyazo.com/06894e5abb4c65d0038bb22952e984a7

**Comment by RevenantX** [comment]
@Upd4ting WINRT 
defines are case sensitive.

**Comment by Upd4ting** [comment]
@RevenantX 
Still the same :/ https://gyazo.com/39d508271be16012cc3e8dc97009a618
Thanks for trying to help btw :D

**Comment by RevenantX** [comment]
@Upd4ting then just use https://github.com/RevenantX/LiteNetLib/releases/download/0.7.7.1/LiteNetLibWin81-0.7.7.1.zip for UWP and https://github.com/RevenantX/LiteNetLib/releases/download/0.7.7.1/LiteNetLib-0.7.7.1.zip for editor.

**Comment by Upd4ting** [comment]
I'll try and let you know thanks

**Comment by Upd4ting** [comment]
That's building perfectly now! Thanks @RevenantX
