### ISSUE TITLE
Server not receiving request

### ISSUE THREAD

**Issue by Upd4ting** [RevenantX/LiteNetLib#156]
It seems that my server isn't receiving all the request. Client send around 30 request per second and the server only receive one sometime.

Client code: https://hastebin.com/omujamegod.cs
Server code: https://hastebin.com/akavofogup.vbs

**Library version**: Last released version

**Framework**: Unity, .NET Framework

**OS**: Windows

**Comment by RevenantX** [comment]
@Upd4ting do you call PollEvents on server?

**Comment by Upd4ting** [comment]
@RevenantX Yeah I have this https://gyazo.com/881c2f84cbd612b1ce95a7673df74a13

**Comment by RevenantX** [comment]
@Upd4ting connection event works?

**Comment by RevenantX** [comment]
@Upd4ting this is very strange code anyway...

**Comment by RevenantX** [comment]
@Upd4ting look at example https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLibSampleUnity/Assets/GameClient.cs

**Comment by Upd4ting** [comment]
I'll read that and adapt my code to use this pattern, i'll tell you if that helps :)
Thanks for being active on this!

**Comment by Upd4ting** [comment]
With this lib I can make so Client connect to server, and client dialog with the server and server respond right?

**Comment by RevenantX** [comment]
@Upd4ting you can do this with simple TCP socket :) This library intended for fast multiplayer games)

**Comment by Upd4ting** [comment]
@RevenantX I don't want to use TCP because I need something fast.  Does that mean that dialog between client-server is not possible with this library?
I need something fast because i'm sending 30 request second with pictures from a camera and the server will do computer vision and send result

**Comment by RevenantX** [comment]
@Upd4ting any communication type is possible with this library. This just depends on how you implement this. This library is just transport.

**Comment by RevenantX** [comment]
@Upd4ting if all your data must be sent reliably (reliable ordered) better use TCP.

**Comment by Upd4ting** [comment]
@RevenantX TCP would be faster than this? I just need them ordered not reliable

**Comment by Upd4ting** [comment]
Is there an option for that ?

**Comment by RevenantX** [comment]
@Upd4ting https://github.com/RevenantX/LiteNetLib/blob/0.7/LiteNetLib/NetConstants.cs

**Comment by RevenantX** [comment]
@Upd4ting SendOptions.Sequenced.

**Comment by Upd4ting** [comment]
I have this error: Error: Unreliable packet size > allowed (1429)
Is there a way to increase this?

**Comment by RevenantX** [comment]
@Upd4ting automatic fragmentation works only for reliable packets. So you can split packet by hands into small pieces. (by size of MTU)

**Comment by Upd4ting** [comment]
@RevenantX Yeah that's understandable. So if I need that ReliableOrdered will your UDP lib be faster that just a TCP implementation?

**Comment by RevenantX** [comment]
@Upd4ting no.

**Comment by Upd4ting** [comment]
@RevenantX Okay thanks. I'll do some testing on my side. Thanks for helping!
