### ISSUE TITLE
[Question] Design question related to your framework

### ISSUE THREAD

**Issue by SynergiAios** [RevenantX/LiteNetLib#157]
Currently I'm finishing my swiss army knife authoritative networking framework for unity. It is of course based on your awesome c# library for the networking basics. And currently I'm trying to figure out, what to suggest in my documentation to the people. I currently have 2 possibilities in my framework to run the server:

1) Snapshots are send unreliable and each message always contains a full snapshot.
2) Snapshots are send reliable and each snapshot is a delta to a previous one

The first possibility is limited to like max 100 objects. The second one can deliver unlimited objects. Both have their advantages and disadvantages but there is one major thing I currently think about and I need to ask you for technical informations how your framework behaves, as I can't test it really as I can"t simulate that many clients currently.

So what is, if I go with possibility 2 where every package sent is in a reliable channel. And there are like 200 people connected. And like in the worst case, something between 40-70 people are constantly having a bad connection. How would LiteNetLib behave, if it has to constantly track a bunch of people not acking packages, built up queues, .... 

Is there any major problem possibly occurring with such a bad situation, or will there be no problems?

**Comment by nxrighthere** [comment]
You can test it by yourself using [BenchmarkNet](https://github.com/nxrighthere/BenchmarkNet) as a base for your simulation and combine it with [Clumsy](http://jagt.github.io/clumsy/) to simulate a bad network condition. It will give you some vision of what will happen in such scenarios.

**Comment by SynergiAios** [comment]
Oh that is awesome didn't know something like this actually exists. That is awesome. A way to actually test the bare bones for a huge amount of clients. I will definitely check it out to see if I can get an answer with this framework. Such open source projects, make me feel very bad for writing a paid solution for networking x)

**Comment by NVentimiglia** [comment]
What I do is this
- Subdivide the messages into relevancy sets (rooms)
- I have a 'create' signal that is reliable, the bulk of my data is here.
- I issue nonreliable snapshots of position and weapon state (x, y, z, velocity, fire1, fire2)
- If you miss a snapshot, extrapolation takes over for minimal 'snap'

Ive played with more complex lockstep implementations in the past. They are great for strategy games where you can wait for the players next 'turn'. For twitch games, you can find yourself in a state of 'network contango' which is hard to model out correctly. My take away is if things are moving fast, you want minimal moving parts between the object and the stream.
