### ISSUE TITLE
Pure curiosity - swapping raw sockets for Steamworks p2p API?

### ISSUE THREAD

**Issue by justonia** [RevenantX/LiteNetLib#158]
I love the abstraction you have created with this library but I am curious how hard it might be to support a pluggable socket backend such that one could use either raw C# sockets or say, the Steamworks P2P API:

https://partner.steamgames.com/doc/features/multiplayer/networking

The latter is quite nice since it handles NAT punching (with a free fallback relay server if it fails) and peer discovery. The API is quite similar to a regular socket backend and it should also be fully threadsafe.

Also here are the two C# wrappers for Steamworks:

https://github.com/Facepunch/Facepunch.Steamworks
https://github.com/rlabrecque/Steamworks.NET

**Comment by Krakean** [comment]
Interested in this question too.

@RevenantX ping :)

**Comment by RevenantX** [comment]
@justonia @Krakean i don't know how Steamworks P2P API works. But you can use "reuse" socket option. Inside library similar UDP raw sockets used.

**Comment by yacuzo** [comment]
If anyone still wants this I would suggest doing the same concept as for the new layer system (CRC & encryption). Extract a NetSocketBase from the current NetSocket (maybe rename this to UdpNetSocket), take that as a parameter in the NetManager constructor (having NetSocket as a default value for backwards compatibility) and create a new SteamworksSocket that inherits from NetSocketBase.

It is also possible to add WebSocket support this way.

**Comment by RevenantX** [comment]
Added that if you set "count" after processing inbound packed - it will be ignored by LiteNetLib - so now this is supported.
