### ISSUE TITLE
NetDataReader should check if enough data is available

### ISSUE THREAD

**Issue by c0nnex** [RevenantX/LiteNetLib#160]
NetDataReader does not check if enough data is available to deserialize. e.g. GetString() should check if enough bytes are available for reading the string. This can happen if a DataObject has changed it's structure (a new prop was added)
Currently it simply fails with 
```
OnNetworkReceive System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at LiteNetLib.Utils.NetDataReader.GetString() in LiteNetLib\NetDataReader.cs:line 340
```

**Comment by RevenantX** [comment]
@c0nnex all methods of NetDataReader doesn't check available bytes. Because this doesn't always needed. For cases you need to add check you must check `AvailableBytes` by hands.

**Comment by c0nnex** [comment]
Yes, but some will need it (e.g. for strings or arrays). For those needing data it should be checked by the datareader. What is the sense of using the packetprocessor, if it does not check if tehre is enough data to read, and you end up checking the data manually before it gets deserialized?
Imho it's not a good habit to throw unhandled exceptions. It would be better to provide a "OnDeserializationFailed" interface or something like that.
In my case I am deserializing a INetSerializable and for an unknown reason the paket received by the server did not contain all the data that should be in the structure. I cannot tell exactly why that was happening,  as both server and client share the same paket-structure and upon the second try all fata was received correctly. Still investigating this.

**Comment by RevenantX** [comment]
@c0nnex i can add length checks to NetPacketProcessor. But not into NetDataReader.

**Comment by marcejohnson** [comment]
While converting from .7.7.2 to .8 indev I got this error.  I got around it by passing in the `reader.RawDataSize` to `GetString()`....  as in `NetPacketReader.reader.GetString(reader.RawDataSize);` . 
Perhaps the function could do this by default, but just sharing in case this helps anyone else make the move to latest!  :-)

**Comment by RevenantX** [comment]
@marcejohnson RawDataSize is wrong thing for this.

**Comment by RevenantX** [comment]
@c0nnex done with TryGet methods.
