### ISSUE TITLE
Disconnected Peers are not removed on Server

### ISSUE THREAD

**Issue by c0nnex** [RevenantX/LiteNetLib#161]
2018-03-01 20:41:25.7979 | Debug | Connected Clients: 4
2018-03-01 20:41:27.8762 | Debug | Client disconnected: 93.208.221.94:4239 : RemoteConnectionClose
2018-03-01 20:41:30.8139 | Debug | Connected Clients: 4 

As you can see the peer is not removed after a disconnect is initiated from the client.
(Connected Clients outputs NetManager.PeersCount every 5 seconds)

(current master branch)

**Comment by RevenantX** [comment]
@c0nnex PeersCount != Connected clients. To get connected clients use `public NetPeer[] GetPeers(ConnectionState peerState)` with `ConnectionState.Connected`

**Comment by c0nnex** [comment]
Imho there is a general mismatch in the logic.
E.g. if i have a client (maxcon = 1) , disconnect that one and want to reconnect to the server , i will always get the disconnected peer back and every send to it will not happen. Currently i need to dispose the client-NetManager and reinstanciate it, which makes it very tricky, because i am using fixed ports. (reusing timeouts for lingering sockets etc)

**Comment by c0nnex** [comment]
Tried this over and over again now. A "reused" Client-peer (because you reuse it internally) will not receive any stuff. Either the server does not send or the peer does discard the message becasue it thinks it already got it.
Too bad, thought LiteNetLib is a suitable (lightwight, better, faster) replacement for Lindgren, but it's not reliable enough currently to be considered really.

**Comment by RevenantX** [comment]
@c0nnex you are using unstable master branch (there are notice in readme). Yes there is bugs, because i don't have many time for now to find them.

**Comment by RevenantX** [comment]
This fixed in master
