### ISSUE TITLE
Connected state on disconnected peer 

### ISSUE THREAD

**Issue by davinpra** [RevenantX/LiteNetLib#163]
NetPeer would still have Connected ConnectionState even after being disconnected
i'm using 0.7.7.1

**Comment by RevenantX** [comment]
@davinpra can you show minimal example with reproduce?

**Comment by davinpra** [comment]
if you check the connection state of the peer from OnPeerDisconnected parameter it will return connected while it should be disconnected, even if you call DisconnectPeer from NetManager it will still return connected, however on master branch the behaviour is correct

`

    public void OnPeerDisconnected(NetPeer peer, DisconnectInfo disconnectInfo)
    {
        Console.WriteLine("[Server] Peer disconnected: " + peer.EndPoint + " " + peer.ConnectId + ", reason: " + disconnectInfo.Reason + ", status: " + peer.ConnectionState);

        netManager.DisconnectPeer(peer);



        Console.WriteLine("status: " + peer.ConnectionState);

    }`

**Comment by Krakean** [comment]
@RevenantX any progress on this?

**Comment by RevenantX** [comment]
@Krakean this fixed in 0.8

**Comment by Krakean** [comment]
@RevenantX 
Thanks.
When you plan to release v0.8 stable? :)

**Comment by RevenantX** [comment]
@davinpra @Krakean 
fixed in 0.7 branch.
