### ISSUE TITLE
NetDataWriter type not found when Referencing DLL

### ISSUE THREAD

**Issue by pha3z** [RevenantX/LiteNetLib#164]
Is NetDataWriter intentionally left out of the compiled DLL?  When I add the DLL to my own solution, everything works fine with the GitHub sample code except for this:

`The type or namespace name 'NetDataWriter' could not be found (are you missing a using directive or an assembly reference?)	`

Should I be doing something more than just sticking the LiteNetLib dll into my project as a reference?

Also, I'm having trouble figuring out what the difference is between the three DLLS:  LiteNetLib, LiteNetLibCore and LiteNetLibStandard.   I'm guessing it has something to do with different .NET architectures, but I am confused by .NET architecture in general.  How do I know which DLL I should be using?

**Comment by RevenantX** [comment]
@pha3z 
> Should I be doing something more than just sticking the LiteNetLib dll into my project as a reference?

No. NetDataWriter in DLL.

> Also, I'm having trouble figuring out what the difference is between the three DLLS

https://msdn.microsoft.com/en-us/magazine/mt842506.aspx
Or just use google to know differences.

**Comment by pha3z** [comment]
Thank you. After you said it's in the dll, that made me realize that I have to specific sub-namespaces:

I only had: `using LiteNetLib;` at the beginning of my file.
I added this to fix the problem: `using LiteNetLib.Utils;`

C# newbie error. :)

I read the microsoft link.  Thank you so much. :)
