### ISSUE TITLE
Suggestion: Main doc should suggest using INetEventListener?

### ISSUE THREAD

**Issue by pha3z** [RevenantX/LiteNetLib#166]
Sorry, trying not to be spammy.  I try to ask things other people would also want to know. :)

If I understand all the examples correctly...

It looks like the GitHub sample may not be the fastest "up and running" way to use LiteNet.  I see you've implemented a very handy INetEventListener so you don't have to register functions custom.

Might it be better to add an example of using the INetEventListener on the homepage and suggest most users go that route?

**Comment by RevenantX** [comment]
@pha3z any developer can use `EventBasedNetListener` or `INetEventListener` if he wants. There all samples in LibSamble use - `INetEventListener`. If i show `INetEventListener` example at main page it will be very long
