### ISSUE TITLE
SendNextPackets  endless loop

### ISSUE THREAD

**Issue by ren-bimviz** [RevenantX/LiteNetLib#167]
```csharp  
int relate = NetUtils.RelativeSequenceNumber(_localSeqence, _localWindowStart);
```
**relate  = 64** 

```csharp
                if (relate < _windowSize)
                {
                    PendingPacket pendingPacket = _pendingPackets[_localSeqence % _windowSize];
                    pendingPacket.Packet = _outgoingPackets.Dequeue();
                    pendingPacket.Packet.Sequence = (ushort)_localSeqence;
                    pendingPacket.Next = _headPendingPacket;
                    _headPendingPacket = pendingPacket;
                    _localSeqence = (_localSeqence + 1) % NetConstants.MaxSequence;
                }
                else //Queue filled
                {
                    break;
                }
```

Will be forever  **break** .  And will be send nothing

**Comment by RevenantX** [comment]
@ren-bimviz this is not send method. This is method for adding pending packet. And _localWindowStart moving when acks received.

**Comment by ren-bimviz** [comment]
but there be a bug.
I encounter can not send anything message,
because can not adding a pending packet

**Comment by RevenantX** [comment]
@ren-bimviz there is no bugs. Check benchmarks and look how 1000 and more reliable packets arriving.

**Comment by ren-bimviz** [comment]
@RevenantX 
are you sure?
I can reappear

> if (relate < _windowSize)
 relate = 64 and _windowSize = 64
and goto else and 

>   break //Queue filled

**Comment by RevenantX** [comment]
@ren-bimviz i am sure. This is TCP like "window" technique.
relate will be lower after packets acked - because  _localWindowStart increasing after acks.
```csharp
public void ProcessAck(NetPacket packet)
{
...
    if (seq == _localWindowStart)
    {
        //Move window                
        _localWindowStart = (_localWindowStart + _ackedPackets) % NetConstants.MaxSequence;
        _ackedPackets = 1;
    }
...
}
```

**Comment by ren-bimviz** [comment]
@RevenantX 
thanks , I know you say.
there has some bugs in my app.
thanks for your reply!
