### ISSUE TITLE
Multiple Connections

### ISSUE THREAD

**Issue by NVentimiglia** [RevenantX/LiteNetLib#17]
I am writing a benchmark / stress tester. I'm currently running into an issue that I can not connect more than two clients at a time. My test is based off of the Echo test.

https://gist.github.com/NVentimiglia/0cec23e985c12d0166043c44585bacdd

That said, here are my initial results with two clients

> [0] CON 2 MSG 1896 TIME 15.0026217 OPS 126.377911668599 LAG NA ERR 0
[0] CON 2 MSG 1894 TIME 15.0036247 OPS 126.236162118878 LAG 15 ERR 0
[0] CON 2 MSG 3805 TIME 30.0080228 OPS 126.799423786095 LAG NA ERR 0
[0] CON 2 MSG 3805 TIME 30.0080228 OPS 126.799423786095 LAG 15 ERR 0

**Comment by NVentimiglia** [comment]
search for "private int _clientCount = 3;"

**Comment by RevenantX** [comment]
Look at second argument of your NetServer - this is max clients.
https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/NetServer.cs#L20

**Comment by RevenantX** [comment]
And if you want very high performance - use "server.UnsyncedEvents = true" and "client.UnsyncedEvents = true". But this requires make your code thread safe, because it will don't sync incoming queues.

**Comment by NVentimiglia** [comment]
That was it, thanks

**Comment by NVentimiglia** [comment]
Will update my tests and repost with some results.

**Comment by RevenantX** [comment]
Or without UnsyncedEvents - send messages not in Receive method (because it called when you use Poll). Send them from another thread for correct test.

**Comment by NVentimiglia** [comment]
Reoppening, as I am still having issues related to many connections.

**5 Connections**

> [0] CON 5 MSG 4597 TIME 15.0013546 OPS 306.438993182656 LAG NA ERR 0
[0] CON 5 MSG 4597 TIME 15.0023566 OPS 306.418526273399 LAG 16 ERR 0
[0] CON 5 MSG 9271 TIME 30.004077 OPS 308.991341410036 LAG NA ERR 0
[0] CON 5 MSG 9269 TIME 30.004077 OPS 308.924683802138 LAG 16 ERR 0
[0] CON 5 MSG 13799 TIME 45.0070481 OPS 306.596423949875 LAG NA ERR 0
[0] CON 5 MSG 13795 TIME 45.0070481 OPS 306.507548980978 LAG 16 ERR 0


**10 Connections**

> Synced time test: 1/10/2017 2:46:27 PM
[Server] Peer connected: 127.0.0.1:50567
[Server] Peer connected: 127.0.0.1:50568
[Server] Peer connected: 127.0.0.1:50569
[Server] Peer connected: 127.0.0.1:50570
[Server] Peer connected: 127.0.0.1:50571
[Server] Peer connected: 127.0.0.1:50572
[Server] Peer connected: 127.0.0.1:50573
[Server] Peer connected: 127.0.0.1:50574
[Server] Peer connected: 127.0.0.1:50575
[Server] Peer connected: 127.0.0.1:50576
Waiting:: Errors 0 Peers 10
Ready. Press any key to start
Starting
[Server] Peer disconnected: 127.0.0.1:50574, reason: Timeout
[0] CON 9 MSG 2656 TIME 25.5172401 OPS 104.086491704877 LAG NA ERR 0
[0] CON 10 MSG 2646 TIME 25.5187418 OPS 103.688497682907 LAG 96 ERR 0
[Server] Peer disconnected: 127.0.0.1:50567, reason: Timeout
[Server] Peer disconnected: 127.0.0.1:50568, reason: Timeout
[Server] Peer disconnected: 127.0.0.1:50569, reason: Timeout
[Server] Peer disconnected: 127.0.0.1:50570, reason: Timeout
[Server] Peer disconnected: 127.0.0.1:50571, reason: Timeout
[Server] Peer disconnected: 127.0.0.1:50572, reason: Timeout
[Server] Peer disconnected: 127.0.0.1:50573, reason: Timeout
[Server] Peer disconnected: 127.0.0.1:50575, reason: Timeout
[Server] Peer disconnected: 127.0.0.1:50576, reason: Timeout

I did update the code as you suggested 
https://gist.github.com/NVentimiglia/0cec23e985c12d0166043c44585bacdd

**Comment by RevenantX** [comment]
When using UnsyncedEvents - you don't need to call PollEvents. You can remove threads code that just using 100% cpu.
But i don't recommend use UnsyncedEvents. Better send messagess from another thread as i said before.

**Comment by RevenantX** [comment]
Corrected code for UnsyncedEvents https://gist.github.com/RevenantX/f212abd189a6f281a330c68aa6f828a6

**Comment by RevenantX** [comment]
If you reduce UpdateTime of Client and Server to 1 msec - you will get better results. Echo stress test depends on UpdateTime, because Library doing internal reliability logic with this ticks. But if you will send messagess from another thread both from client and server - you will get real power :)

**Comment by NVentimiglia** [comment]
**Without sending for another thread.**

> [0] CON 10 MSG 50145 TIME 15.004567 OPS 3341.98247773495 LAG NA ERR 0
[0] CON 10 MSG 50145 TIME 15.0055579 OPS 3341.76178814385 LAG 2 ERR 0
[0] CON 10 MSG 101071 TIME 30.0090667 OPS 3368.01544048019 LAG NA ERR 0
[0] CON 10 MSG 101062 TIME 30.0090667 OPS 3367.7155311198 LAG 2 ERR 0

This is about equal to my TCP DotNetCore solution, though that does include a more robust routing (RPC) and serialization layer as well. We might be able to do better.

The updateTime of 1ms smells to me. What is this doing? Is this some sort of 'return to main thread' logic ?

I think we might need to think about how we want to handle threading in the future as it looks like a pretty easy gotcha to bottleneck on. Would you recommend manually queing the message on the main thread with the actual sending being invoked on a background thread (I ask because I did see a que internally, not sure what it is doing)

**Comment by NVentimiglia** [comment]
> [0] CON 100 MSG 64044 TIME 15.0125366 OPS 4266.03456207394 LAG NA ERR 0
[0] CON 100 MSG 63962 TIME 15.0145386 OPS 4260.00436670095 LAG 23 ERR 0
[0] CON 100 MSG 129043 TIME 30.0218531 OPS 4298.30229233918 LAG NA ERR 0
[0] CON 100 MSG 128962 TIME 30.0218531 OPS 4295.60425768655 LAG 23 ERR 0


> [0] CON 200 MSG 33453 TIME 15.0166789 OPS 2227.72293546211 LAG NA ERR 0
[0] CON 200 MSG 33261 TIME 15.0176778 OPS 2214.78982589439 LAG 90 ERR 0
[0] CON 200 MSG 69212 TIME 30.0229568 OPS 2305.30258765186 LAG NA ERR 0
[0] CON 200 MSG 69025 TIME 30.0299357 OPS 2298.53972014998 LAG 87 ERR 0

Anymore and I run out of memory on my local box.

**Comment by RevenantX** [comment]
Sending packets needs some logic, that ticks every **UpdateTime** (msec) (because of flow control). In version 0.6.1 if you send **Unreliable** packets they will be send immediately without waiting. If you send every echo 1000 packets instead of 1 - send logic will send all 1000 packets (if flow control not setuped).

Main sense of library - is that you can send Unreliable packets (for Player positions as example)

**Comment by NVentimiglia** [comment]
Gotcha, Good stuff.
