### ISSUE TITLE
Why Doc says use Source instead of DLL for Unity?  But example Unity Sample uses DLL?

### ISSUE THREAD

**Issue by pha3z** [RevenantX/LiteNetLib#170]
The main document says always use source for Unity, never precompiled DLLs.

But the Sample Unity project shows the dll being included.  Also I see on other issue, you've instructed others to also use DLL.

So why does the doc say don't use DLL with Unity?

**Comment by RevenantX** [comment]
For unity3d logger and fixes for some mobile platforms in NetSocket.cs code.

**Comment by RevenantX** [comment]
If you develop your game/application only for standalone platforms you can use DLL.

> But the Sample Unity project shows the dll being included.

I don't want copy litenetlib code twice in repository)
