### ISSUE TITLE
Suggestion: Add IHandler Interface on NetPeer

### ISSUE THREAD

**Issue by pha3z** [RevenantX/LiteNetLib#171]
If there is a better way to do this, please let me know.  Otherwise, I have a suggestion to improve library.

Presently, I am instancing a custom Connection object for each Peer connection to my server.

I implemented INetEventListener and used a static dictionary of connected peers -- indexed by ConnectId.  When a packet arrives, my code looks into the ConnectedPeers dictionary to find out which Connection Object I need to call to handle the packet.

Existing code looks like this:
```
public static class NetServer
{
	private static Dictionary<long, ConnectionManager> Connections = new Dictionary<long, ConnectionManager>();

    public class ServerListener : INetEventListener
    {
        public NetManager Server;

        public void OnPeerConnected(NetPeer peer)
        {
            try
            {
                Connections.Add(peer.ConnectId, new ConnectionManager();
            }
            catch {   log.Write("ERROR");     }
        }

        public void OnNetworkReceive(NetPeer peer, NetDataReader reader, DeliveryMethod deliveryMethod)
        {
            ConnectionManager ThisConn;
            Connections.TryGetValue(peer.ConnectId, out ThisConn);
            ThisConn.HandleInboundPacket(reader.Data);
        }

    }

}
```

This solution works well except for one problem -- I am doing an _unnecessary_ dictionary look up for every single packet received.  My suggestion is this:

You could add an IHandler Interface to Peer class.  It might start with only one function:  HandlePacket(), but you could certainly add more methods.

Then consumer of your library could do this:

```
public class myConnectionHander : IHandler
{
    public void HandlePacket(byte[] Pkt)
    {
        //Do something with the packet here.
    }
}

public class ServerListener : INetEventListener
{
    public void OnPeerConnected(NetPeer peer)
    {
        peer.Handler = new myConnectionHandler();
    }

    public void OnNetworkReceive(NetPeer peer, NetDataReader reader, DeliveryMethod deliveryMethod)
    {
        peer.Handler.HandlePacket(reader.Data);
    }

}
```

**It would completely eliminate the need for consumer to maintain a list that maps Handlers to Peers, which would also increase performance by eliminating a custom container look-up for every single packet.**

If I'm using the library incorrectly, please tell me.  I just don't see how to get around the need for a container look-up right now.

**Comment by NVentimiglia** [comment]
I stopped reading at the word static dictionary. Using static is an anti pattern that should be avoided at all costs. This breaks the scalability and the extensibility of the application. Specifically, think about test scenarios where you may need to open up several Network instances within the same process.

We should not break or clean design for a feature that adds no new functionality

**Comment by pha3z** [comment]
Yeah.  I don't want to use a dictionary.  That's the point.  I'm asking how to map incoming Peer packets to a customer handler without using my own look up container.  Is there already a way to do this in the library?   I want to avoid a custom connection list entirely.

**Comment by RevenantX** [comment]
@pha3z that is good idea. I will investigate your proposal.

**Comment by RevenantX** [comment]
@pha3z but you can use NetPeer tag object to store anything you want.

**Comment by pha3z** [comment]
So using Tag, I would do the following like this?

```
public class ServerListener : INetEventListener
{
    public void OnPeerConnected(NetPeer peer)
    {
        peer.Tag= new myConnectionHandler();
    }

    public void OnNetworkReceive(NetPeer peer, NetDataReader reader, DeliveryMethod deliveryMethod)
    {
        myConnectionHandler Handle = peer.Tag as myConnectionHandler;
	Handle.HandlePacket(reader.Data);
    }
}
```

I guess that works, but it requires use of "as" keyword.   Am I correct?

**Comment by RevenantX** [comment]
@pha3z 
>So using Tag, I would do the following like this?

Yes

>I guess that works, but it requires use of "as" keyword. Am I correct?

Faster will be simple cast
```csharp
    public void OnNetworkReceive(NetPeer peer, NetDataReader reader, DeliveryMethod deliveryMethod)
    {
        myConnectionHandler Handle = (myConnectionHandler)peer.Tag;
	Handle.HandlePacket(reader.Data);
    }
```

**Comment by pha3z** [comment]
Well this is certainly a lot faster than a container look-up.  Thank you! :)

I still think a Handler Interface would be really nice, though. :)  Best performance... plus intuitive for demonstrating how to use library.
