### ISSUE TITLE
How to work whith DeliveryMethod.ReliableOrdered...

### ISSUE THREAD

**Issue by qq1054599715** [RevenantX/LiteNetLib#172]
Information about  feature
i let Client use DeliveryMethod.ReliableOrdered   sending message type
and  let Server set SimulatePacketLoss = true   and the  lossChance = 20 
when Client send many  messages to the Server,The Server stoped work, i am saidly.
pray for that  you  tell me how to resolve this problem... 

**Library version**: [0.7.7.1]

**Framework**: [Unity]

**OS**: [ Windows]

**Comment by qq1054599715** [comment]
thank big god. 
i download the released code instead of cod on github.  very thank big god.

i find #define UNITY  does not work in unity2017.3 ,but  #define UNITY || UNITY_2017  worked,

**Comment by RevenantX** [comment]
#define unity works if you add it to defines......
![img](https://docs.unity3d.com/uploads/Main/ScriptDefines.png)
