### ISSUE TITLE
[Question] Multithreading

### ISSUE THREAD

**Issue by SynergiAios** [RevenantX/LiteNetLib#176]
I was tinkering around with the new Unity Job System and ECS and was thinking about merging my network implementation of your framework too into multithreading. So I was checking your source code to see if there are any threading issues to occur. You are really a genius and already designed it thread safe. So you have in the NetPeer class the send method with a lock on a _sendLock object and in this send method you add the packets into the different queues to be send. 

My question is, as I'm currently not totally aware of your source code, do you think, there is a given difference in making my calls to the NetPeer.Send async as it basically would mean there can be many threads that await the release of the lock of the previous call. So basically they would all still turn synchron. 

Is there any scenario you designed your framework threadsafe you could think of? I mean I think you did this for a given reason, so I was asking myself what is this reason? Or were you just really carefully on implementing this framework and already thought of what would happen if a user tries to use your framework in a multithreaded case?

**Comment by RevenantX** [comment]
@SynergiAios my library already multithreaded. It internally starts 3 threads (2 if there is no IPv6). 2 for receiving packets and 1 for send and internal logic.

> difference in making my calls to the NetPeer.Send async

There is no sense to do this.

**Comment by SynergiAios** [comment]
Thx for declaring this.

**Comment by vanhaodev** [comment]
> @SynergiAios my library already multithreaded. It internally starts 3 threads (2 if there is no IPv6). 2 for receiving packets and 1 for send and internal logic.
> 
> > difference in making my calls to the NetPeer.Send async
> 
> There is no sense to do this.


**I see each connector (netpeer) is a separate stream, does LiteNetLib have this set up already? Do I need to handle context switches?**
