### ISSUE TITLE
Endless Loop in ReliableChannel

### ISSUE THREAD

**Issue by Dmetriy** [RevenantX/LiteNetLib#177]
Hi!

Detected appearance of infinite loop in ReliableChannel.SendNextPackets last do while.

Library version 0.7.7.1. Ping between client and server about 170.
The minimal example in which we managed to reproduce issue: https://github.com/Dmetriy/LiteNetLibTest

Assume that error arises from receipt of old acknowledgments right after reconnect.

**Comment by RevenantX** [comment]
Found possible problem. I will try fix today.

**Comment by RevenantX** [comment]
@Dmetriy fixed in master (0.8.x) but need tests. (there can be some instability at all)
