### ISSUE TITLE
Socket.ReceiveFrom isn't supported on Linux and macOS

### ISSUE THREAD

**Issue by Krakean** [RevenantX/LiteNetLib#178]
@RevenantX 
Hello.
Version: latest master.

This line in NetSocket.cs#176:
result = socket.ReceiveFrom(receiveBuffer, 0, receiveBuffer.Length, SocketFlags.None, ref bufferEndPoint);

Reported just in case if LiteNetLib supposed to be cross-platform.

**Comment by RevenantX** [comment]
@Krakean checked latest version (using mono) on Debian 9. All works.

**Comment by RevenantX** [comment]
@Krakean checked .net core 2.0. All compiles fine.

**Comment by Krakean** [comment]
@RevenantX 
Hm, my bad then. This notice was given by using https://github.com/dotnet/platform-compat

**Comment by RevenantX** [comment]
@Krakean this is look like false positive. Look at issues at this repo.
