### ISSUE TITLE
When Virtual Ethernet Adapter and WIFI Adapter Enable peer.EndPoint alway get vritual adapter ip

### ISSUE THREAD

**Issue by fingerx** [RevenantX/LiteNetLib#179]
[Bug]

When Virtual Ethernet Adapter enable and WIFI Adapter enable peer.EndPoint alway get vritual adapter ip.Only WIFI Adapter enable peer.EndPoint get ip is ok.

**Library version**: [0.7.7.1]

**Framework**: [Unity]

**OS**: [Windows10]

**Comment by RevenantX** [comment]
@fingerx and why this is bug? If you get this behavior on localhost - then all ok.

**Comment by fingerx** [comment]
@RevenantX  thanks
