### ISSUE TITLE
NetSerializer serialize the large string get empty

### ISSUE THREAD

**Issue by qq1054599715** [RevenantX/LiteNetLib#180]
when data is smaller ，run ok，then data get bigger，NetSerializer serialize empty on  [string] Type filed
the data server Send:
33910517596142225171120008310197114991048210111511710811663500913451344434921175755515692117555156669211757705757344434504849564748524749554550494748524750513444345048495647485247495545504947485247505534443492117575551569211755515666921175770575734443450484956474852474955455049474852475157344434504849564748524749554550494748524752523444349211757555156921175551566692117577057573444345048495647485247495545505047485247535434443450484956474852474955455050474852475357344434921175756686992117577057573444345048495647485247495645494947525447505134443450484956474852474956454949475254475249344434921175756686992117577057573444345048495647485247495645494947525447535734443450484956474852474956454949475256475056344434921175756686992117577057573444345048495647485247495645494947535147515734443450484956474852474956454949475351475351344434921175756686992117577057573444345048495647485247495645494947535247485234443450484956474852474956454949475352474955344434921175756686992117577057573444345048495647485247495645494947535247505134443450484956474852474956454949475352475256344434921175756686992117577057573444345048495647485247495645494947535247534934443450484956474852474956454949475353474851344434921175756686992117577057573444345048495647485247495645494947535347485234443450484956474852474956454949475353475053344434921175756686992117577057573444345048495647485247495645494947535347515234443450484956474852474956454949475354474948344434921175756686992117577057573444345048495647485247495645495047514947495434443450484956474852474956454950475149475152344434681011091113444345048495647485247495645504947525147525234443450484956474852474956455049475251475255344434681011091113444345048495647485247495645504947525147525534443450484956474852474956455049475251475349344434681011091113444345048495647485247495645504947525147534934443450484956474852474956455049475252474850344434681011091113444345048495647485247495645504947525247485034443450484956474852474956455049475252474853344434681011091113444345048495647485247495645504947525247485334443450484956474852474956455049475252474856344434681011091113444345048495647485247495645504947525247485634443450484956474852470000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

the dataType is 
public class A{
    public string command { get; set; }
    public string content { get; set; }
}
the [content] filed get empty

**Comment by RevenantX** [comment]
@qq1054599715 yes, there is limit to 1000 symbols. I will add limit change.

**Comment by qq1054599715** [comment]
thanks for big god's answer!

**Comment by qq1054599715** [comment]
thanks for big god's answer!

**Comment by RevenantX** [comment]
@qq1054599715 what version of library are you using?

**Comment by qq1054599715** [comment]
0.7.7.1

**Comment by Krakean** [comment]
@RevenantX 
I suppose you implemented it in recent commit?
May be this ticket can be closed :)

**Comment by RevenantX** [comment]
@Krakean i think he need this in stable branch...

**Comment by RevenantX** [comment]
@qq1054599715 
Added max string length to constructor. So you can change value. In 0.7 branch on github.
