### ISSUE TITLE
Need IPAddres.Any change to my bind IP!

### ISSUE THREAD

**Issue by iamryuzaki** [RevenantX/LiteNetLib#182]
NetSocket.Bind(port, reuseAddress) - 
Need to this.BindSocket - write IPAddres.Any for my IP Addres... My server machine have big count ip addres http://prntscr.com/j8qozh

**Comment by RevenantX** [comment]
@iamryuzaki в 0.8 по-другому реализовано подключение. И есть возможность старых "ключей"
server:
```csharp
       listener.ConnectionRequestEvent += request =>
       {
                request.AcceptIfKey("SomeConnectionKey");
       };
```

client:
```csharp
 client.Connect("localhost" /* host ip or name */, 9050 /* port */, "SomeConnectionKey" /* text key or NetDataWriter */);
```

**Comment by iamryuzaki** [comment]
@RevenantX Благодарю вас, вы очень помогли. Я работаю в партнерстве мелких проектов, а также сам GameDev разработчик. И ваша работа крайне важна!  Я буду и сам пользоватся вашим продуктом, и своих партнеров и коллег просвещать о вашм решении. Благодарю вас!
