### ISSUE TITLE
[Question] Mass assigning SubscribeReuseable

### ISSUE THREAD

**Issue by xSINIQx** [RevenantX/LiteNetLib#187]
Hey there, i was wondering if its possible to mass assign SubcribeReusable?
I've got a long list of SubscribeReuseables at the top of my class now, and it doesn't feel like the right way to do this.
quick example as i'm at work and dont have my code at hand:
`_packetProc.SubscribeReusable<Packet1, NetPeer>(PacketHandlers.PacketOneHandler);
_packetProc.SubscribeReusable<Packet2, NetPeer>(PacketHandlers.PacketTwoHandler);
`
... and so on...
Any pointers?
Thanks in advance.

**Comment by RevenantX** [comment]
@xSINIQx hi!
> Hey there, i was wondering if its possible to mass assign SubcribeReusable?

no. But you can call template method(**SubscribeReusable**) by reflection in loop for all your packet classes. But this thing possibly will not work on iOS.

**Comment by xSINIQx** [comment]
Thanks, i think i'll look into a different way, i stumbled upon another problem which would require me to make an extra lookup or store the methods in the packet classes, and that seems pretty inefficient to me. i came across #171 and thought of making my own packet processor instead.

**Comment by RevenantX** [comment]
@xSINIQx packet processor and serializer - are separate classes in LiteNetLib so you can easily build your own packet processor over NetSerializer) Or use any protobuf/flatbuffers etc.)
