### ISSUE TITLE
How to create a time synced event?

### ISSUE THREAD

**Issue by Saishy** [RevenantX/LiteNetLib#188]
So let's say I'm making a game, and I know in 2.7s something will happen.
Instead of waiting 2.7s in the sever and sending the event to clients, is there a way I can send the info that it will happen 2.7s from now and somehow get the time synced?

I am not sure how to find out what is the difference in time between host and clients.

Thanks in advance.

**Comment by unwild** [comment]
Hello, 

This issue has nothing to do with the lib, it's only custom code.

After the connection, synchronize client clock with server clock with custom code, 
 (you can find examples easily), then just pass the timestamp of the event from the server to the client, pool it somewhere and check your events pool to fire events.

**Comment by Saishy** [comment]
I thought it had something to do with the Time features of the lib.

**Comment by unwild** [comment]
Haven't noticed the NTP requests features, sorry. Deleting my comment.

**Comment by RevenantX** [comment]
@Saishy if you need this logic - better will be use ticks. In almost all multiplayer games - logic update rate is locked to some value. So you can store game current tick number.
If you have logic update rate - 15 milliseconds. So sequence 4 will equal 60 milliseconds.

**Comment by Saishy** [comment]
@RevenantX Ah, I guess I will have to implement the rotating buffer then.

Thank you.
