### ISSUE TITLE
Can this be used to allow a host to listen on multiple ports at the same time?

### ISSUE THREAD

**Issue by MostHated** [RevenantX/LiteNetLib#191]
Hey there,
    I am trying to find a network library for Unity3d that will let my server listen on multiple ports. Is this capable of doing that?

Thanks,

**Comment by RevenantX** [comment]
@MostHated hi! You can start several NetworkManagers on different ports and bind them to one listener.

**Comment by RevenantX** [comment]
@MostHated 
>Also, in the "GithubSample.cs", the Client() and Server() method names look like they were accidentally swapped.

Oops) This is my mistake.

**Comment by MostHated** [comment]
No worries, lol. I had another question. I currently have everything already setup to serialize my custom types using MessagePack with Lz4 compression to byte[], is it possible to just use what I already have and send that over instead of having to try to convert everything I have setup already? Some of it is dictionaries, object's etc which I don't think are supported anyways.

**Comment by RevenantX** [comment]
@MostHated you can always just send byte[] array. I don't fully understand what you mean)

**Comment by MostHated** [comment]
Yeah, its fine, I got it, no worries.

**Comment by RevenantX** [comment]
@MostHated ok) Closing.
