### ISSUE TITLE
Discovery Multicast?

### ISSUE THREAD

**Issue by edcwhite** [RevenantX/LiteNetLib#192]
The README indicates that Multicasting for discovery is available however I don't see anywhere in the code where this can be configured for IPv4?    I have had to download and change the source to support this.  Am I missing something?

Thanks!

**Comment by RevenantX** [comment]
@edcwhite for IPv4 - broadcast is used instead of multicast for discovery (because of bugs in unity/IL2CPP and some mobile platforms)
