### ISSUE TITLE
Thread.Sleep design descision

### ISSUE THREAD

**Issue by marsermd** [RevenantX/LiteNetLib#193]
Steps to reproduce:
1) Set update time to a low value (i.e. 1 ms)
2) Write a game that's high on the processor and (utilize multiple cores for better reproduction)
3) Run on an ios device (i.e. IPad Air 2)
4) Observe a huge packet loss for a period of ~1 second that happens from time to time.

So why is it happening?

In **NetThread** there is an assumption that `Thread.Sleep(ms)` will sleep for an approximately given amount of time.

But actually `Thread.Sleep` just commands the OS to **not to schedule** this thread for execution for the given amount of time. And the time for the thread to be scheduled back is arbitrary although it is usually close to the requested time.

**Comment by RevenantX** [comment]
@marsermd logic thread with sleep used only for sending packets. Receiving logic works independently. So this is strange. And with higher values (for example 15 ms) there is no such lags?

**Comment by marsermd** [comment]
@RevenantX sorry for rushing with posting this :)
I am preparing a more in-depth report for you.

And yes, the problem seems to be related exactly to the sending of the packets.

**Comment by marsermd** [comment]
I think that my initial guess was wrong and there is something else happening.
Despite that I'd like to point out that using `Thread.Sleep(n)` and relying on it to continue the thread after ~n ms is quite a bad idea.

> Thread.Sleep(n) means block the current thread for at least the number of timeslices (or thread quantums) that can occur within n milliseconds.  The length of a timeslice is different on different versions/types of Windows and different processors and generally **ranges from 15 to 30 milliseconds**.  This means the thread is **almost** guaranteed to block for more than n milliseconds.  

[Source](https://blogs.msmvps.com/peterritchie/2007/04/26/thread-sleep-is-a-sign-of-a-poorly-designed-program/)

P.S. still digging into the problem, I'll keep you posted.

**Comment by RevenantX** [comment]
@marsermd and what alternatives there are in C# to Thread.Sleep? (.NET 3.5)

**Comment by marsermd** [comment]
LiteNetLib 0.7.7.1
In Unity (from source code)

**Comment by RevenantX** [comment]
@marsermd spin wait will eat 100% cpu

**Comment by NVentimiglia** [comment]
@RevenantX (Insert Heavy Metal Album Here)

**Comment by NVentimiglia** [comment]
@RevenantX Yeah, maybe the jobs system could be an option.

**Comment by RevenantX** [comment]
@NVentimiglia there are only two options Thread.Sleep and System.Timers.Timer.

**Comment by RevenantX** [comment]
@Eideren 
>Also sleeping based on the amount of time remaining to the next tick might be better than sleeping a tick to keep a more consistent delta time between ticks

This how it works for now.

>How about using Monitor.Wait and Pulse()

This thread (logic thread) must resend packets after some amount of time to maintain reliability. 
And for disconnect timeouts and some other things.

**Comment by Eideren** [comment]
@RevenantX Yeah, the overloaded function with the object and int parameters allows you to wait a specified amount of time like Thread.Sleep while still allowing other threads to force it to wake up through pulsing the lock object.

System.Timers.Timer uses System.Threading.Timer internally which is not as precise as your Thread.Sleep, I don't know for sure whether it's more reliable than Thread.Sleep when the system is busy but I highly doubt it.

**Comment by RevenantX** [comment]
@Eideren i know about Monitor.Pulse and Monitor.Wait. But for almost all situations thread sleep is enough. I think this problem caused by wifi or some other thing.

**Comment by Eideren** [comment]
@RevenantX I entirely agree, 'just trying to help you out in case where it ended up being related to thread scheduling.

**Comment by marsermd** [comment]
**Regarding the initial issue**

Turned out we have a faulty WIFI. And at the rate of ~100 packets/second of size ~256 bytes it suddenly starts queuing them up and introduces this huge lag.

Probably a good read up for me and for others interested in this stuff is [bufferbloat.net](https://www.bufferbloat.net/projects/bloat/wiki/Experiment-Fun_with_wireless/)

**Regarding the design descision**

Overall I'd say that Thread.Sleep(ms) is a good solution for 
> resend packets after some amount of time to maintain reliability. And for disconnect timeouts...

But as I previously said, the time that was spent in that `Thread.Sleep(n)` should be calculated via [Stopwatch](https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.aspx) rather than relying on `n` itself.

And I'd suggest everyone to whom latency is crucial, calling `NetManager.Flush()` every time they'd like to ensure that all the packets are immediately sent. As long as I understand, it immediately sends all unsent packets.

It would be nice to document `NetManager.Flush()` and more precisely describe the effect of `UpdateTime`. And also add `Flush` to the example.

@RevenantX if you agree on that, I'd like to do that. 
If you have any thoughts on how to do it better, I'd be happy to help you with that as well.

**Comment by RevenantX** [comment]
@marsermd 
> But as I previously said, the time that was spent in that Thread.Sleep(n) should be calculated via Stopwatch rather than relying on n itself.

DateTime.Ticks have enough precision. So i can just modify update loop to use already existing DateTime and pass difference to **Update** delta time.

**Comment by marsermd** [comment]
@RevenantX 
The problem here is that DateTime.Now.Ticks is not as high res as you'd expect.
Yes, incrementing DateTime.Ticks by 1 means incrementing by 1e-4 of a millisecond.

But DateTime.Now is updated rarely. At my win7 pc it is updated once every 1 ms. On different operating systems this rate is different.
That's why the [docs](https://msdn.microsoft.com/en-us/library/system.datetime.now(v=vs.90).aspx) recommend using Stopwatch for time sensitive stuff.

**Comment by RevenantX** [comment]
@marsermd added stopwatch elapsed to peer.Update( delta time ) in master.
