### ISSUE TITLE
[sample] .Subscribe usage sample

### ISSUE THREAD

**Issue by StoicaNicusor** [RevenantX/LiteNetLib#194]
Just found out I can't use SubscribeReusable for all my classes, but how can I use .Subscribe with packet constructor instead ? Can you please provide a sample usage ? Thanks in advance.

**Comment by RevenantX** [comment]
```csharp
_netPacketProcessor.Subscribe<MyPacketClass, NetPeer>(SomeReceiveMethod, () => { return new MyPacketClass(...); });
```
