### ISSUE TITLE
Random examples all messy ??

### ISSUE THREAD

**Issue by devingDev** [RevenantX/LiteNetLib#195]
I downloaded the latest source instead of using Nuget now its totally different.
The LibSample ones for example dont match what you have in your README
THe LibSample ones worked with Nuget one i think and the one in readme worked when I copied the LiteNetLib folder into Unity/VS Project .

**Comment by devingDev** [comment]
I already have the latest available from relase page 0.7.7.1. Used the source for Unity as written in readme.
It seems to built a connection as server accepts the peer and attempts to send a message but the client in unity never receives that message. I used the example provided in Readme and have Unity 2018.1.3f1

**Comment by devingDev** [comment]
Well the example in the Readme in the 0.7 branch does not match 0.7.7.1 for example : 
NetManager client = new NetManager(listener, "SomeConnectionKey"); already throws an error as it expects an INetEventListener and no connection Key...

**Comment by RevenantX** [comment]
@devingDev are you sure that you using 0.7.7.1 both on server and client?

**Comment by RevenantX** [comment]
@devingDev https://github.com/RevenantX/LiteNetLib/blob/0.7/LiteNetLib/NetManager.cs#L200

**Comment by devingDev** [comment]
Oh sorry I added the latest source "Download as zip" which was from the master branch. Now it matches the sample at least. Thanks
