### ISSUE TITLE
Is there any plan to release 0.7.7.2?

### ISSUE THREAD

**Issue by wuyuntao** [RevenantX/LiteNetLib#196]
We've encountered a problem that NetManager.Stop blocks when called in a .net core app with a docker container which is similar to issue #190 and is fixed in later commits after 0.7.7.1.

So is there any plan to release 0.7.7.2 to cover these bug fixes?

**Comment by RevenantX** [comment]
@wuyuntao yes. I will upload new version today.

**Comment by RevenantX** [comment]
@wuyuntao uploaded: https://www.nuget.org/packages/LiteNetLib/0.7.7.2
