### ISSUE TITLE
Null Exception in ConnectionNum

### ISSUE THREAD

**Issue by wormszer** [RevenantX/LiteNetLib#197]
I am seeing a crash happen when i am connecting with a  client to the server.
I have latest from master 9338f33.

The commit from 8fc2ed0 "Add Reason to Reject #159 (and some fixes)" added this code

```csharp
        internal byte ConnectionNum
        {
            get { return _connectNum; }
            private set
            {
                _connectNum = value;
                _mergeData.ConnectionNumber = value;
            }
        }
```

_mergeData is null because  the NetPeer is being constructed with this constructor
        internal NetPeer(NetManager netManager, IPEndPoint remoteEndPoint)

Which does not initialize it.

**Library version**: [commit id (9338f337556ae3e9adaf0fc2b8ef14d9e415f001)

**Framework**: [Unity]

**OS**: [Windows]

**Comment by RevenantX** [comment]
@wormszer thanks for bug report! Fixed)
