### ISSUE TITLE
Is there a low-overhead method to send a byte-array?

### ISSUE THREAD

**Issue by rikimaru0345** [RevenantX/LiteNetLib#201]
1) I want to use my own serializer.
Is there a way to send a custom byte[] buffer without the library creating any copies?

2) Also, I want to avoid garbage-collection-pressure as much as possible. Will the library create new buffers to receive data, or is there a way to .Recycle() incoming data like with other libraries?

3) Does this library automatically fragment messages that are too big for one low-level packet, and reassemble them on the receiving side automatically? If not, is that a planned feature?

**Comment by RevenantX** [comment]
@rikimaru0345 
>I want to use my own serializer.
Is there a way to send a custom byte[] buffer without the library creating any copies?

Lowest overhead method:
```csharp
public void Send(byte[] data, int start, int length, DeliveryMethod options)
```
But it will make one copy.

>Also, I want to avoid garbage-collection-pressure as much as possible. Will the library create new buffers to receive data, or is there a way to .Recycle() incoming data like with other libraries?

Data automatically will be recycled after OnReceive called. So if you want to save data you need to call ```GetBytes(...)``` from NetDataReader.

>Does this library automatically fragment messages that are too big for one low-level packet, and reassemble them on the receiving side automatically? If not, is that a planned feature?

There is information in readme:
>Automatic fragmentation of reliable packets

**Comment by NVentimiglia** [comment]
I also use my own FlatBuffer inspired serialization system. My serializer was written in a way that I could initialize with a null 'buffer' and set it at runtime.

When I read from LiteNet, I just set my buffer to the one passed by LiteNet, deserialize and queue my struct, and release the buffer same frame.

When I write, I pass my bytes I follow a similar pattern, but instead use a buffer I instantiate.

It has worked out really well.

**Comment by rikimaru0345** [comment]
Thanks for those answers! That is great to hear!
Looks like a great library so far :)
