### ISSUE TITLE
is it good for audio and video streaming? 

### ISSUE THREAD

**Issue by friuns2** [RevenantX/LiteNetLib#202]
Does LiteNetLib implement some similar techniques described here, like pacer, FEC and NACK?
https://habr.com/company/oleg-bunin/blog/413479/

**Comment by RevenantX** [comment]
@friuns2 LiteNetLib doesn't implement specaial features for audio and video streaming. But there is some project that used LiteNetLib for these purposes: https://github.com/boonkerz/teamscreen

**Comment by friuns2** [comment]
I think they not only for audio or video, but overall deal with ahead of line blocking. there is some c# code i found https://github.com/antiduh/ErrorCorrection 
Would be very usefull i think to have that in LiteNetLib

**Comment by RevenantX** [comment]
@friuns2 you can use it over LiteNetLib unreliable messages.
