### ISSUE TITLE
Feedback on invalid ConnectKey

### ISSUE THREAD

**Issue by Alloc86** [RevenantX/LiteNetLib#204]
Hi,

currently it looks like if a client tries to connect to a server with an invalid ConnectKey there's two things missing in my opinion:
1. An event on the server side so we can e.g. log the attempts
2. More importantly a feedback message to the client so the client can distinguish a ConnectionFailed event (for whatever other reason that might be) vs an invalid password. I need to be able to offer an option to retry with a new entered password by the user.

Could this be added (especially part 2)?

Regards,
Chris

**Comment by RevenantX** [comment]
@Alloc86 hi!
This features already exist in 0.8 version. It might be a bit unstable but i will fix bugs if you find some)
There is new `ConnectionRequestEvent` that you can use for this purposes. (you can implement any checks or use classic "key" check method)
```csharp
listener.ConnectionRequestEvent += request =>
{
    if(server.PeersCount < 10 /* max connections */)
        request.AcceptIfKey("SomeConnectionKey");
    else
        request.Reject();
};
```

**Comment by Alloc86** [comment]
Yeah, the "unstable" part is worrying me a bit ;)
But good to know this is coming. While it's not very nice in the current setup it definitely doesn't break using LiteNetLib.

Also, very great library, good job :)
Will probably have some more feedback later on.

**Comment by RevenantX** [comment]
>Also, very great library, good job :)

@Alloc86 Thanks)
