### ISSUE TITLE
Wrong port over Internet

### ISSUE THREAD

**Issue by Memorix101** [RevenantX/LiteNetLib#206]
Hey,

I have a question. Maybe someone can answer it because I actually don't understand why this happens and where the issue is.

When I connect to my server over the internet my client is listed with a wrong port.
The weird is this does occur on some other PCs too but on some not. Is it a router issue or something else I miss here? It doesn't happen on localhost, only over the Internet.

Thank you :)

![45645654](https://user-images.githubusercontent.com/1466920/43028025-aae6c1fe-8c7d-11e8-89e1-5fe4f5109fb8.PNG)

**Comment by MostHated** [comment]
The port you manually assign is for the incoming "listening port". That is the port on the server side that, from the outside, is always the same so you can find it. On the client side, it has to have a port as well, so when you initiate a connection, it automatically picks a random high number that is not being used (as they are less likely to be used) so that the client can communicate back and forth, as each side must have a port in which the data flows through.

**Comment by Memorix101** [comment]
My code:
```ruby
        private const int masterPort = 5395;
        private static string masterIp = "127.0.0.1";

        static void Main(string[] args)
        {
            //Client
            ClientListener _clientListener = new ClientListener();

            NetManager client1 = new NetManager(_clientListener)
            {
                //SimulateLatency = true,
                SimulationMaxLatency = 1500,
                UnconnectedMessagesEnabled = true,
            };

            _clientListener.client = client1;
            client1.Start();
            client1.Connect(masterIp, masterPort, _clientListener.gamekey);
            _clientListener.PrintPort();

            while (!Console.KeyAvailable)
            {
                client1.PollEvents();
                Thread.Sleep(15);
            }

            client1.Stop();
            Console.ReadKey();
        }

**Comment by MostHated** [comment]
Its connecting on the correct port, the client side has its own port for connecting out technically to the incoming port of 5395. They are different entities technically and both need their own port. So when it says LOG : YourClient : Port, that is the clients outgoing port, which then connects to YourServer : 5395.

**Comment by Memorix101** [comment]
Ah, and the server only list the ingoing on, right?
OK. That confused me somehow ^-^ I though it would use the same port for in and outgoing stuff.
