### ISSUE TITLE
NetManager.cs should have an "IncreaseMaxConnections()" method

### ISSUE THREAD

**Issue by Trithilon** [RevenantX/LiteNetLib#208]
Information about bug or feature
It will be tricky to implement a setMaxconnections because Netmanager then has to decide which connections to drop. But I don't see any harm in allowing more connections on demand.

**Library version**: [commit id (9f2a1d1a8244510d9ec502cc002bfdddba666d09) or release version (0.7.7.1)]

**Framework**: [Mono, Unity, dotnetcore, .NET Framework]

**OS**: [Linux, Windows, etc]

**Comment by RevenantX** [comment]
@Trithilon this already implemented in next version (0.8 master branch)
