### ISSUE TITLE
Is this library designed for things other than peer to peer?

### ISSUE THREAD

**Issue by bureto** [RevenantX/LiteNetLib#209]
I was previously using [this library](https://github.com/KillaMaaki/Unity-Netcode.IO) but I am looking for a replacement since it is very inactive and I was unable to troubleshoot it by myself. So I am curious if this library would be a good option for me. Is there a way to only allow the clients to have access to the server peer and not the other client's peers? So communication is strictly client-server-otherclients? Also is there ddos protection feature like inflating-client-server packets? I suppose I could add these features (or remove some in my case) myself (thank you for making this free and open-source) but just curious if there is fork already out there or something. Please let me know if these are dumb ideas as well since I am no expert. One more thing, does this support console? Thanks again.

**Comment by MostHated** [comment]
I believe the majority of the people who use this library use it for client / server architecture setups. That is how I have and am using it. It is especially great when used in conjunction with this.

https://github.com/insthync/LiteNetLibManager

**Comment by bureto** [comment]
Thank you @MostHated , that is great to hear! I'll probably give it a go then and see what happens.
