### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by jradesenv** [RevenantX/LiteNetLib#21]
Please, add install instructions in the Readme. 
I'm trying to figure out how to use it in Unity, but can't understand your sample ;x 
can you help me with?

**Comment by RevenantX** [comment]
Just copy LiteNetLib folder into unity. Or download release DLL files and put into unity project.

**Comment by jradesenv** [comment]
Thanks. I was thinking about NUGET or something hehe. But thanks, its working now!!

**Comment by Thraka** [comment]
@RevenantX Will NuGet be added? I'm generally done with downloading release dll's and installing manually. I want it automated 😄

**Comment by RevenantX** [comment]
@Thraka https://github.com/RevenantX/LiteNetLib/issues/62 
So i suppose - yes)

**Comment by RevenantX** [comment]
@Thraka added nuget https://www.nuget.org/packages/LiteNetLib/

**Comment by devingDev** [comment]
Which folder do I have to copy I don't understand, The root folder called LiteNetLib or the one inside that called LiteNetLib as well ???

**Comment by RevenantX** [comment]
@devingDev https://github.com/RevenantX/LiteNetLib/tree/master/LiteNetLib this folder.
