### ISSUE TITLE
Server demo on front page does not match latest version

### ISSUE THREAD

**Issue by Reelix** [RevenantX/LiteNetLib#210]
Release: LiteNetLibStandard-0.7.7.2.zip

On the "Code" page under Server, it has

`NetManager server = new NetManager(listener);`

This is no longer applicable in 0.7.7.2 as NetManger requires 2 or 3 arguments, and does not work with 1.

I suspect the entire example is outdated :p

**Comment by RevenantX** [comment]
@Reelix 
At main page there is example for next version 0.8.
There is link on main github page to stable branch with 0.7.7.2 example:
https://github.com/RevenantX/LiteNetLib/tree/0.7
