### ISSUE TITLE
"NM Bad!"

### ISSUE THREAD

**Issue by rikimaru0345** [RevenantX/LiteNetLib#212]
I'm getting this here:

https://i.imgur.com/fWZPXhS.png

From what I can see that means that we have received some "unaligned" or "unexpected" data?
Anyway, the `return false;` is hit, and then it goes to NetManager.cs : line 587
To "DataReceived bad!"

I got this while trying to figure out why my reject packets are not received.
Everything works fine normally, except when I want to reject a connection with a message.
Then the client doesn't receive the rejection from the server and keeps trying.

I have set a "Action-Breakpoint" to log a message in NetPeer.cs, and it is indeed hit!
https://i.imgur.com/koNaY6Q.png

But my client somehow doesn't receive the message.
It only works sometimes. Only when I have a breakpoint in there and step through it, the client receives the reject packet as intended.

It is definitely a timing issue somehow, as soon as I add a delay it starts working.

Version: the latest 0.7 branch.

**Comment by RevenantX** [comment]
@rikimaru0345 
>I'm getting this here:
>https://i.imgur.com/fWZPXhS.png

This code on screenshot from 0.8 branch. Are you sure that library on both sides are same versions?

**Comment by rikimaru0345** [comment]
Indeed it's from the 0.8 branch, sorry! 

I'm sure both sides are the same version because there are no two sides (no two separate executables I mean).

In my tests, I'm starting client and server from the same process.

**Comment by RevenantX** [comment]
@rikimaru0345 try latest version. I possibly fixed this.

**Comment by RevenantX** [comment]
@rikimaru0345 
>Another strange thing is that the server keeps spaming that Reject message to the client, even after disconnecting:

This is normal behaviour. It will send reject messages in "DisconnectTimeout" (by default 5 seconds) time.

**Comment by rikimaru0345** [comment]
`try latest version. I possibly fixed this.`
I downloaded the latest master branch, it didn't fix the issue.

`This is normal behaviour. It will send reject messages in "DisconnectTimeout" (by default 5 seconds) time.` 
I see, that makes sense. I have the disconnect timeout on a high value (4 min) on purpose so I can debug while testing things.

**Comment by RevenantX** [comment]
@rikimaru0345 https://github.com/RevenantX/LiteNetLib/commit/9c8a27fef35274493608914bd3cc8b67db60abba this commit?

**Comment by rikimaru0345** [comment]
Yes, I have that exact version. Commit hash matches, and the code does as well:
https://i.imgur.com/iOvkpFd.png

**Comment by RevenantX** [comment]
@rikimaru0345 do you have `MergeEnabled == true`? Can you disable (if it enabled) for test. And if you can please send me buffer that you receive in NetPacket.cs `FromBytes` method

**Comment by rikimaru0345** [comment]
I'll try and report back as quickly as possible!

**Comment by rikimaru0345** [comment]
I wrote "one of the responses" because I thought maybe the server would send multiple different things. But it actually, sends only that exact same message all the time.

I will now try to see what exactly is different between the buffer I got here, and what happens when I re-enable MergeEnabled and then set a breakpoint to wait (so it works).

Maybe the buffer is different when it works...
Give me a few more minutes.

**Comment by rikimaru0345** [comment]
Yes, the buffer is different now:

`"0A-3E-34-F3-91-BA-09-D6-08-49-6E-76-61-6C-69-64-20-76-65-72-73-69-6F-6E-2E-20-53-65-72-76-65-72-20-56-65-72-73-69-6F-6E-3A-20-27-47-61-6D-65-20-31-2E-30-2D-31-36-34-35-39-31-33-30-38-39-27"`

**Comment by RevenantX** [comment]
@rikimaru0345 i found some bugs. And fixing them.

**Comment by RevenantX** [comment]
@rikimaru0345 fixed broken connection reject. And added delay betwen shutdown packets. Check fix)

**Comment by rikimaru0345** [comment]
Everything works nicely now! Thanks!

**Comment by RevenantX** [comment]
@rikimaru0345 thanks for bug report and investigation)

**Comment by tcsaddul** [comment]
Wow! That's super fast fix.
   On Friday, August 24, 2018, 9:18:41 PM GMT+8, Ruslan Pyrch <notifications@github.com> wrote:  
 
 
@rikimaru0345 thanks for bug report and investigation)
