### ISSUE TITLE
[Enhancement] Pass the NetPeer that sent the packet to the subscribed handler method.

### ISSUE THREAD

**Issue by Orsidus** [RevenantX/LiteNetLib#216]
Currently when subscribing to a packet there is seemingly no direct way to get the connected peer that the packet came from. It would be really useful for situations where you want the client might need a response from the server. 

If the ReadPacket/ReadAllPackets method took the optional NetPeer that is provided to the NetworkReceiveEvent handler method and then passed it along, it would allow you to process packets with the NetPeer, this is also useful if you need access to the tag parameter of the NetPeer.

**Comment by RevenantX** [comment]
@Orsidus this is already done:
https://github.com/RevenantX/LiteNetLib/blob/master/LibSample/PacketProcessorExample.cs
