### ISSUE TITLE
Modifying the Lib 

### ISSUE THREAD

**Issue by Adevien** [RevenantX/LiteNetLib#217]
Hi, i was doing some modifications to the lib (added few classes / code changes), and after compile it only works on server and somehow on client,i can connect but i don't receive packets.

Actually no matter what the lib contains it will not work right.
Tried clean build , more versions.

**Comment by RevenantX** [comment]
@Adevien well, i don't know that modifications you made :) How i can help you? Some things in library is not very simple to modify. Maybe you modified some critical code.

**Comment by Adevien** [comment]
I tried with empty library, and i don't get packets anymore. i think is an issue with PollEvents on unity side.

**Comment by RevenantX** [comment]
@Adevien if you tried UnitySample from library repo there is old version of library.

**Comment by Adevien** [comment]
I know, i updated it.

**Comment by Adevien** [comment]
The issue i have is on Unity, with fresh compiled library. The PollEvent doesn't work right.
But when i use the one from releases is working.

**Comment by RevenantX** [comment]
@Adevien could you provide minimal exapmle of problem? Maybe project sources that doesn't work.

**Comment by Adevien** [comment]
Is not an exact issue, packets gets dropped for no reason on local.

**Comment by Adevien** [comment]
But is happening only when changing the compiled library from https://github.com/RevenantX/LiteNetLib/releases

to one compiled by me. Doesn't matter if is clean / modifed.

**Comment by RevenantX** [comment]
@Adevien compiled from 0.7 branch or master (0.8)?

**Comment by Adevien** [comment]
0.7.7.2

**Comment by Adevien** [comment]
not sure how stable is 0.8. I tought was something wrong with my VS and tried from other rig. Same issues.

**Comment by Adevien** [comment]
0.7.7.2 that is precompiled works fine. Only one compiled by me doesn't work.

**Comment by RevenantX** [comment]
@Adevien libraries from releases page and source - identical. They compiled on appveyor: https://ci.appveyor.com/project/RevenantX/litenetlib/build/0.7.315/artifacts

**Comment by Adevien** [comment]
Then what could be the problem? Im using the precompiled and is work, but i want to compile it myself it starts to drop packets.

**Comment by Adevien** [comment]
Can you check if is something wrong? I get packets dropped that would work with precompiled one.

[0.7.7.2 Compiled by me.zip](https://github.com/RevenantX/LiteNetLib/files/2343480/0.7.7.2.Compiled.by.me.zip)

**Comment by Adevien** [comment]
FIXED: Was an instance issue, on Scene Change. The DontDestroyOnLoad of Network instance wasn't saved, only the GameObject and script class. I had to re-create an instance before swapping servers. Thanks for the time and sorry for dumb questions 
 :1st_place_medal:
