### ISSUE TITLE
Is this strictly a peer to peer library?

### ISSUE THREAD

**Issue by njbrown09** [RevenantX/LiteNetLib#218]
If this made only to be used in p2p games? or is it just a connection between a client and server?

**Comment by RevenantX** [comment]
@njbrown09 because this library based on UDP it can be used as p2p and/or client/server.

**Comment by njbrown09** [comment]
Thats the thing. In testing, some of the clients have been getting messages sent by other clients. Its weird too. Its not 100% of the time. Maybe 0.05% of the packets get received by other clients instead of just the server.

**Comment by RevenantX** [comment]
@njbrown09 this is very weird. How this can be possible? Clients doesn't know about other clients
