### ISSUE TITLE
Question about NetDataWriter

### ISSUE THREAD

**Issue by njbrown09** [RevenantX/LiteNetLib#220]
It doesnt seem to be recyclable. Should i just create one instance of it and then reset and reuse it? or is there a proper way to get rid of it after im done so it wont eat gc allocations?

**Comment by RevenantX** [comment]
>Should i just create one instance of it and then reset and reuse it? 

@njbrown09 yes)

**Comment by xmedeko** [comment]
Yes, just call `writer.Reset();`. To send the message, do not use `CopyData`, but the writer itself: `peer.Send(writer, SendOptions....)`.

Note: this writer reuse is not thread-safe.
