### ISSUE TITLE
Time sync client and server

### ISSUE THREAD

**Issue by xmedeko** [RevenantX/LiteNetLib#221]
Since the `NetManager` uses incoming packet queue, the processing of the incoming packet may be delayed. So, I need some packet `ArrivalTime` in the `INetEventListener.OnNetworkReceive` request to be able more accurately sync the time between client and server. Typical time sync is
```c#
serverTime = packet.ServerTime + ping / 2;
```
I thing for the LiteNetLib `NetManager` I would need to correct it
```c#
serverTime = packet.ServerTime + ping / 2 + (DateTime.Now - packet.ArrivalTime);
```

I know the difference ` (DateTime.Now - packet.ArrivalTime)` is usually small (tens of ms), so it's not a blocker for me, but it would be nice to have it.

**Comment by RevenantX** [comment]
Added simple time sync with pong packet

**Comment by RevenantX** [comment]
https://github.com/RevenantX/LiteNetLib/commit/0a772486b0322def150d8b10e3e8b0a7cf5d5724
