### ISSUE TITLE
[Unity] Client doesnt disconnect when you exit play mode in the editor

### ISSUE THREAD

**Issue by njbrown09** [RevenantX/LiteNetLib#223]
It appears that exiting playmode in the unity editor doesnt properly shut down litenetlib as if the application was just closed.

Work Around
```csharp
//Add this to any monobehaviour that has a litenetlib netmanager on it
void OnApplicationQuit()
    {
       theNetManagerObject.Stop();
    }
```

**Library version**: Master
**Framework**: Unity

**OS**: Windows

**Comment by RevenantX** [comment]
@njbrown09 this is expected behavior.

**Comment by njbrown09** [comment]
I assumed. You might want to add something to the readme as this caused me several hours of trouble.

**Comment by RevenantX** [comment]
@njbrown09 unityexample shows this. It uses `Stop()` in OnDestroy method.
Maybe i will add some F.A.Q.

**Comment by njbrown09** [comment]
Ah ok my bad.
