### ISSUE TITLE
Replace compile time check STATS_ENABLED with a runtime check

### ISSUE THREAD

**Issue by xmedeko** [RevenantX/LiteNetLib#224]
Replace #STATS_ENABLED with some bool flag like `Statistics.Enabled` or `NetManager.StatisticsEnabled`, so it may be enabled/disabled without recompiling. AFAIK a simple bool flag check does not affect the CPU.

**Comment by RevenantX** [comment]
done with pr: https://github.com/RevenantX/LiteNetLib/pull/364
