### ISSUE TITLE
NetManager.Stop() hangs on Linux for client code

### ISSUE THREAD

**Issue by xmedeko** [RevenantX/LiteNetLib#226]
Just have s simple client
```csharp
NetManager client = new NetManager(this);
client.Start();
client.Connect("127.0.0.1", xxxx);
//...
client.Stop();
```

It runs well on Windows, however hangs on `client.Stop()` on Linux. (.NET Core 2.1 on both OSes). Note: server code `Stop()` finishes well on Linux.

**Library version**:  0.7.7.2 (from NuGet for .NET Core 2.1)
**Framework**: dotnetcore 2.1
**OS**: Linux (Ubuntu 18)

**Comment by RevenantX** [comment]
@xmedeko there was bug with blocking sockets in 0.7.7.1. In 0.7.7.2 this was fixed. This is very strange. Can you recheck library versions on both client and server?

**Comment by xmedeko** [comment]
`<PackageReference Include="LiteNetLib" Version="0.7.7.2" />` it's just a fresh project which uses just this version 0.7.7.2 from it's start. The `LiteNetLib.dll` has 77312 bytes.

I have removed NuGet and used the source code (zip from the [GitHub release page](https://github.com/RevenantX/LiteNetLib/releases)) and it runs well.

**Comment by RevenantX** [comment]
@xmedeko hmm. there can be a old packet. I will look into this.

**Comment by RevenantX** [comment]
@xmedeko checked. Local nuget package that was uploaded contains 0.7.7.2, installed package into project from nuget contains 0.7.7.1. O_o

**Comment by RevenantX** [comment]
@xmedeko try update to 0.7.7.3 in nuget. I checked reupload fixed this.

**Comment by xmedeko** [comment]
Yep, works fine with 0.7.7.3.
I'll probably rather use sources instead of NuGet. I have just a test client code in .NET Core, my target platform is Unity and is should have the sources included. So, the test client and the Unity code would be more similar.
