### ISSUE TITLE
INetLogger use standard logging levels instead of colors

### ISSUE THREAD

**Issue by xmedeko** [RevenantX/LiteNetLib#227]
Use standard logging levels for `INetLogger`, like Fatal, Error, Warn, Info, Debug and maybe Trace, instead of colors. So, it's easier to plug in to libraries like NLog, log4net, etc.

**Comment by RevenantX** [comment]
@xmedeko i used colors for other debug purposes) not for logging levels)

**Comment by xmedeko** [comment]
Yes, you can continue to use colors. Just make the interface:
```c#
public interface INetLogger
    {
        void WriteNet(Level level, string str, params object[] args);
    }
```
And ten make some implementation `ColoredLogger` and that's all.

Furthemore, it's not necessary to have DEBUG_MESSAGES compile time switch. It's enough to make some `VoidLogger` and plug it as default. I can make a PR with some logging facade, if you like. (For 0.7 version).

**Comment by RevenantX** [comment]
@xmedeko 
>Furthemore, it's not necessary to have DEBUG_MESSAGES compile time switch. It's enough to make some VoidLogger and plug it as default.
This is necessary because this can cause slow performance. Most debug calls creating many boxed variables (because of params object[]).

**Comment by xmedeko** [comment]
Ah yes, I do not like these logging interfaces `(string str, params object[] args)` anyway. So, just make more elaborate interface:
```c#
public interface INetLogger
{
    void WriteNet(Level level, string str);
    bool IsDebugEnabled {get;}
    bool IsInfoEnabled {get;}
    bool IsWarnEnabled {get;}
    bool IsErrorEnabled {get;}
}
```
And then each log like:
```c#
if (logger.IsInfoEnabled) logger.Info(...);
```
The good magic about logging is when you can switch in on/off in the production code just by config.

Anyway, even if you want to keep the `DEBUG_MESSAGES` switch, please make the interface with levels, not colors.

**Comment by NVentimiglia** [comment]
I think an Enum to switch on would be cleaner than 4 bools

**Comment by xmedeko** [comment]
@NVentimiglia Yes, it's easier to have just one method `bool IsLogEnabled(Level level)` for the interface implementer, but more complicated to use. Unfortunately, C# has no extension properties. So it's possible to write extension methods `bool IdDebugEnabled()` then. I have chosen this solution, since it's IMO better. E.g. see the [common's logging ILog facade](https://github.com/net-commons/common-logging/blob/master/src/Common.Logging.Core/Logging/ILog.cs).
