### ISSUE TITLE
Timeout on disconnect in 0.7.7.2

### ISSUE THREAD

**Issue by xmedeko** [RevenantX/LiteNetLib#228]
I have a stress test client, which starts N threads with clients. I start the server and client on my developer machine, i.e. localhost.

Client: connects to a server and sends 2 `ReliableOrdered` just after the connect, i.e. in the `INetEventListener.OnPeerConnected` method.
Server: just after receiving the first `ReliableOrdered` message, it issues `server.DisconnectPeer(peer, writer)`. 

Mostly, the client gets  of the clients gets `Disconnected RemoteConnectionClose` and that's OK. But sometimes a client gets `Disconnected Timeout` (wrong). Ive plugged in the debugging and see some `ReliableOrdered` message is keeping resending, but there should be no packet lost on localhost. (End even if some packet would be lost, I would expect just one resend, not resending all time.)

Client log _(repeated many times)_:
```
DarkGreen [RC]Resend: 31 > 27
DarkYellow [P]SendingPacket: ReliableOrdered
Blue [S]Send packet to 127.0.0.1:14325, result: 203
DarkGreen [RC]Resend: 31 > 27
DarkYellow [P]SendingPacket: ReliableOrdered
Blue [S]Send packet to 127.0.0.1:14325, result: 17
```

Server log _(repeated many times)_:
```
[R]Recieved data from 127.0.0.1:63048, result: 203
[R]Recieved data from 127.0.0.1:63048, result: 17
```

**Library version**: 0.7.7.2
**Framework**: .NET Core 2.1
**OS**: Windows

**Comment by RevenantX** [comment]
@xmedeko 
>End even if some packet would be lost, I would expect just one resend, not resending all time.

This needed for reliability and fast delivery.

Can you try this test in 0.8 library? I think i fixed most possible bad cases with this situation.

**Comment by RevenantX** [comment]
@xmedeko 0.8 almost stable (and works in many places better than 0.7) i think i will make new release version.

**Comment by xmedeko** [comment]
Yes, the problem does not appear with 0.8.
