### ISSUE TITLE
0.8 Client.Stop does not send disconnect

### ISSUE THREAD

**Issue by xmedeko** [RevenantX/LiteNetLib#229]
In 0.7 `NetManager.Stop()` has sent disconnect message, but in 0.8 it stops without any message sent. Is it intended or bug? I see the code `netPeer.Shutdown(null, 0, 0, true);` and that the last param `force = true` causes not to send the disconnect message.

**Library version**: commit id cd84459 0.8indev
**Framework**:  .NET Core
**OS**: Linux, Windows

**Comment by RevenantX** [comment]
@xmedeko this i forgot to return to "false" after some tests.

**Comment by xmedeko** [comment]
Furthemore, I've tested 100 clients to connect to the server, then called 'Stop()'. The server has received `OnPeerDisconnected Timeout` just for some of them. It does not detect the Timeout for most of the clients and keeps them in the pool.

**Comment by RevenantX** [comment]
@xmedeko can you show this sample code?

**Comment by xmedeko** [comment]
**More info:** I've tried a bit debugging. After stopping all clients and waiting for 15 sec (more than `DisconnectTimeout`), the server reports: `PeersCount`: 30, but `GetPeers((ConnectionState)0xff)` returns always just one connection in the `Disconnected` state.

Waht about to add cleanup of disconnected peers in the `NetManager` just as an error fallback?

**Comment by RevenantX** [comment]
@xmedeko thanks for debugging. I will fix this soon.

**Comment by RevenantX** [comment]
@xmedeko fixed.

**Comment by xmedeko** [comment]
@RevenantX I've tested it and it's OK. Thanks.
