### ISSUE TITLE
Throw "System.EntryPointNotFoundException：getifaddrs " in android

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#23]

**Comment by RevenantX** [comment]
Can you provide more information?

**Comment by QiuBuZai** [comment]
System.Net.NetworkINformation.LinuxNetworlnterface.ImplGetAllNetworkInterfaces();
 System.Net.NetworkINformation.Networlnterface.GetAllNetworkInterfaces();
Rethrow as TypeInitializationException:An exception war thrown by the type initializer for LiteNetLib.NetSocket;
LiteNetLib.NetManager..ctor(NetEventListener,Int32 maxCOnnections, System.String connectkey);
LiteNetLib.NetManager..ctor(NetEventListener,System.String connectkey))

**Comment by QiuBuZai** [comment]
API compatibility level is ".Net2.0"

This seems to be a bug in the anroid platform

**Comment by RevenantX** [comment]
in NetUtils.cs there is some code that access method "GetAllNetworkInterfaces" but for android there is "try catch".
https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/NetUtils.cs#L86

But you get this exception inside NetSocket constructor?

**Comment by QiuBuZai** [comment]
Yes。But I can't find method "GetAllNetworkInterfaces" inside NetSocket constructor;

The same will be error。Only when  I set the API compatibility level to ".Net2.0"；My project need .Net2.0。

**Comment by QiuBuZai** [comment]
Is not just catch this exception can let the normal operation of the program

**Comment by RevenantX** [comment]
fixed
