### ISSUE TITLE
Info: New example project

### ISSUE THREAD

**Issue by Adevien** [RevenantX/LiteNetLib#230]
Hi, a new example project including player spawn and movement would be good? I have one for 0.7.7.2 but i can update it for 0.8 for you to add it on the stable release. Let me know.

**Comment by RevenantX** [comment]
Hi! I think this will be cool) Better for 0.8 because i plan soon release it as stable version.

**Comment by Adevien** [comment]
This weekend ill update it on my github and let you know, maybe friday.

**Comment by Adevien** [comment]
@RevenantX Sorry for the delay, got some issues & a cold. Is there a way to fast forward send the data received from a client?  Example : [Client - Node - Server] .

**Comment by RevenantX** [comment]
@Adevien you can always just use peer.Send(NetDataWriter.FromBytes( netPacketReader.GetRemainingBytes(), false));

**Comment by RevenantX** [comment]
https://github.com/RevenantX/NetGameExample
