### ISSUE TITLE
ProcessConnectRequest fails if Debug messages are enabled

### ISSUE THREAD

**Issue by bojkott** [RevenantX/LiteNetLib#232]
The line
 `NetUtils.DebugWrite("ConnectRequest LastId: {0}, NewId: {1}, EP: {2}", netPeer.ConnectId, connRequest.ConnectionId, remoteEndPoint);` 
at NetManager.cs:561 fails if netPeer is null and DEBUG_MESSAGES are enabled. This should be moved inside the nullCheck below.

**Comment by RevenantX** [comment]
Thanks for report! Fixed)
