### ISSUE TITLE
Multiple servers start on same port on Linux

### ISSUE THREAD

**Issue by hkben** [RevenantX/LiteNetLib#235]
I want to start multiple servers on one computer , so i wrote the code below to auto start a server using other available port. Code works fine on Windows (2 process : port 9000 , port 9001) , but when I run it on Linux , all server started on same port .

```csharp
var port = 9000;

do
{
    network.Start(port);
    port++;
} while (!network.IsRunning);
```

**Library version**: 0.8 , 0.7

**Framework**: Mono

**OS**: Amazon Linux

**Comment by RevenantX** [comment]
Can you provide full example?

**Comment by hkben** [comment]
https://gist.github.com/hkben/69e7f99d5e4352666f7bb62471ff7f4a

Its just very simple code . When I run 2 exe on Windows , I got port 9000 and 9001 . 

When I run `mono server.exe &` on Linux twice , I got both port 9000.

**Comment by RevenantX** [comment]
@hkben 
```csharp
            for(int i = 0; i < 2; i++)
            {
                _serverListener = new ServerListener();
                NetManager network = new NetManager(_serverListener, 2, "myapp1");
                network.Start(port);
                port++;
                Console.WriteLine("Server start on Port {0}", network.LocalPort);
                _serverListener.Server = network;
            } 
```
You have some very strange code. This is more correct.

**Comment by hkben** [comment]
@RevenantX 
But it just starts 2 servers on 1 process , what I'm doing is start 2 servers on 2 different processes . The do-while code is for scanning available port automatically.

**Comment by xmedeko** [comment]
@hkben Better and safe way is specify port from command line or some config and let process exist if the port is busy. Your way you may have troubles if you have some errors, like if a process hangs, etc.

On the linux - the server start on the same port and same IP address (same NIC)? Maybe you have more local ip addresses on Linux. Try `netstat -u -l`.

**Comment by hkben** [comment]
@xmedeko 
Just tested on Linux again , I started 3 servers on same port (29410) and the netstat result is : 
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 0.0.0.0:cisco-tdp       0.0.0.0:*
udp        0      0 0.0.0.0:29410           0.0.0.0:*
udp        0      0 0.0.0.0:29410           0.0.0.0:*
udp        0      0 0.0.0.0:29410           0.0.0.0:*
udp        0      0 localhost:323           0.0.0.0:*
udp        0      0 0.0.0.0:bootpc          0.0.0.0:*
udp        0      0 0.0.0.0:sunrpc          0.0.0.0:*
udp6       0      0 [::]:cisco-tdp          [::]:*
udp6       0      0 [::]:29410              [::]:*
udp6       0      0 [::]:29410              [::]:*
udp6       0      0 [::]:29410              [::]:*
udp6       0      0 localhost6:323          [::]:*
udp6       0      0 ip-172-31:dhcpv6-client [::]:*
udp6       0      0 [::]:sunrpc             [::]:*
```
 
I am not sure if specify port is suitable for me , because I want to deploy and restart multiple game servers automatically on AWS . But I will consider changing my flow to use specify port only .

**Comment by xmedeko** [comment]
Do you use Mono or .NET Core? I've just tried that on .NET Core and Ubuntu 18 and it works properly.

**Comment by hkben** [comment]
@xmedeko 

This code works for me . I started 2 servers and I can see port 29410 and 29411 on netstat .
```csharp
_udpSocketv4.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, false);
```
But an error occurred when it try to Bind IPv6 Socket .

```
[B]Bind exception: System.Net.Sockets.SocketException (0x80004005): Address already in use
  at System.Net.Sockets.Socket.Bind (System.Net.EndPoint localEP) [0x00043] in <c9b43c60e5b84ea98d756d8161e8fdab>:0
  at LiteNetLib.NetSocket.BindSocket (System.Net.Sockets.Socket socket, System.Net.IPEndPoint ep) [0x00018] in <971d64bdb46a4df083a3b644b33a233c>:0
```

I have tried to change :
```csharp
if(reuseAddress)
    _udpSocketv6.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
```
to :
```csharp
_udpSocketv6.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, false);
```
But it's not helping.

**Comment by hkben** [comment]
@xmedeko 

Before servers stop :
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 0.0.0.0:cisco-tdp       0.0.0.0:*
udp        0      0 0.0.0.0:29410           0.0.0.0:*
udp        0      0 0.0.0.0:29411           0.0.0.0:*
udp        0      0 localhost:323           0.0.0.0:*
udp        0      0 0.0.0.0:bootpc          0.0.0.0:*
udp        0      0 0.0.0.0:sunrpc          0.0.0.0:*
udp6       0      0 [::]:cisco-tdp          [::]:*
udp6       0      0 localhost6:323          [::]:*
udp6       0      0 ip-172-31:dhcpv6-client [::]:*
udp6       0      0 [::]:sunrpc             [::]:*
```

After servers stop :
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 0.0.0.0:cisco-tdp       0.0.0.0:*
udp        0      0 localhost:323           0.0.0.0:*
udp        0      0 0.0.0.0:bootpc          0.0.0.0:*
udp        0      0 0.0.0.0:sunrpc          0.0.0.0:*
udp6       0      0 [::]:cisco-tdp          [::]:*
udp6       0      0 localhost6:323          [::]:*
udp6       0      0 ip-172-31:dhcpv6-client [::]:*
udp6       0      0 [::]:sunrpc             [::]:*
```

**Comment by xmedeko** [comment]
Hmm, this problem is not easy, e.g. see 
https://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t
https://github.com/dotnet/corefx/issues/11292

I do not know it in depth, just a guess - try
```c#
_udpSocketv6.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, true);
```

**Comment by hkben** [comment]
@xmedeko 
It works ! Thank you ! :+1: 
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 0.0.0.0:cisco-tdp       0.0.0.0:*
udp        0      0 0.0.0.0:29410           0.0.0.0:*
udp        0      0 0.0.0.0:29411           0.0.0.0:*
udp        0      0 localhost:323           0.0.0.0:*
udp        0      0 0.0.0.0:bootpc          0.0.0.0:*
udp        0      0 0.0.0.0:sunrpc          0.0.0.0:*
udp6       0      0 [::]:cisco-tdp          [::]:*
udp6       0      0 [::]:29410              [::]:*
udp6       0      0 [::]:29411              [::]:*
udp6       0      0 localhost6:323          [::]:*
udp6       0      0 ip-172-31:dhcpv6-client [::]:*
udp6       0      0 [::]:sunrpc             [::]:*
```

**Comment by RevenantX** [comment]
@hkben @xmedeko cool information. I will add this as fix.

**Comment by RevenantX** [comment]
@hkben @xmedeko but this property only exists starting from .net framework 4.0 (and .net core)

**Comment by xmedeko** [comment]
@RevenantX this problem is not for .NET Core, the problem is in stand-alone Mono on Linux (maybe @hkben may post the Mono version.) So, the `#if NETCORE` in the 860d54e commit is wrong. Also, to fix the problem, I think @hkben had to use (please, confirm):

```c#
_udpSocketv4.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, false);
_udpSocketv6.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, false);
_udpSocketv6.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, true);
```

If the `SocketOptionName.IPv6Only` is missing on some platforms, then you may use the int value 27 instead. But without real testing it's useless to set it. The code portability is a real problem here.

I suggest:
instead of `if (reuseAddress) ...` use:
```c#
_udpSocketv4.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, reuseAddress);
```
Or use three state flag `bool? reuseAddress` when `null` means do not change default.

Use the `SocketOptionName.IPv6Only` for platforms that support it, is you can flag it with some `#if` or use the value 27 instead.

**Comment by RevenantX** [comment]
@xmedeko reuseAddress in socket disabled by default.

**Comment by xmedeko** [comment]
@RevenantX apparently not for the @hkben See all comments in this issue, he has reported:


> This code works for me . I started 2 servers and I can see port 29410 and 29411 on netstat .
> 
> _udpSocketv4.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, false);

**Comment by RevenantX** [comment]
i will refix this.
