### ISSUE TITLE
Connection stops working due to failed MTU discovery

### ISSUE THREAD

**Issue by Alloc86** [RevenantX/LiteNetLib#237]
Hi,

did you have or heard of any issues with connections no longer working at some point? _Some_ of our testers have the issue that at some point during the connection they no longer receive any data on their end. The other direction, i.e. the data the client sends to the server, still works though.

So far I nailed it down to the LiteNetLib part by putting debug logging to the place where we call NetPeer.Send and on the other end to the NetworkReceiveEvent. As long as data is transmitted normally we get the log output on both ends just fine with the same size of packages but as soon as it stops working only the server side send logs show, the client side never fires the NetworkReceiveEvent.

We only use SendOptions.ReliableOrdered for all our data. Also watching the NetworkErrorEvent but that's not fired either.

Was wondering... when not calling PollEvents for a moment (like 20 seconds) could that kill the connection? I suppose it should handle all the connection keep alive stuff and data reception on its own in the background threads and PollEvents is just to actually get the events handled by the caller?

Of course could the issue still be caused by our software but I'm currently out of ideas.

**Library version**: release version (0.7.7.2)

**Framework**: Unity

**OS**: Windows

Regards,
Chris

**Comment by Alloc86** [comment]
Well, I don't have any idea if the source of the issue is the same, but from a high level view this is not about disconnects at all :)
There's neither a manual disconnect happening nor do I get any kind of automatic disconnects like from timeouts. It's simply stopping to receive the packets on the client side while the other direction on the same LiteNetLib connection still works fine.

**Comment by RevenantX** [comment]
@Alloc86 
>Was wondering... when not calling PollEvents for a moment (like 20 seconds) could that kill the connection?

No)

> I suppose it should handle all the connection keep alive stuff and data reception on its own in the background threads and PollEvents is just to actually get the events handled by the caller?

You are right.

Well in 0.7.7.2 some code parts (and architecture) works bad. I think there is some error in reliable channel (and possibly hard to detect). Can you try please 0.8 branch version? I rewrited some bad parts of reliable channel in 0.8. I will make 0.8 release soon. And if all works correct and you want to stay on 0.7.x branch i can backport this fixes into 0.7 branch.

**Comment by nxrighthere** [comment]
Which Unity version are you running on? It might be a bug in the Unity if you are using .NET 4.6 (it's still unstable and in some cases `Socket.ReceiveFrom` may fail and stop receiving any data. Switching to .NET 3.5 should solve this problem, just as a temporary solution.

**Comment by xmedeko** [comment]
@nxrighthere I had that problem with #228 on .NET Core 2.1 both client and server.

**Comment by Alloc86** [comment]
Unity 2018.2.1 with the .NET 3.5 framework.

I'll give 0.8 a try and report back :)

**Comment by nxrighthere** [comment]
Yes, this is definitely a bug in the library.

**Comment by RevenantX** [comment]
@Alloc86 thanks!

**Comment by Alloc86** [comment]
Unfortunately updating to the latest master didn't solve the issue. Also added a debug log to the NetManager.ReceiveFromPeer method to make sure it's not us for some reason stopping to call PollEvents. Not seeing the incoming packets there either though.

Will get a Wireshark snapshot today and see if the packets even arrive at his system.

(Btw, when I did the same thing on my end (working connection) to test the Wireshark setup, I noticed that I receive quite a lot of the packets two times)

**Comment by RevenantX** [comment]
@Alloc86 seems that reliable channel become broken at some moment. Maybe because of some invalid data (maybe some packets corrupted and without checksum).

**Comment by Alloc86** [comment]
Yeah, now I suppose the question is *why?* ;)

**Comment by Alloc86** [comment]
Oh, btw, I see didn't specify that clearly in the initial post: The point that (at least this one user I'm testing with) gets the issue is always the same, i.e. it's always the same last successfully received package. After that it's a fragmented message (though there are a bunch of successfully delivered fragmented messages before) that's never received and nothing else afterwards either.
And I can connect to the same server just fine and receive all the data, so it does not seem to be a generic issue with fragmented messages or anything like that, but of course it *could* still be related to the specific binary content of the messages or something like that as that varies a little bit between different users.

**Comment by Alloc86** [comment]
PS: I can give you access to the current game builds that show the issue, but no idea if that would help you without our source to actually debug it.

**Comment by Alloc86** [comment]
Hm, the captured data isn't as readable as I hoped it was. Shows a lot of "Fragmented IP Protocol" entries (even on the sender side ... would've assumed that this should not be the case with LiteNetLib sending packets smaller than the MTU?) which seem to be part of the actual UDP traffic so it's harder to read the data in there.

**Comment by xmedeko** [comment]
@Alloc86 have you tried LiteNetLib debug logging (compile the client with DEBUG, DEBUG_MESSAGES)? Or try to examine the state of `ReliableChannel` after the problem - how many `_receivedPackets, _pendingPackets, _outgoingAcks` it has, etc.

**Comment by Alloc86** [comment]
@xmedeko Issue with looking at stuff is that I have to log it out on the client at appropriate events as I can't debug on the tester's machine (and none of our devs had this issue yet). But I will definitely add the script defines to the next build :)

**Comment by RevenantX** [comment]
@Alloc86 this defines (DEBUG_MESSAGES) reduces performance alot. Better replace some places with DebugWriteForce. I will add some checks to reliable channel to see if it become broken at some point.

**Comment by xmedeko** [comment]
Also, if you may log some state by a Timer tick only, e.g. log a state of `ReliableChannel` in 1, or 5 min interval only. And instruct your testers to wait after the problem occurs and then send you the logs.

@RevenantX the logging performance is the problem of #227. If you have proper designed logging, you may log warnings e.g. if the channel buffer is full etc. Then you may switch on logging just for Warn and Error levels without big performance penalty.

**Comment by RevenantX** [comment]
@Alloc86 @xmedeko i added discord chat https://discord.gg/FATFPdy

**Comment by Alloc86** [comment]
Seems like RevenantX was correct, it was an MTU issue that he fixed in a commit today. Thanks a lot :)

**Comment by RevenantX** [comment]
@Alloc86 thanks for debugging)

**Comment by Alloc86** [comment]
Seems like it's not completely ok right now. With the latest code we get the issue again. Have disabled the MTUs 1500 and 2304 again for the next build to try again.

**Comment by RevenantX** [comment]
@Alloc86 what platform?

**Comment by Alloc86** [comment]
Unity 2018.2.1, .NET 3.5, Windows 64 bit players on both sides.

**Comment by xmedeko** [comment]
I am not so strong in networking, but is it possible to detect the drop by fragmentation by some ICMP? https://en.wikipedia.org/wiki/Path_MTU_Discovery

**Comment by Alloc86** [comment]
Well, seems like it works if the MTU is restricted to 1492 in our tests. Of course there could be situations where even that fails. Seems like the MTU detection code isn't fully working yet?

**Comment by RevenantX** [comment]
@Alloc86 MTU less than 1492 is very rare (on some very old hardware)

**Comment by xmedeko** [comment]
@RevenantX nope, just found out that [Google Cloud uses MTU 1460](https://cloud.google.com/vpn/docs/concepts/mtu-considerations) and other ISP may do it as well.

**Comment by Alloc86** [comment]
Yeah, I *think* VPNs also lower the MTU (at least pretty sure they did in the past) as they basically have to encapsulate complete UDP packets into their own UDP packets.

**Comment by RevenantX** [comment]
@xmedeko @Alloc86 when DontFragment enabled packets that more than MTU should not be received on other side. And client (and or server) must get socket error - MessageTooLong. Seems that in some rare cases packets will be fragmented anyway (in strange way).

**Comment by xmedeko** [comment]
And can you catch that socket error and lower the MTU?

**Comment by RevenantX** [comment]
@xmedeko MTU is minimal on start and increases by one step in PossibleMtu in first seconds. And if it receive that error - it stops.

**Comment by xmedeko** [comment]
I mean can you catch this error when sending data packets? Then to lower the MTU or trigger the MTU rediscovery?

**Comment by RevenantX** [comment]
@xmedeko i can catch this errors (and there already code for this). But in @Alloc86 case there is no any errors. It just corrupts packet.

**Comment by RevenantX** [comment]
@Alloc86 any news?

**Comment by ObsComp** [comment]
MTU issues? Wowsers that brings me back. This was a known issue inside linksys and dlink routers. What you might be seeing is a drop from a router that loses the packet, creating a hang up or losing part of the data would be my guess. 
Stick at 1492 as you have mentioned, possibly 1490.

**Comment by Alloc86** [comment]
@RevenantX Sorry, just now saw your message when looking if there were any tickets for connection timeouts.
We've been running with the possible MTU sizes array only containing 576 and 1400 to be on the safe side. Think there's been no real issues for the most part.

Though we still do get timeouts that I can see no reason for, but I don't think it's the MTU issue with those values. Most of them seem to happen at random points during gameplay and (at least in some situations, not sure if it applies to all of them) it instantly kicks *all* connected users at that point. No issues reconnecting afterwards.

**Comment by RevenantX** [comment]
@Alloc86 well this all bugs must be fixed in 0.8.3 (from our dialogue on discord we determined that you used old unstable version) so i close this. Reopen if you find this bugs in 0.8.3
