### ISSUE TITLE
No more way to get data without copy??

### ISSUE THREAD

**Issue by rikimaru0345** [RevenantX/LiteNetLib#244]
Hi,
using latest master branch version. ( https://github.com/RevenantX/LiteNetLib/commit/864d411bad6f772c20a012043c55641b334d153d )

NetDataReader and NetPacketReader do not expose any way to get the data directly anymore.
I do not want to copy the bytes into a buffer to work with them, because in my application I can guarantee that I will not be using the buffer after I have handled the `OnNetworkReceive` event.
There is GetBytes with a buffer parameter but that still does a copy that I do not need.

I hope this is just an oversight.
If you are concerned about visibility you can:
a) name the method `GetRawBufferUnsafe()`
b) also decorate it with `[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]`

I want to avoid every useless data-copy, especially in such a straightforward case.

**Comment by RevenantX** [comment]
@rikimaru0345 i removed some copies from internal logic, and result is that NetPacketReader contains all data (with packet internal headers and other things). So just make one copy and then just recycle that packet (`dataReader.Recycle()`)

**Comment by rikimaru0345** [comment]
I see, ok then. 

For the future it might be good to have direct access though (along with some HeaderSize property or something so we know what part of the buffer is the actual payload).

For now making one copy won't be too bad, I'll make one copy, but it would be good to eliminate that as well since it is essentially "free" performance.

**Comment by xmedeko** [comment]
Note: you can set `NetManager.AutoRecycle` and then do not need to call `Recycle()` manually.

**Comment by xmedeko** [comment]
Note: you may set `NetManager.AutoRecycle = true` and then you do not need to call `Recycle()` manually.

**Comment by TwoTenPvP** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.arraysegment-1 ?

**Comment by rikimaru0345** [comment]
Yeah, having the payload available through an ArraySegment would actually solve all those problems!

**Comment by RevenantX** [comment]
@rikimaru0345 you can access NetPacketReader bytes by index - `reader[0]` like in array segment.

**Comment by RevenantX** [comment]
@rikimaru0345 well i made some changes. You now have raw buffer and offset and user data size https://github.com/RevenantX/LiteNetLib/commit/66dd1d34355c265b861fbdff44b92b121e3610a9

**Comment by rikimaru0345** [comment]
Awesome, thank you!

**Comment by RevenantX** [comment]
@rikimaru0345 sorry there was bug (offset always 0))) That fixed in 
960801f
