### ISSUE TITLE
0.8indev connection is not responsive under stress test

### ISSUE THREAD

**Issue by xmedeko** [RevenantX/LiteNetLib#249]
I have tried my stress test with 50 clients and server running at localhost. After approx. 20 clients connects the server and client is becoming less responsive, server issues many disconnects by Timeout.
When I ran the same test with commit e6c2c64 then it runs well. I suspect the blocking sockets may be the problem?

**Library version**: 0.8indev commit dc2521c1f1
**Framework**: .NET Core
**OS**: Windows

**Comment by xmedeko** [comment]
I have tried commit
4d623a90a4 added auto recycle, try using blocking sockets (third time)
It seems to behave a bit better than dc2521c but still has same problems.
I have tried one commit before
7a9a45cb09 Better fix for #235 
And it runs well.

**Comment by xmedeko** [comment]
I have tried dec56ec but with `socket.ReceiveTimeout = 100000` and it seems running ok.

**Comment by xmedeko** [comment]
I think one performance bottleneck is that `socket.ReceiveFrom` ends very often with `SocketException SocketError.TimedOut`. The exceptions are a bit expensive. When I put the code:
```c#
if (socket.Available == 0 && !socket.Poll(100000, SelectMode.SelectRead))
    continue;
result = socket.ReceiveFrom(receiveBuffer, 0, receiveBuffer.Length, SocketFlags.None, ref bufferEndPoint);
```
Then the performance is back. Works well even for blocking socket. I think this double poll is better than throwing exception.

Suggestions:
- Do not log `SocketError.TimedOut`.
- Do the socket `socket.Poll` before read. If it is a performance degradation for high message rate, then make a switch for those who has lower message rates.
- If you need `ReceiveTimeout`, `SendTimeout` for .NET Core only, then
  - Do use them for `#if NETCORE` only and use the `socket.Poll` for `#if NETCORE` too. (Or maybe some `#if NETCORE_LINUX`).
  - Do not use them for other platforms. Then you do not need to use `socket.Poll` for other platforms, too.

**Comment by RevenantX** [comment]
@xmedeko higher frequence will be better for latency.

**Comment by xmedeko** [comment]
I do not see any latency increase with high Poll time wait (have tried 5sec = 5000000). It returns as soon as read data are available.
