### ISSUE TITLE
The ping value is inaccurate。

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#25]
public class NetClient : MonoBehaviour, INetEventListener
{
    private NetManager _netClient;
    private NetPeer _serverPeer;
    private NetDataWriter _dataWriter = new NetDataWriter();
    private int now;
    private SendOptions _option = SendOptions.Unreliable;

    void Start ()
    {
        UberDebug.Log("start");
        _netClient = new NetManager(this, "sample_app");
        _netClient.Start();
    }

    void Update()
    {
        _netClient.PollEvents();
        if (_serverPeer == null || _serverPeer.ConnectionState != ConnectionState.Connected)
        {
            _netClient.SendDiscoveryRequest(new byte[] { 1 }, 5000);
        }
    }

    void OnDestroy()
    {
        if (_netClient != null) _netClient.Stop();
    }

    public void OnPeerConnected(NetPeer peer)
    {
        _serverPeer = peer;
        StartCoroutine(GetPing());
    }

    private IEnumerator GetPing()
    {
        for (int i = 0; i < 20; i++)
        {
            yield return new WaitForSeconds(1f);
            now = DateTime.Now.Millisecond;
            _serverPeer.Send(_dataWriter, _option);
        }
      
    }

    public void OnNetworkReceive(NetPeer peer, NetDataReader reader)
    {
        Debug.Log("ping:" + (DateTime.Now.Millisecond - now));// Response time
is 20+ms
        Debug.Log("serverPeer ping:" + (_serverPeer .Ping));// ping value is 0ms
    }

}

**Comment by QiuBuZai** [comment]
29/5000
Zài júyùwǎng nèi de xiǎngyìng shíjiān jīběn dàyú 30ms, dànshì ping zhí wèi 0;
The response time in the LAN is basically greater than 30ms, but the ping value is 0;

**Comment by QiuBuZai** [comment]
The response time in the LAN is basically greater than 30ms, but the ping value is 0;

**Comment by QiuBuZai** [comment]
Is my calculation method is not right？

**Comment by RevenantX** [comment]
Use more accurate Stopwatch class or 
`long milliseconds = DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond;`

> Is my calculation method is not right？
yes.

**Comment by QiuBuZai** [comment]
Thank you

**Comment by QiuBuZai** [comment]
I think it should be the cause of the event being executed in the Update function。UnsyncedEvents is false。

**Comment by RevenantX** [comment]
Very possible.
