### ISSUE TITLE
Get the IPv4 address

### ISSUE THREAD

**Issue by SokratesMir** [RevenantX/LiteNetLib#254]
Hey there,
is there any way to get the peer IPv4 address or let the peer connect with IPv4 instead of IPv6?
EndPoint.Host stores the IPv6, the application I'm using only supports
IPv4 until now, thus I can't work with the incoming peers correctly.
Thanks for the help!

**Comment by xmedeko** [comment]
You can use `DISABLE_IPV6` compile flag.

**Comment by SokratesMir** [comment]
I maybe missed to say that I am working in a normal Visual Studio 2017 environment.
As far as I didn't miss anything, there is no option for me to use any specific compile flags for my project.
Still thanks for the answer.

What I achieved so far is, that by giving the client a IPv4 address to connect, the client will also connect via his IPv4 address and will not use his IPv6.
If there would still be a solution with which I can directly tell the client to always connect via his IPv4 that'll be nice.

**Comment by xmedeko** [comment]
@SokratesMir Use sources not DLL (NuGet) - it's recommended. Then in VS 2017 go to project _Project Properties > Build > General > Conditional compilation symbols_. Separate more symbols by semicolon, e.g.: `NETCORE;DISABLE_IPV6`

**Comment by SokratesMir** [comment]
Thank you very much!
This is closed then
