### ISSUE TITLE
"Value does not fall within expected range" if set ReuseAddress to TRUE

### ISSUE THREAD

**Issue by quabug** [RevenantX/LiteNetLib#256]
Information about bug or feature

```csharp
var net = new NetworkManager(this);
net.ReuseAddress = true;
net.Start();
```

**Library version**: de15ad9a7cc757ca9a47e6684defa56a653f7590

**Framework**: Unity .net 4.x

**OS**: Windows

throw at this line: https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/NetSocket.cs#L154
naughty quick fix: https://github.com/quabug/LiteNetLib/blob/master/LiteNetLib/NetSocket.cs#L151

**Comment by RevenantX** [comment]
Thanks for report!
