### ISSUE TITLE
Error	CS1061	'EventBasedNetListener' does not contain a definition for 'ConnectionRequestEvent' 

### ISSUE THREAD

**Issue by NothingFaceX** [RevenantX/LiteNetLib#257]
The example code is obsoleted and it's not working , I just got the package right now and nothing working ! 

> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1061	'EventBasedNetListener' does not contain a definition for 'ConnectionRequestEvent' and no extension method 'ConnectionRequestEvent' accepting a first argument of type 'EventBasedNetListener' could be found (are you missing a using directive or an assembly reference?)	
> 
>  
> I fixed it with changing to new NetManager(listener);
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1729	'NetManager' does not contain a constructor that takes 1 arguments	
> 
> 

**But how can I fix the first error ?**

**Errors in Clients Example :**

> error CS1501: No overload for method 'Connect' takes 3 arguments
>  error CS1593: Delegate 'EventBasedNetListener.OnNetworkReceive' does not take 3 arguments

```csharp
// EXAMPLE IN MAIN PAGE!
```

**Library version**: last version from nuget

**Framework**: .Net 4.7

**OS**: Windows

**Comment by RevenantX** [comment]
@NothingFaceX stable branch (0.7) code and examples https://github.com/RevenantX/LiteNetLib/tree/0.7
This information on main page.
