### ISSUE TITLE
p2p чат

### ISSUE THREAD

**Issue by jenokizm** [RevenantX/LiteNetLib#26]
привет уважаемый автор! в универе для учебных целей есть задача сделать п2п чат лишь на двоих, но никакими станами и т.д. не могу справится с публичными динамическими адресами типа билайн, рт и т.д. Также пробовал вашу либу тоже не удалось( подскажите предназначена ли она для обхода таких вот глабальных натов, если нет то что посоветуете?

**Comment by RevenantX** [comment]
P2P чат любого вида (tcp, udp) вряд-ли будет работать через мобильную сеть без HolePunch сервера (stun). И вроде даже с HolePunch не всегда будет работать. Т.к. поидее GPRS/3G используют симметричный NAT который адекватным способом почти не обходится.
Хотя когда я тестировал эту библиотеку через 4G то всё работало (в Эстонии).
Короче надо сперва проверить будет ли работать HolePunch как в этом примере https://github.com/RevenantX/LiteNetLib/blob/master/LibSample/HolePunchServerTest.cs
А если не будет, то нужен туннельный сервер. Который просто будет пересылать пакеты от одного пира-другому

**Comment by jenokizm** [comment]
спасибо за ответ! да печаль я тоже самое гуглил насчет симметричного. а как же тогда работают загрузки торрентов или биткойны?
Ваш тестовый метод запустил (билайн 3G), и помойму кстати он правильно отработал! вот вывод:

> Press ESC to quit
Wait peer created. i(10.193.45.92:50323) e([::1]:50323)
Wait peer found, sending introduction...
host - i(10.193.45.92:50323) e([::1]:50323)
client - i(10.193.45.92:50324) e([::1]:50324)
Success C1. Connecting to C2: 10.193.45.92:50324
Success C1. Connecting to C2: [::1]:50324
Success C2. Connecting to C1: 10.193.45.92:50323
Success C2. Connecting to C1: [::1]:50323
PeerConnected: 10.193.45.92:50323
PeerConnected: 10.193.45.92:50324

**Comment by RevenantX** [comment]
Торренты и биткионы работают между большим количеством пиров (а не 1 на 1). На телефоне это работает когда один или больше из пиров не за NAT или с проброшеным портом.
