### ISSUE TITLE
hole punch got socket exception 10052 while peer behinds Mobile network NAT

### ISSUE THREAD

**Issue by vollkornbrot** [RevenantX/LiteNetLib#260]
Thank you for this useful library

I found that if any peer hole punches under a mobile network, 
it will get socket exception 10052, and hole punch failed
but if I increase the _socket.Ttl to 16,  it works well.

```csharp
(In NatPunchModule.cs)
private void HandleNatIntroduction(NetDataReader dr)
{
   ... (omitted)
   if (hostByte == HostByte)
   {
       _socket.Ttl = 2;   // <<<<< here
       _socket.SendTo(writer.Data, 0, writer.Length, remoteExternal, ref errorCode);
       _socket.Ttl = NetConstants.SocketTTL;
    }
    ... (omitted)
}
```

**Library version**: [commit id (b86f2884eccdf92dd50ee65d8c04887b4e1891ff) 

**Framework**: [NET Framework 3.5]

**OS**: [Win10]

**Comment by RevenantX** [comment]
@vollkornbrot thanks for report! I will try to investigate mobile network situation. What about using max TTL(255, NetConstants.SocketTTL)? Does is works?

**Comment by vollkornbrot** [comment]
use NetConstants.SocketTTL 225, works well too.

**Comment by RevenantX** [comment]
@vollkornbrot this is strange) Because socket TTL - 2 this is cheat for some routers)

**Comment by snoopyuj** [comment]
Same problem here. Have no idea what causes this problem.

**Comment by snoopyuj** [comment]
I found a solution from [here](https://stackoverflow.com/questions/10332630/connection-reset-on-receiving-packet-in-udp-server)

I added the code into NetSocket.BindSocket() method:
`private bool BindSocket(Socket socket, IPEndPoint ep, bool reuseAddress)
        {
            //Setup socket
            const int SIO_UDP_CONNRESET = -1744830452;
            byte[] inValue = new byte[] { 0 };
            byte[] outValue = new byte[] { 0 };
            socket.IOControl(SIO_UDP_CONNRESET, inValue, outValue);
            ...`

But still don't know how it happened.

**Comment by RevenantX** [comment]
this fixed already in https://github.com/RevenantX/LiteNetLib/commit/df368c04d98960ab591acd7e505fc204ffba6311
