### ISSUE TITLE
about remote connect

### ISSUE THREAD

**Issue by onurigdi** [RevenantX/LiteNetLib#265]
i am trying basic connection. its working on local ip. when i run my server built exe on a server. i can not reach server exe by domain name or ip. i defined UDP ports on firewall as allow. but still not connect.

server code

        _dataWriter = new NetDataWriter();
        _netServer = new NetManager(this);
        _netServer.Start(5000);
        _netServer.DiscoveryEnabled = true;
        _netServer.UpdateTime = 15;

client code 
        _netClient = new NetManager(this);
        _netClient.Start();
        _netClient.UpdateTime = 15;
        _netClient.Connect("domain or ip adress of my server", 5000, "sample_app");

**Framework**: unity
**OS**: windows

**Comment by RevenantX** [comment]
@onurigdi do you forwarded ports on router?

**Comment by onurigdi** [comment]
i changed the ports which i try to connect. it worked well now. may be it was blocked by an other application. i couldnt find why it happened. its working now :)
