### ISSUE TITLE
Why the local IP is “169.254.68.213”

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#27]
Press ESC to quit
Wait peer created. i(169.254.68.213:58084) e([::1]:58084)
Wait peer found, sending introduction...
host - i(169.254.68.213:58084) e([::1]:58084)
client - i(169.254.68.213:58085) e([::1]:58085)
Success C1. Connecting to C2: [::1]:58085
Success C2. Connecting to C1: [::1]:58084
PeerConnected: [::1]:58084
PeerConnected: [::1]:58085

**Comment by QiuBuZai** [comment]
Run the “HolePunchServerTest”

**Comment by QiuBuZai** [comment]
Is not in the case of multi-card will be wrong？

**Comment by RevenantX** [comment]
What OS and network type? Android and 3G/4G?

**Comment by QiuBuZai** [comment]
PC the “HolePunchServerTest”

**Comment by QiuBuZai** [comment]
This project has not considered the situation of multi-network card?

**Comment by RevenantX** [comment]
Ehm. This feature is not implemented. It automatically selects first network card. I can try add selection. But this feature will be very platform dependent.

**Comment by QiuBuZai** [comment]
Through my test, this problem does not make LAN P2P failure.

**Comment by RevenantX** [comment]
#43 duplicate
