### ISSUE TITLE
Method to GetPeerById()

### ISSUE THREAD

**Issue by mkgn** [RevenantX/LiteNetLib#271]
Information about bug or feature
Probably a new feature or some input about how it can be done with current framework.

**Library version**: release version (0.7.7.1)]

**Framework**: Server: .net core, client unity .NET 4.5

**OS**: Server Windows, client: android and hopefully iOS

Isn't it good to add a method to get the peer when the id is passed? As of now we do it by maintaining our own dictionary. But I think this is a needed small feature?

**Comment by RevenantX** [comment]
done
