### ISSUE TITLE
In 0.8.2-beta there is no NetDataReader reader.Data

### ISSUE THREAD

**Issue by fzdravko** [RevenantX/LiteNetLib#272]
In 0.8.2-beta how to get whole message, there is no NetDataReader reader.Data like in 0.7.....

**Library version**: [version (0.8.2-beta)]

**Framework**: [dotnetcore]

**OS**: [Windows]

**Comment by RevenantX** [comment]
@fzdravko there is dataReader.RawData and dataReader.UserDataOffset and dataReader.UserDataSize
