### ISSUE TITLE
[Question]keep connection when client ip change?

### ISSUE THREAD

**Issue by lordoffox** [RevenantX/LiteNetLib#273]
If client change it's ip address, when 4G switch to WIFI, does LiteLib keep connection instead of disconnect the connection?

**Comment by RevenantX** [comment]
@lordoffox if IP address changed then you will get disconnect.

**Comment by lordoffox** [comment]
how long to receive disconnect notify?

**Comment by lordoffox** [comment]
quic can keep connection,  it improve the mobile rudp quality
mobile change ip in many case: 4g -> wifi, wifi -> 4g, 4g1 -> 4g2
is any change LiteNetLib can keep connection?

**Comment by RevenantX** [comment]
@lordoffox you can make this on application level if you can 100% identify connected peer.

**Comment by lordoffox** [comment]
yes i can know the identify by peer
but i can't control the resend data manager by LiteNetLib
so application need to know which data is send succeed to remote, by at this time, disconnect event received, if reconnect succeed , maybe some duplicate data while send to new peer.

**Comment by RevenantX** [comment]
@lordoffox this will be fixed with #67
