### ISSUE TITLE
GC

### ISSUE THREAD

**Issue by NVentimiglia** [RevenantX/LiteNetLib#274]
Information about bug or feature
- On the latest from master (Dec 1, 2018) (690f8c435f8c28adb0a892648ccdf6985b970f13 [690f8c4])
- Running clients and server inside unity, windows
- Noticed some garbage being allocated when testing.
- Would like remove this allocation, is possible. 

![image](https://user-images.githubusercontent.com/125889/50066397-5a08c580-0170-11e9-82ad-21cecf465346.png)

**Comment by RevenantX** [comment]
@NVentimiglia this allocations is ok. After constructing packets will be pooled and there will be no more allocations.

**Comment by NVentimiglia** [comment]
@RevenantX I am seeing this every frame. The code is an echo test against some bytes.

I see #119, is there a branch for this beta that I can pull from, or do I need to extract the project as a zip ?

**Comment by RevenantX** [comment]
@NVentimiglia this already in master and in 0.8.2 beta version

**Comment by NVentimiglia** [comment]
@RevenantX just to clarify, the 48 bytes of GC every frame is expected behavior for an echo test (with 1 active message per client max) ?

**Comment by RevenantX** [comment]
@NVentimiglia i will test your behavior. This is not expected behavior because there is pooling.

**Comment by RevenantX** [comment]
@NVentimiglia just tested in unity 2018.2.6f1 with deep profile - and there is no any allocations

**Comment by RevenantX** [comment]
@NVentimiglia https://i.imgur.com/98iR0G1.png

**Comment by NVentimiglia** [comment]
Cool, must be something on my end, I'll double check my code.
