### ISSUE TITLE
REQUESTED Feature: DTLS optional / Cert Login for Hole Punch Server

### ISSUE THREAD

**Issue by seppy87** [RevenantX/LiteNetLib#275]
Hallo,

I like your lib since it has also UDP Hole Punching Functionality. My question is: Is it possible to add DTLS if someone wants it? Atm I am encrypting the json String I am sending. I mean with Optional that you can switch it on or off. Not a Eat or Die Function

Does the Connectionkey Matter in the connection to the Hole Punch Server? I would like to make it harder to misuse the server. I would like to implement a way for login like OpenVPN with created Certs.

Greetings

**Comment by RevenantX** [comment]
@seppy87 there is example of hole punch server. You can make it in almost any way you want. (with encryption on your side)
