### ISSUE TITLE
"bool[]" type missing on NetSerializer on 0.8.2 beta

### ISSUE THREAD

**Issue by Kamiperat0r** [RevenantX/LiteNetLib#278]
Unless I am mistaken, the management of "bool []" is missing in NetSerializer.cs.

Adding the following code in the "Private StructInfo RegisterInternal <T> ()" method seems to solve the problem:
`else if (propertyType == typeof(bool[]))
                {
                    var setDelegate = ExtractSetDelegate<T, bool[]>(setMethod);
                    var getDelegate = ExtractGetDelegate<T, bool[]>(getMethod);
                    info.ReadDelegate[i] = reader => setDelegate((T)info.Reference, reader.GetBoolArray());
                    info.WriteDelegate[i] = writer => writer.PutArray(getDelegate((T)info.Reference));
                }`

**Comment by RevenantX** [comment]
@Kamiperat0r this already in master branch

**Comment by RevenantX** [comment]
https://github.com/RevenantX/LiteNetLib/commit/690f8c435f8c28adb0a892648ccdf6985b970f13

**Comment by Kamiperat0r** [comment]
@RevenantX Indeed. Thank you.
