### ISSUE TITLE
Add a callback where we can modify packets

### ISSUE THREAD

**Issue by rikimaru0345** [RevenantX/LiteNetLib#279]
## Feature Request

The idea is that we're able to add/change data before its being sent/received.

### Use-Cases:
- Payload Encryption
Only possible for reliable channels, since the encryption state changes with the input (wouldn't be a very safe encryption if the key doesn't mutate with the input now, would it lol).
Which means every channel has its own callback (good idea to combine this with adding channels that each have their own `DeliveryMethod` and sequence, just add one byte to signify the channel, done).

- Packet Checksums
Adding a checksum to each packet would reduce the chances of getting data that's accidentally by some faulty hardware between sender and receiver. Obviously it won't help against hackers at all since they will simply inject their packets earlier (as in calling the same Send() method that the application is using, or just emulate the checksum), but that's not a goal anyway.

**Comment by NVentimiglia** [comment]
Why can't we just encrypt the data and then send it? Likewise, why can't we decrypt the payload in our receive handler?

**Comment by rikimaru0345** [comment]
From the top of my head there are a few reasons:

- For example I have a networking system that calls Send from all over the place to do different things. Parts are even auto generated, other parts are in a different lib,...
So if I would want to add encryption I'd have to go in everywhere and change stuff. 
It's a common thing to have a callback for this purpose in networking libraries because of that. 


- LiteNetLib can merge packets, or split large ones and reassemble them. The actual udp packets that are being sent can contain a fraction of a user packet, one packet, or multiple packets (or multiple + a fraction of another one...)
So adding additional data like a checksum may change how many packets are actually sent... 



If you want more reasons, I'm pretty sure you will find additional ones if you take a look at some other networking libraries.

**Comment by moien007** [comment]
@rikimaru0345, Your use case for encryption is wrong, since you cannot use **stateful** encryption at packet level. As you mentioned before, this kind of encryption only works for reliable-ordered channels.

My suggestion for this issue is a breaking change. That is, change `NetSocket` class to an (public) abstract class which contains:

- `OnReceive`event, which LNB will register its packet handler callback to it
- `Send` method, which LNB will use it to send packets 

And then we define `NetSystemSocket` class, which inherits `NetSocket` and utilizes `System.Net.Sockets.Socket`.

**Comment by rikimaru0345** [comment]
> Yuck. Write a proxy and get some control over your data flow.

Yes, that's the plan. At the moment things are still somewhat in motion. Once feature requests have died down a little and the API of my project really crystallizes into something that I can be reasonably sure won't have any more large changes, I'll do that.

**Comment by RevenantX** [comment]
@rikimaru0345 
>Packet Checksums

Big packets (merged and fragmented) - almost in all cases in size of MTU so you cannot add checksum by using some external method. And with encryption there is same thing.

**Comment by RevenantX** [comment]
@rikimaru0345 there already separate feature request for checksums - so i will add them later. And encryption is better be handled on user side (and there is rare needs for this). So yes this feature request will be rejected.

**Comment by moien007** [comment]
@RevenantX 
Justifying @rikimaru0345 is not enough to close the feature request. 
This feature adds a useful abstraction to LNB. 
Please provide some reasons why this feature is harmful to LNB. (performance penalties.. etc)

**Comment by RevenantX** [comment]
@moien007 sure if a fragment (in reliable channel) lost or corrupted - library will resend that. But if you add some data to that fragment that already in size of MTU - you will not able to send it in almost any case. How you can disagree with UDP implemenation.
