### ISSUE TITLE
Issues with ReadAllPackets?

### ISSUE THREAD

**Issue by ahackitdev** [RevenantX/LiteNetLib#28]
This is possibly just an error on my side, but I can't seem to get Packet subscribing and receiving to work. I can send/receive normal data using Reader/Writer, but can't seem get to get serialization,packet subscribing to work.

Server Code
`           
            netSerializer = new NetSerializer();
            netSerializer.Subscribe<PongPacket>(OnPongPacketRecieved);

        private void OnPongPacketRecieved(PongPacket pPacket)
        {     
           Console.WriteLine("[Server] RecievedPacket:\n" + pPacket);
        }

        public void NetworkRecieveEvent(NetPeer peer, NetDataReader dataReader)
        {
                Console.WriteLine("[Server] recieved data, processing...");
                netSerializer.ReadAllPackets(reader);

        }
`
Client Code
`
       public  void Update(KeyboardState keyboardState)
        {

            if (ConnectionMade)
            {
                clientsPaddle.Update(keyboardState);
                writer.Reset();
                PongPacket packet = new PongPacket();
                packet.PacketID = "Paddle";
                packet.Y = clientsPaddle.Position.Y;         
                clientsPeer.Send(serializer.Serialize(packet), SendOptions.ReliableOrdered);
                Console.WriteLine("Sending Packet to Server" + writer.Data);

            }
            client.PollEvents();
        }
`

Struct
`    struct PongPacket
    { 
        public string PacketID { get; set; }
        public float Y { get; set; }
    }
`

Any thoughts? Like I mentioned sending the same data not in a Struct and not serializing it works fine. Maybe I am missing something? Worked pretty closely with the examples.

**Comment by ahackitdev** [comment]
From Client Side Console Log is:
ID:Paddle Y:180Bytes22
Sending Packet to ServerSystem.Byte[]

From Server Sides it is:
[Server] recieved data, processing...
Sending Packet to Client

The ouput should be 
[Server] recieved data, processing...
Sending Packet to Client

**Comment by RevenantX** [comment]
Very strange that there is no exceptions. Can you give me minimal code with problem. I will try to reproduce and fix this.

**Comment by ahackitdev** [comment]
Server Code: 
`
            serverListener = new EventBasedNetListener();
            serverListener.PeerConnectedEvent += ClientConnectedEvent;
            serverListener.NetworkReceiveEvent += NetworkRecieveEvent;
            server = new NetManager(serverListener, 2, "PongMultiplayer");
            server.Start(9050);
            reader = new NetDataReader();
            writer = new NetDataWriter();
            netSerializer = new NetSerializer();
            netSerializer.Subscribe<PongPacket>(OnPongPacketRecieved);

        private void OnPongPacketRecieved(PongPacket pPacket)
        {     
           Console.WriteLine("[Server] RecievedPacket:\n" + pPacket);
        }

        public void ClientConnectedEvent(NetPeer peer)
        {
            Console.WriteLine("We got connection: {0}", peer.EndPoint);
            writer.Put("Hello Client");
            peer.Send(writer, SendOptions.ReliableOrdered);
            serversPeer = peer;
            ConnectionMade = true;

        }

        public void NetworkRecieveEvent(NetPeer peer, NetDataReader dataReader)
        {
            if(dataReader.GetType() == typeof(string))
            {
                Console.WriteLine("We got: {0}", dataReader.GetString(100));
            }
            else
            {
                Console.WriteLine("[Server] recieved data, processing...");
                netSerializer.ReadAllPackets(reader);
           
            }
        }
`

ClientCode
`
            clientListener = new EventBasedNetListener();
            clientListener.NetworkReceiveEvent += NetworkRecieveEvent;
            clientListener.PeerConnectedEvent += ServerConnectedEvent;
            client = new NetManager(clientListener, "PongMultiplayer");
            client.Start();
            client.Connect("localhost", 9050);
            writer = new NetDataWriter();
            reader = new NetDataReader();
            serializer = new NetSerializer();
            Console.WriteLine("Client Started");

       public  void Update(KeyboardState keyboardState)
        {


            if (ConnectionMade)
            {
                clientsPaddle.Update(keyboardState);
                writer.Reset();
                PongPacket packet = new PongPacket();
                packet.PacketID = "Paddle";
                packet.Y = clientsPaddle.Position.Y;
                clientsPeer.Send(serializer.Serialize(packet), SendOptions.ReliableOrdered);
                Console.WriteLine("Sending Packet to Server" + writer.Data);

            }


            client.PollEvents();

        }
`

Struct
`
    struct PongPacket
    { 
        public string PacketID { get; set; }
        public float Y { get; set; }
    }
`

I think this should be all the code to recreate the problem - I removed most of everything that was related to updating the game. On the creation of the packet you could spoof in any string/float. 

I have tested that Struct is created accurately and that after serialization there is an actual bit length(22), but once Server Gets NetworkEvent and readsPacket. OnPacketRecieved never gets called.

Let me know if there is anything else you need, I bet this is a small issue that I missed but I cant find it.

**Comment by ahackitdev** [comment]
Oh - I misunderstood that implementation - I thought that returned the type of the nextRead.

I'll remove it, although I believe it is unrelated.

**Comment by ahackitdev** [comment]
I changed around what I am showing I am writing. It does look like Serialization is working and I am getting a byte length of 22 before sending.

`
                clientsPaddle.Update(keyboardState);
                writer.Reset();
                PongPacket packet = new PongPacket();
                packet.PacketID = "Paddle";
                packet.Y = clientsPaddle.Position.Y;
                byte[] bytes = serializer.Serialize(packet);
                Console.WriteLine("Sending Packet to Server " + bytes.Length);
                clientsPeer.Send(bytes, SendOptions.ReliableOrdered);
`

**Comment by RevenantX** [comment]
```  
public void NetworkRecieveEvent(NetPeer peer, NetDataReader dataReader)
    {
        if(dataReader.GetType() == typeof(string))
        {
            Console.WriteLine("We got: {0}", dataReader.GetString(100));
        }
        else
        {
            Console.WriteLine("[Server] recieved data, processing...");
            netSerializer.ReadAllPackets(reader);
       
        }
    }
```
Here mistake
```netSerializer.ReadAllPackets(reader);``` correct to ```netSerializer.ReadAllPackets(dataReader);```

**Comment by ahackitdev** [comment]
Damn it...... That was it.... I appreciate the help so much. I love the library and looking forward to using it more.
`

        private void OnPongPacketRecieved(PongPacket pPacket)
        {     
           Console.WriteLine("[Server] RecievedPacket:\n" + pPacket.PacketID);
           clientsPaddle.Y = pPacket.Y;
        }

        public void NetworkRecieveEvent(NetPeer peer, NetDataReader dataReader)
        {

                Console.WriteLine("[Server] recieved data, processing...");
                netSerializer.ReadAllPackets(dataReader);

        }
`
Any other call outs from what you see? If not - appreciate all the help!

**Comment by RevenantX** [comment]
Use resharper, Luke :)
