### ISSUE TITLE
NtpRequest fails for IPv6 in Unity on Windows

### ISSUE THREAD

**Issue by xmedeko** [RevenantX/LiteNetLib#283]
NtpRequest fails for "time.google.com" on Windows when IPv6 network is available. Code is like:
```c#
IPAddress serverAddress = LiteNetLibUtils.ResolveAddress("time.google.com");
NtpRequest.Create(serverAddress, NtpResponseReceived)
```
I am sorry I have no detail, I do not have access to the IPv6 network at the moment. (Will try to get some details later.) A user has reported, it goes OK when he has switched off the IPv6 support on the LAN card properties.

**Library version**: 0.8.2-beta
**Framework**: Unity
**OS**: Windows

**Update:** Cannot simulate it, so unfortunately have no details. But users reports that disabling IPv6 by `DISABLE_IPV6` (and the latest master 4754c37) solves the problem.

**Comment by RevenantX** [comment]
Fixed :)
