### ISSUE TITLE
NetworkErrorEvent not getting called

### ISSUE THREAD

**Issue by Damianu** [RevenantX/LiteNetLib#284]
Information about bug or feature

listener.NetworkErrorEvent  isn't getting called, instead error is getting thrown 
```
System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=No such host is known
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

So when client enters IP that isnt valid or server isnt started etc there is no way of catching it. (calling .Connect() in trycatch doesnt catch it either)

**Library version**:  master branch
**Framework**: dotnetcore

**OS**:  Windows

**Comment by Damianu** [comment]
Actually I realised it's just VS catching the exception too soon, wouldn't it be better to catch that exception and pass it to some callback same way messages are done?

**Comment by RevenantX** [comment]
@Damianu done
