### ISSUE TITLE
Possibility to give a ArraySegment<byte> to send

### ISSUE THREAD

**Issue by MichalPetryka** [RevenantX/LiteNetLib#288]
**Information about feature**
Adding possibility to send ArraySegments would be really useful in places which try to avoid as many allocations as it is possible (example: voice chat in unity)

**Library version**: n/a

**Framework**: n/a

**OS**: n/a

**Comment by RevenantX** [comment]
@MichalPetryka you can send ArraySegment using Array, Offset and Count properties.
