### ISSUE TITLE
Warning in Unity 2018.2.17f1

### ISSUE THREAD

**Issue by MichalPetryka** [RevenantX/LiteNetLib#292]
Unity 2018.2 with .net 4.x gives a warning that one thing is deprecated
![image](https://user-images.githubusercontent.com/35800402/52919054-70610800-32fe-11e9-987c-6938f78271d7.png)

**Library version**: master

**Framework**: Unity

**OS**: n/a

**Comment by RevenantX** [comment]
@MichalPetryka this is ok, because newer OSSuportsIPv6 doesn't work in some situations on some platforms (ios/android)

**Comment by MichalPetryka** [comment]
That has been fixed in 2018.2 https://issuetracker.unity3d.com/issues/android-socket-dot-ossupportsipv6-throwing-exception-on-android
