### ISSUE TITLE
Multicast or broadcast support

### ISSUE THREAD

**Issue by msalai** [RevenantX/LiteNetLib#298]
Does your library supports Multicast sending or perhaps Broadcasting instead of sending separate packet to each peer?

**Comment by RevenantX** [comment]
@msalai there is SendDiscoveryRequest that sends broadcasts for IPv4 and Multicast (in broadcast-like mode) for IPv6. Thats all.

**Comment by msalai** [comment]
But is there a way to send it reliably (DeliveryMethod.ReliableOrdered)?

**Comment by RevenantX** [comment]
@msalai no.

**Comment by RevenantX** [comment]
@msalai you can send packets to peers using netManager.SendToAll( ... )

**Comment by msalai** [comment]
yes, but it will send one by one and for big data and high number of clients it will be very slow.

**Comment by RevenantX** [comment]
@msalai well broadcast work only in LAN, and there is no other way to send broadcast reliably.

**Comment by msalai** [comment]
yes, I need it for LAN only. It would be great to have option like reliable multicast or broadcast. I know it is not an easy task, but I am just throwing suggestions.

**Comment by RevenantX** [comment]
@msalai show me libraries with reliable broadcast. Because how this can work if reliability works by resending data, and you need to know which peer received data to resend.

**Comment by msalai** [comment]
I could find one in java/c++ called aeron (https://github.com/real-logic/aeron) but it requires some driver which is not good in my opinion. To know which peer received data, you would need to keep some kind of list on server side in which there will be confirmations for each sent packet. Crazy, but possible for sure. But that is just my guess - I am not a network expert.

**Comment by RevenantX** [comment]
@msalai well i'm not suprised that is used some sort of hack (driver)

**Comment by msalai** [comment]
driver is for other purpose and it is only called "driver", it is not real driver in windows or anything like it. It is described as following:

"The mediadriver is a separate process that provides a means to demux and provide buffers of data for Aeron to process from various transmission media. It decouples the means of data transmission from protocol processing. There can be many different media drivers for various media, to take advantage of different optimisations (such as Linux epoll and sendmmsg/recvmmsg)."

Reliable multicast is not that hard to achieve (I have working solution for certain task made by one of my freelancers) but integrating it into your library is out of my scope.

**Comment by RevenantX** [comment]
@msalai well this library focused on games and it must be 'Lite' network library without of tons unused features :) If you have soulution - use it)
