### ISSUE TITLE
Weird ID generation

### ISSUE THREAD

**Issue by MichalPetryka** [RevenantX/LiteNetLib#301]
I'd expect IDs to be the lowest available number, but spamming connect and disconnect with one client gives results like this:
![alt text](https://media.discordapp.net/attachments/403321276153987072/556930822582698003/unknown.png "1")
This would allow us to use an array to get peer by id if we have max connections instead of using a dictionary to do that.
**Library version**: last commit

**Framework**: Unity

**OS**: n/a

**Comment by MichalPetryka** [comment]
Expected behaviour would be that it would always give 0

**Comment by RevenantX** [comment]
@MichalPetryka this is normal behaviour
