### ISSUE TITLE
SendUnconnectedMessage() size limitation

### ISSUE THREAD

**Issue by Sofaisme** [RevenantX/LiteNetLib#302]
Hi, I tried to send 40KB data by using SendUnconnectedMessage(), but the NetManager didn't receive any data. If I send 2KB data packet, it works. Does SendUnconnectedMessage() has size limitation? Thank you.

**Library version**: [commit id (9f2a1d1a8244510d9ec502cc002bfdddba666d09) or release version (0.7.7.1)]
0.8.2 beta
**Framework**: [Mono, Unity, dotnetcore, .NET Framework]
Unity: 2017.4.22f1
scripting runtime version: .Net 3.5
Api compatibility level: .Net 2.0
**OS**: [Linux, Windows, etc]
Windows Win10 x64

**Comment by RevenantX** [comment]
@Sofaisme yes it has limitation of MTU (Maximum Transfer Unit). Best maximum size for that packet is 507 bytes for all cases. (MTU(576) - UdpHeaderSize(68) - LiteNetLibHeader(1))
