### ISSUE TITLE
Linux "SocketException: Protocol option not supported"

### ISSUE THREAD

**Issue by Alloc86** [RevenantX/LiteNetLib#303]
With the current release we get this exception in the log when starting the server:
> [B]Bind exception: SocketException: Protocol option not supported
at SetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, Boolean optionValue)
at LiteNetLib.NetSocket.BindSocket (Socket socket, IPEndPoint ep, Boolean reuseAddress), errorCode: ProtocolOption

And (probably at the same time) Unity writes this to stdout:
> System.Net.Sockets.SocketOptionName 0x1b is not supported at IPv6 level

**Library version**: release version 0.8.3

**Framework**: Unity 2018.2.20, .NET 2 backend

**OS**: Linux

**Comment by RevenantX** [comment]
@Alloc86 are you using library sources or precompiled dll?

**Comment by Alloc86** [comment]
Sources from the release zip (i.e. https://github.com/RevenantX/LiteNetLib/archive/v0.8.3.zip ).

**Comment by RevenantX** [comment]
@Alloc86 looks like unity bug (there are some fixes in 2018.3) so you can disable IPv6 for now by enabling DISABLE_IPV6

**Comment by Alloc86** [comment]
Ok, thanks :)
Maybe that could be added as a conditional on UNITY_2018_3_OR_NEWER so others don't run into the same issue.

Actually we plan to update ourselves to 2018.3 or even 2019.1 so that shouldn't hurt a lot anyway :)

**Comment by RevenantX** [comment]
@Alloc86 well this is just log message. It must work after this error happens.

**Comment by Alloc86** [comment]
Indeed it does, still a nasty log message ;)
