### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by iamkisly** [RevenantX/LiteNetLib#305]
Hello. I have two questions:

1. How many connections including active can the server support? I tried to implement a datagram server using dotnetty and was faced with the fact that their implementation of the UDP server works only in single-threaded mode. 
2. Are you considering the inclusion of support for the header from the new network unit? They use a 32 bit header.

https://github.com/Unity-Technologies/multiplayer/blob/b7c2798078ab2408caf232b8775aa6ff9ac71ccd/com.unity.transport/Runtime/NetworkProtocols.cs#L25

**Library version**: [commit id (9f2a1d1a8244510d9ec502cc002bfdddba666d09) or release version (0.7.7.1)]

**Framework**: Unity, dotnetcore

**Comment by RevenantX** [comment]
@iamkisly 
1) depends on server hardware and game logic. Some games works with 1000 clients, some can only with 100 at maximum.
2) No
