### ISSUE TITLE
feature MultiDimensional arrays

### ISSUE THREAD

**Issue by mikaelssen** [RevenantX/LiteNetLib#306]
Information about feature request

I may be an idiot, but this lib does exactly what i was looking for, but when ever a class or anything has a multi dimensional array, it simply errors out and crashes. I checked the source code and it's not supported, and I'm kinda dumbfounded on how / if i can add my own support for it

Tried to do some snippets of code and what not, but i can't seem to get it to work. 
There may be a simple solution but i'm on the "use hours to solve an issue that's probably obvious" stage..

```csharp
        public class Chunk : INetSerializable
	{
		public int Width { get; set; }
		public int Height { get; set; }
		public int[,] Chunk_Map_data { get; set; } //this is the part that crashes everything, removing this fixes it, changing it to a one dimensional array is the only solution i can come to think of, but that ruins the beauty of this dimensional array.
		public int x { get; set; }
		public int y { get; set; }

		public Chunk()	{}

                void INetSerializable.Serialize(NetDataWriter writer)
		{
			writer.Put(Width);
			writer.Put(Height);
			writer.Put(x);
			writer.Put(y);

			Chunk_Map_data = new int[Width, Height];

			//This din't work
			for (int x = 0; x < Width; x++)
			{
				for (int y = 0; y < Height; y++)
				{
					writer.Put(Chunk_Map_data[x, y]); //this can be a single for loop, but this is also an example
				}
			}
		}
               SNIP    deserialise is basically the same.

```

**Library version**: [Master via DLL download as nuget is not on beta]

**Framework**: [ .NET Framework core]

**OS**: [ Windows]

**Comment by MichalPetryka** [comment]
Maybe try with a jagged array?

**Comment by mikaelssen** [comment]
No, yea, din't see that at all, haha @RevenantX 
whelp, that fixed it, wasted a good amount of time, Thanks 👍
