### ISSUE TITLE
Hole punch doesn't work if one of client use 3G/4G

### ISSUE THREAD

**Issue by sangvublogic** [RevenantX/LiteNetLib#307]
Hole punching for one of client use 3G/4G not successful

Thanks

**Comment by RevenantX** [comment]
@sangvublogic as i know - 3G/4G doesnt work well with hole punching at all in any cases. So there can be just impossible thing.

**Comment by sangvublogic** [comment]
@RevenantX thanks for your answer

**Comment by sangvublogic** [comment]
@RevenantX So how i can check when client is under Symmetric NAT or hole punch fail. Because there aren't any event to catch when client cannot establish connection

**Comment by RevenantX** [comment]
@sangvublogic well - after your connection failed from both sides - this is sign that you under Symmetric NAT. In this case you can easily create UDP tunnel.

**Comment by sangvublogic** [comment]
@RevenantX thanks you very much for your support
