### ISSUE TITLE
If two clients in an internal network will produce two hole

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#31]
private void HandleNatIntroduction(NetDataReader dr)
        {
            // read intro
            byte hostByte = dr.GetByte();
            NetEndPoint remoteInternal = dr.GetNetEndPoint();
            NetEndPoint remoteExternal = dr.GetNetEndPoint();
            string token = dr.GetString(MaxTokenLength);

            NetUtils.DebugWrite(ConsoleColor.Cyan, "[NAT] introduction received; we are designated " + (hostByte == HostByte ? "host" : "client"));
            NetDataWriter writer = new NetDataWriter();

            // send internal punch（the first time）
            writer.Put(hostByte);
            writer.Put(token);
            _netBase.SendRaw(NetPacket.CreateRawPacket(PacketProperty.NatPunchMessage, writer), remoteInternal);
            NetUtils.DebugWrite(ConsoleColor.Cyan, "[NAT] internal punch sent to " + remoteInternal);

            // send external punch（the second time）
            writer.Reset();
            writer.Put(hostByte);
            writer.Put(token);
            _netBase.SendRaw(NetPacket.CreateRawPacket(PacketProperty.NatPunchMessage, writer), remoteExternal);
            NetUtils.DebugWrite(ConsoleColor.Cyan, "[NAT] external punch sent to " + remoteExternal);
        }

**Comment by QiuBuZai** [comment]
If I only use the public network ip hole will be a problem?

**Comment by RevenantX** [comment]
Internal punch used for better connections if users in one local network. But if they not behind symmetric NAT - public hole will work.

**Comment by QiuBuZai** [comment]
If they behind symmetric NAT,Can I use local ip to punch holes?
I'm hard to do this test。

**Comment by RevenantX** [comment]
If they behind symmetric nat, but in one local network - local punch will work.

**Comment by QiuBuZai** [comment]
Your answer helped me a lot
