### ISSUE TITLE
peer.Send() keeps everything in memory

### ISSUE THREAD

**Issue by kurse** [RevenantX/LiteNetLib#310]
I'm using the LiteNetLib to send big amounts of data via UDP (I need low latency so TCP is not possible). I get everything to work up until the peer.Send() part which skyrockets my memory consumption until the app crashes. I do receive the packets on the remote device (separate one) but for some reason everything stays in memory. any idea how to fix this?

**Comment by RevenantX** [comment]
@kurse well LiteNetLib isn't designed to send big amounts of data. But you can reduce pool size here: https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/NetConstants.cs#L92

**Comment by kurse** [comment]
@RevenantX Thanks, I will try it out and see how that will go. Thanks!

**Comment by kurse** [comment]
I ended up implementing my own custom socket management in UDP, if anyone is interested in why and what I've done, go to my question at [Stackoverflow](https://stackoverflow.com/questions/56304789/udp-client-uses-too-much-memory-when-sending-multiple-small-parts-of-a-huge-arra) . Something similar will probably work with LiteNetLib as well.
