### ISSUE TITLE
Server after some time, cannot send messages - only receive 

### ISSUE THREAD

**Issue by fdsagizi** [RevenantX/LiteNetLib#314]
Hi. We use this lib for our backend, where CCU 2k-4k connects. 

Everything ok, but after some time ( 2 hour - 2 days ), library cannot send any messages.

New Client connection to server - OK
Sever receive messages - OK

Server send back messages - FAIL!

What  happen may be ?

We use Unity 2018.3, Linux

**Comment by RevenantX** [comment]
@fdsagizi well without debug logs and debugging at all i cannot say what wrong. But there was some peoples that found similar problem too and:
"@MichalPetryka: from what we tested, our issue doesn't appear on unity 2019.1 (we were using 2018.3), so it's probably something on unitys side"

**Comment by fdsagizi** [comment]
> from what we tested, our issue doesn't appear on unity 2019.1 (we were using 2018.3), so it's probably something on unitys side"

They know how repeat  this bug ? 
Now i cannot repeat, and this bug may happen only after 2 days of server works...

about unity 2019.1 - now we cannot switch version

**Comment by fdsagizi** [comment]
@RevenantX 

Привет. В общем написал проверку, живая ли библиотека или нет - создаем подключение к ней, и смотрим, отвечает ли. Если не отвечает, перезапускаем, просто делая:

net.Stop();
net.Start(port);

и вот тут, выплыла проблема - Stop не завершается, как оказалось он останавливается на 

  _logicThread.Join(); <- тут
       
 как я понимаю logicThread внутри, встает в dead lock 
Вообще, хоть библиотека очень простая, но система блокировок дико сложная.
У меня есть опыт написания RUDP либы( на с++ ), но тут же, Я офигел от количества блокировок. Мне кажется даже тебе трудно гарантировать что, все места блокируются правильно, и нету смертельных петель - когда Блок блокирует блок.

Кажется было бы, куда проще сделать 1 поток на прием сообщений. Который только принимает и обрабатывает сообщения как буферы данных, но не имеет доступа к NetPeer и прочему. А когда мы делаем net.PollEvents() то, просто берем пришедшие данные - через 1 блокировку, и дальше применяем их. Но это мое мнение ( таких сложных блокировок я всегда избегал )

Еще по библиотеке:

Видел в запросах на фичи - это проверка чек сумм на данные, это нужно прям обязательно. Если чек сумма не сходиться, просто скипать пакет как не валидный. В мобильном интернете это прям типичная ситуация.

Так же, странно выглядет код Debug.Log который идет с аргументами - как я понимаю, он всегда будет формировать строку, даже если дебаг выключен. по идеи надо делать if(debugEnabled) Debug.Log(...) иначе пустые аллокации строк

Так же не понял, есть ли проверка на дубликат сообщений - тк в  UDP это нормальная практика, когда приходят 2 сообщения одинаковых.

Попробуем разобраться с дебагом - https://gamedev.ru/code/forum/?id=244828
и перейти на 2019.1 ( но думаю мало вероятно что это поможет ) Тк работа идет с системными компонентами c# - а не с Юнити.

**Comment by RevenantX** [comment]
@fdsagizi 
>Видел в запросах на фичи - это проверка чек сумм на данные, это нужно прям обязательно.

Это понятно. Но я уже говорил по этому поводу. Если ты пишешь защиту от левых пакетов (а почти во всех случаях это надо делать) - то битый пакет без чексуммы ты тоже спокойно обработаешь.

>Так же не понял, есть ли проверка на дубликат сообщений - тк в UDP

В readme всё написано. Есть для Sequenced и других. Для unreliable - нет

>Так же, странно выглядет код Debug.Log который идет с аргументами -

Если посмотришь в исходники там [Conditional("DEBUG_MESSAGES")] который вырезает метод если нет такого дефайна.

> А когда мы делаем net.PollEvents() 

Примерно так и работает. PollEvents работает в потоке в котором ты вызываешь PollEvents

**Comment by RevenantX** [comment]
@fdsagizi 
> Попробуем разобраться с дебагом - https://gamedev.ru/code/forum/?id=244828
и перейти на 2019.1 ( но думаю мало вероятно что это поможет ) Тк работа идет с системными компонентами c# - а не с Юнити.

Там проблема не с компонентами юнити. А с кривой имплементацией Mono и сокетов в том числе.

**Comment by fdsagizi** [comment]
@RevenantX Привет Руслан.
Сделал проверку, может ли либа послать сообщения - просто подключаюсь к ней переодически, и проверяю. После того, как ловлю то, что она перестает отвечать, делаю перезапуск. 

net.Stop();
net.Start(port);

Так вот, когда либа перестает отвечать на сообщения то и на  Stop - процесс зависает, как выяснилось на ожидании завершения потока - _logicThread.Join();

Как я понимаю, либа зависает внутри logicThread - скорее всего, на каком то локе.
Возможно это обьясняет причину, почему перестает посылать сообщения!

Я изучил код либы, она очень простая и лаконичная. Но блокировки - безумно сложные, и запутанные. Получить deadlock в это либе очень просто - хотя бы словив один Exсeption где нибуть в нутри ( а они бывают ). 
У меня был опыт написания RUDP либы, для С++ проекта. Там только 1 поток, для обработки поступающих данных, дальше главный поток просто брал эти сообщения через 1 лок.

**Comment by fdsagizi** [comment]
@RevenantX 
> Там проблема не с компонентами юнити. А с кривой имплементацией Mono и сокетов в том числе.

зависает ведь не на сокетах, а на семафорах.

**Comment by RevenantX** [comment]
@fdsagizi ну останови выполнение на зависании join и посмотри где стоит поток LogicThread. Скинь стактрейс и будет понятно в чём причина.

**Comment by RevenantX** [comment]
@fdsagizi https://github.com/RevenantX/LiteNetLib/commit/0ef6d9cb3525eb5ece6a757083b419f215f8a0e9

Added more safe locks so maybe this will be fixed.

**Comment by fdsagizi** [comment]
> @fdsagizi [0ef6d9c](https://github.com/RevenantX/LiteNetLib/commit/0ef6d9cb3525eb5ece6a757083b419f215f8a0e9)
> 
> Added more safe locks so maybe this will be fixed.

Привет, хорошие новости!
Перешли на юнити 2019.1 и обновились до последней версии LiteNetLib ( до этого была февральская версия )

сейчас все работает отлично! Большое спасибо за библиотеку!

**Comment by RevenantX** [comment]
@fdsagizi отлично тогда закрываю (может действительно проблема в юнити). 
P.S. Огромное спасибо за донат) Как-то даже много)

**Comment by shaunthesheep644** [comment]
Привет! У нас примерно такое же поведение на последней версии на текущий момент (0.9.4). Сервер работает некоторое время, потом (2 часа - 2 дня) происходит нечто, после чего либа перестает принимать и отправлять сообщения. Прямо перед этим в слой логики сервера прилетает несколько битых пакетов. Я воспроизвел подобное поведение сделав два Recycle пакета подряд - по симптомам получается примерно тоже самое. Я подозреваю, что в пул идет два возврата одного пакета подряд, но ничего подробнее сейчас накопать не могу - либа работает на самом нижнем уровне нашего сервера и снять с нее логи в этот рандомный момент невозможно. До этого  больше года работали на 0.8.3 подобных проблем не было. Есть еще одна корреляция, не знаю насколько это реально - сервер два последних раза падал тогда, когда к нему шло подключение из редактора Unity (при остальных клиентах-девайсах).

**Comment by RevenantX** [comment]
@shaunthesheep644 привет. А можешь простую проверку добавить в NetPacket поле Recycled например и ставить его в True когда попадает в пул и в False когда достается? И проверять при добавлении в пул перед установкой Recycled в True - if(Recycled) кинуть исключение? А еще попробуй try/catch накинуть в UpdateLogic обернув все внутренности while( IsRunning ). И логгировать исключение.

**Comment by shaunthesheep644** [comment]
@RevenantX  Спасибо, буду пробовать, сейчас пока откачу прод на 0.8.3.1 и позже поэкспериментирую.

**Comment by shaunthesheep644** [comment]
@RevenantX привет еще раз, поймал проблему - из пула идет получения пакета и пакет, который выдается, в данный момент находится не в пуле, а где-то в обработке. Первые строчки в стэктрейсе - это мои хелперы, дальше - твое (NetManager.cs:line 1051):

[NM] SocketReceiveThread error: System.Exception: NetPacket already has Recycled value = False
   at LiteNetLib.Helpers.RecycleExtensions.SetRecycledWithAssert(IAssertableOnRecycle assertable, Boolean value) in /app/Network/LiteNetLib/Helpers/RecycleExtensions.cs:line 9
   at LiteNetLib.NetManager.CreateReceiveEvent(NetPacket packet, DeliveryMethod method, Int32 headerSize, NetPeer fromPeer) in /app/Network/LiteNetLib/NetManager.cs:line 1051
   at LiteNetLib.NetPeer.ProcessPacket(NetPacket packet) in /app/Network/LiteNetLib/NetPeer.cs:line 963
   at LiteNetLib.NetPeer.ProcessPacket(NetPacket packet) in /app/Network/LiteNetLib/NetPeer.cs:line 906
   at LiteNetLib.NetManager.DataReceived(Byte[] reusableBuffer, Int32 count, IPEndPoint remoteEndPoint) in /app/Network/LiteNetLib/NetManager.cs:line 1032
   at LiteNetLib.NetManager.LiteNetLib.INetSocketListener.OnMessageReceived(Byte[] data, Int32 length, SocketError errorCode, IPEndPoint remoteEndPoint) in /app/Network/LiteNetLib/NetManager.cs:line 764

**Comment by RevenantX** [comment]
@shaunthesheep644 на отправке работы с пулом эвентов нет, да и они поидее все достаточно thread-safe.
