### ISSUE TITLE
Possible bug with reliableOrdered and acks

### ISSUE THREAD

**Issue by forestrf** [RevenantX/LiteNetLib#32]
With a server and a client in the same machine, after opening the connection and send some messages it starts sending packets like a madman. I enabled the DEBUG_MESSAGES symbol to see what was happening and it logged this:

```
[RR]SendAcks        
[RR]Resend: 277        
[R]Recieved data from ::0.0.0.1:25002, result: 11        
[S]Send packet to ::0.0.0.1:25002, result: 11        
[S]Send packet to ::0.0.0.1:59573, result: 204        
[RR]PacketProperty: ReliableOrdered        
[RR]ReliableInOrder duplicate        
[RR]Sended        

[RR]SendAcks        
[R]Recieved data from ::0.0.0.1:25002, result: 204        
[RR]Resend: 321        
[S]Send packet to ::0.0.0.1:25002, result: 11        
[S]Send packet to ::0.0.0.1:59573, result: 39        
[RR]PacketProperty: ReliableOrdered        
[RR]Sended        
[RR]ReliableInOrder duplicate        

[RR]SendAcks        
[RR]Resend: 335        
[R]Recieved data from ::0.0.0.1:25002, result: 39        
[S]Send packet to ::0.0.0.1:25002, result: 11        
[S]Send packet to ::0.0.0.1:59573, result: 6        
[RR]PacketProperty: ReliableOrdered        
[RR]ReliableInOrder duplicate        
[RR]Sended        

[RR]SendAcks        
[R]Recieved data from ::0.0.0.1:25002, result: 6        
[RR]Resend: 355        
[S]Send packet to ::0.0.0.1:25002, result: 11        
[S]Send packet to ::0.0.0.1:59573, result: 11        
[RR]PacketProperty: ReliableOrdered        
[RR]ReliableInOrder duplicate        
[R]Recieved data from ::0.0.0.1:25002, result: 11        
[RR]SendAcks        

[RR]Sended        
[RR]Resend: 205        
[S]Send packet to ::0.0.0.1:25002, result: 11        
[S]Send packet to ::0.0.0.1:59573, result: 204        
[RR]PacketProperty: ReliableOrdered        
[RR]Sended        
[RR]ReliableInOrder duplicate        
[RR]Resend: 151        

[RR]SendAcks        
[R]Recieved data from ::0.0.0.1:25002, result: 204        
[S]Send packet to ::0.0.0.1:59573, result: 39        
[S]Send packet to ::0.0.0.1:25002, result: 11        
[RR]Sended        
[RR]Resend: 142        
[RR]PacketProperty: ReliableOrdered        
[RR]ReliableInOrder duplicate        
[S]Send packet to ::0.0.0.1:59573, result: 6        

[RR]SendAcks        
[R]Recieved data from ::0.0.0.1:25002, result: 39        
[RR]Sended        
[S]Send packet to ::0.0.0.1:25002, result: 11        
[RR]Resend: 120        
[RR]PacketProperty: ReliableOrdered        
[RR]ReliableInOrder duplicate        
[S]Send packet to ::0.0.0.1:59573, result: 11        
[R]Recieved data from ::0.0.0.1:25002, result: 6        

[RR]SendAcks        
[S]Send packet to ::0.0.0.1:25002, result: 11        
[RR]Sended        
[RR]PacketProperty: ReliableOrdered        
[RR]ReliableInOrder duplicate        
[RR]Resend: 109        
[R]Recieved data from ::0.0.0.1:25002, result: 11        
```

It continues on and on. It happens randomly with a hight probability.

I can help with anything to allow you to replicate it.
Thank you!

**Comment by RevenantX** [comment]
There was one bug in merge system. Are you using last version?

**Comment by forestrf** [comment]
Yes, commit fd58793 (the latest one)

**Comment by RevenantX** [comment]
I will debug and check.

**Comment by boonkerz** [comment]
Same Issue here with my Own Project but merge is not enabled.

[R]Recieved data from 10.0.1.70:56575, result: 1432
[RR]PacketProperty: ReliableOrdered
[RR]ReliableInOrder duplicate

**Comment by boonkerz** [comment]
Ok duplicate comes because my client es resending.

`
double packetHoldTime = (currentTime - currentPacket.TimeStamp.Value).TotalMilliseconds;
                        if (packetHoldTime > _peer.ResendDelay)
                        {
                            _peer.DebugWrite("[RR]Resend: {0}", (int)packetHoldTime);
                            packetFound = true;
                        }
`

produces:

`
[RR]Resend: 1002,6923 : 27,5
[S]Send packet to 10.0.1.40:9050, result: 1432
[RR]Sended
[RR]Resend: 1002,6923 : 27,5
[S]Send packet to 10.0.1.40:9050, result: 1432
[RR]Sended
[RR]Resend: 1002,6923 : 27,5
[S]Send packet to 10.0.1.40:9050, result: 1432
[RR]Sended
[RR]Resend: 1002,6923 : 27,5
`

**Comment by RevenantX** [comment]
Found bug.

**Comment by boonkerz** [comment]
with NetConstants.DefaultWindowSize = 1 it works but bigger packages are slow :)

**Comment by RevenantX** [comment]
Will fix soon.

**Comment by boonkerz** [comment]
can you imagine when?

**Comment by RevenantX** [comment]
Today or tomorrow.

**Comment by RevenantX** [comment]
Fixed

**Comment by boonkerz** [comment]
i have the same issue when i test with different machine for server client.

```
[RC]Resend: 1627 > 27
[P]SendingPacket: ReliableOrdered
[S]Send packet to 10.0.1.40:9050, result: 1432
[RR]Sended
[RC]Resend: 1627 > 27
[P]SendingPacket: ReliableOrdered
```

**Comment by RevenantX** [comment]
With fix? Resend is ok. It called when some packet lost.

**Comment by boonkerz** [comment]
yea with this fix i'm transfering a bigger chunk of data (screensharing app)

Server:
```
[R]Recieved data from 10.0.1.70:64245, result: 1432
[RR]PacketProperty: ReliableOrdered
[RR]ReliableInOrder duplicate
[R]Recieved data from 10.0.1.70:64245, result: 1432
[RR]PacketProperty: ReliableOrdered
[RR]ReliableInOrder duplicate
[R]Recieved data from 10.0.1.70:64245, result: 1432
```

**Comment by RevenantX** [comment]
it is possible. but now there is no deadlocks?

**Comment by boonkerz** [comment]
should not 
i use 
UnsyncedEvents = true
and no pollevents

nothing fancy:
https://github.com/boonkerz/teamscreen/blob/master/Common/IntroducerServer.cs

https://github.com/boonkerz/teamscreen/blob/master/Network/Messages/Connection/ResponseScreenshotMessage.cs

**Comment by boonkerz** [comment]
after debuging with wireshark it looks like the client does not receive the ack package?
server is sending the ack package.
but client does not get it?

**Comment by boonkerz** [comment]
sorry looks like networking bug other client work :(

sorry for spaming
