### ISSUE TITLE
Confusing DeliveryMethod comments in NetConstants.cs

### ISSUE THREAD

**Issue by JasperCiti** [RevenantX/LiteNetLib#322]
I'm confused with the comments on DeliveryMethod in NetConstants.cs:

1. Unreliable = Packets can be dropped, duplicated, arrive without order
2. ReliableUnordered = Packets won't be dropped, won't be duplicated, arrive without order
3. Sequenced = Packets can be dropped, won't be duplicated, arrive in order
4. ReliableOrdered = Packets won't be dropped, won't be duplicated, arrive in order
5. ReliableSequenced = Packets can be dropped (except the last one), won't be duplicated, arrive in order

Can someone confirm if my understanding is correct? Can I update the comments for future developers? (I noticed @Korseus also got confused)

**Comment by GTANAdam** [comment]
A couple of corrections, If I may:

- **Unreliable** = Packets can be dropped, **can be** duplicated, **can** arrive without order.
- **ReliableUnordered** = Packets won't be dropped, won't be duplicated, **can** arrive without order.
- **Sequenced** = Packets can be dropped **(except the last one)**, won't be duplicated, **will** arrive in order.
- **ReliableOrdered** = Packets won't be dropped, won't be duplicated, **will** arrive in order.
- **ReliableSequenced** = Packets can be dropped (except the last one), won't be duplicated, **will** arrive in order

**Comment by RevenantX** [comment]
>Sequenced = Packets can be dropped (except the last one), won't be duplicated, will arrive in order.
Last one can be dropped too (because UDP) this is main differenece to ReliableSequenced (that reliable)
