### ISSUE TITLE
Replacing byte array with Span for RawData

### ISSUE THREAD

**Issue by GTANAdam** [RevenantX/LiteNetLib#323]
So I was working on making a relay platform with this library and I found that in order to get the UserData from RawData, I would have to create another array, which is problematic. 
The solution that was introduced in C# 7.2 starting with .NET Core 2.1 allows slicing Span without copying buffers or allocations.

You can find more details here: [Span specification](https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md)

Introducing this within this library will bring great performance improvements.
Given that I require this in my platform, I will have this implemented and gladly pull request as soon as I'm done with it.

**Comment by RevenantX** [comment]
@GTANAdam there is " public ArraySegment<byte> GetRemainingBytesSegment() " that works in some similar way.

**Comment by RevenantX** [comment]
@GTANAdam also you dont need to create new array. You can just read existing array starting with UserDataOffset (and just read from that point)

**Comment by GTANAdam** [comment]
> @GTANAdam there is " public ArraySegment GetRemainingBytesSegment() " that works in some similar way.
That's actually very interesting..

> @GTANAdam also you dont need to create new array. You can just read existing array starting with UserDataOffset (and just read from that point)
In case the UserData (without the 4 header bytes (for reliable) or more) has to be resent as is, creating a slice with Array.Copy becomes necessary, this would've been avoided with a ReadOnlySpan type RawData segment

**Comment by MichalPetryka** [comment]
Span aren't even supported by .net Framework 4.8, so total no from me.

**Comment by mdsitton** [comment]
Also after doing some benchmarks with span under mono, the performance really isn't there for that runtime. With byte arrays often being faster in the cases i was looking at.

**Comment by GTANAdam** [comment]
> Also after doing some benchmarks with span under mono, the performance really isn't there for that runtime. With byte arrays often being faster in the cases i was looking at. So also a no from me.
Span is designed to avoid or reduce memory allocations (garbage), thus lessen GC work which would eventually increase performance and lower memory usage within massive high performance apps/servers. In contrast, Span wouldn't prove itself any different within small apps or tests, which I suspect is your case.

**Comment by RevenantX** [comment]
> 
> 
> > @GTANAdam there is " public ArraySegment GetRemainingBytesSegment() " that works in some similar way.
> 
> That's actually very interesting..
> 
> > @GTANAdam also you dont need to create new array. You can just read existing array starting with UserDataOffset (and just read from that point)
> 
> In case the UserData (without the 4 header bytes (for reliable) or more) has to be resent as is, creating a slice with Array.Copy becomes necessary, this would've been avoided with a ReadOnlySpan type RawData segment

Array copy isnt necessary when you need resent data as is.
```csharp
netPeer.Send(packet.RawData, packet.UserDataOffset, packet.UserDataSize);
```
