### ISSUE TITLE
Question about udp packet contents

### ISSUE THREAD

**Issue by MarcelPegre** [RevenantX/LiteNetLib#324]
I have this c# client code 

```csharp
using System;
using System.Threading;
using LiteNetLib;
using LiteNetLib.Utils;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            EventBasedNetListener listener = new EventBasedNetListener();
            NetManager client = new NetManager(listener);

            NetDataWriter dataWriter = new NetDataWriter();

            client.Start();
            var target = client.Connect("127.0.0.1" /* host ip or name */, 9050 /* port */, "key" /* text key or NetDataWriter */);

            dataWriter.Put("data");
            target.Send(dataWriter, DeliveryMethod.Unreliable);

            while (!Console.KeyAvailable)
            {
                Thread.Sleep(100);
            }
        }
    }
}
```

and that's sending to a simple nodejs debugging app that prints out the contents of any packet received.
The server received this - 
<Buffer 08 07 00 00 00 15 17 ce 7e f0 09 d7 08 03 00 00 00 6b 65 79>
The last three bytes are the key. I was wondering what's the format for the rest of the information? What is it all? Is there much overhead on each packet?

Thanks

**Library version**: [commit id (9f2a1d1a8244510d9ec502cc002bfdddba666d09) or release version (0.7.7.1)]

**Framework**: [.NET Framework]

**OS**: [Windows]

**Comment by RevenantX** [comment]
@MarcelPegre all info here: https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/NetPacket.cs
There isn't much overhead for each packet. 1 byte - for unreliable packet (and some others), 4 for any channeled packet (sequenced,reliable,etc) and 6 bytes for fragmented channeled packet.

**Comment by MarcelPegre** [comment]
Thanks for the fast response!
With the client connection handling is it secure at all (sorry if this is a stupid line of questioning).
If you verify a client once when they open a peer connection should you also verify them for all future packets?

**Comment by RevenantX** [comment]
@MarcelPegre well this depends on task. You must write your server with protection in all cases (and with authoritative logic).
