### ISSUE TITLE
Combine NetManager.Start and NetManager.Connect into NetManager.Host and NetManager.Join

### ISSUE THREAD

**Issue by Shadowblitz16** [RevenantX/LiteNetLib#330]
I think it would be useful if NetManager.Start and NetManager.Connect
were combined into two functions NetManager.Host and NetManager.Join.

you could even make NetManager.Host accepts a passkey like NetManager.Connect and NetManager.Join, and automatically reject people host side that don't match.

Version 0.8.3.1
OS Windows 7 Home 64 bit;
IDE Visual Studio 2017 Community

**Comment by RevenantX** [comment]
@Shadowblitz16 this will increase complexity in understanding Start/Connect. Also request/reject is so simple only for example. For real games there will be much more custom checks.
