### ISSUE TITLE
'Index was outside the bounds of the array' on client after calling .Reset() on message server-side

### ISSUE THREAD

**Issue by Netkicks** [RevenantX/LiteNetLib#333]
I'm implementing the same code I did months ago, and I'm getting an error when trying to read the first byte element of a message. They **ALL** come from game server with a byte as first element. So on client-side, I check the message type based on it, like everyone does.

However, a **singleton** game update message that's sent a couple times per second is failing to recycle. I call .Recycle() on it before sending it to all players, but sometimes (there seems to be an interval) the message arrives messed up, and reader.GetByte(); thows an exception:

**Index was outside the bounds of the array.**

This is a **simplified** algorithm:

```
foreach (Peer peer in peers) {
   singletonMessage.Reset();
   singletonMessage.Put((byte)messageType);
   singletonMessage.Put(peer.something);
   SendToAllPlayers(singletonMessage);
}
```

This is how I read the message on client-side:

```csharp
private void GotMessage(NetPeer peer, NetPacketReader reader, DeliveryMethod deliveryMethod)
    {

        GameMessageType type = (GameMessageType)reader.GetByte();
     }
```

**Library version**: latest commit

**Framework**: .NET Framework

**OS**: Windows

**Comment by Netkicks** [comment]
Note: this doesn't happen if i do `singletonMessage = new NetDataWriter()` instead of `calling .Reset()`.

**Comment by Netkicks** [comment]
@RevenantX  you can close this thread.

It was a weird issue with threads.

Basically PollEvents() was called on the main thread. And the function for sending updates on another. There's a bug on .NET where threads stutter. I guess there was some kind of threads conflict and things didn't work as they should. 

Changing the target Framework to a newer version (it was 3.5 before) solved it.

Ref.: https://github.com/dotnet/coreclr/issues/25971

**Comment by RevenantX** [comment]
@ghost this is strange. Also you referenced .net core (not .net framework which works in different way). This can be Unity mono bug. Maybe create this bug in unity bug tracker?
