### ISSUE TITLE
I want to ask  About Peer 2 peer connection

### ISSUE THREAD

**Issue by onurigdi** [RevenantX/LiteNetLib#335]
Hi. Am Im working on a matchmaker server. with litenetlib. I simply hold peers in a dictionary on the server. clients registering when connect and unregistering when disconnect. when i match the 2 client with server. clients going on communicating with server. for example if c1 will send a package to c2 then c1 first send it to server. server send it to c2 instead of c1. i thing there must be a way to communicate c1 and c2 peer to peer. i send the clients opponent clients endpoint at first match. c1 has c2 endpoint and c2 has c1 endpoint. how can i send directly client to client instead of sending server.

Clients connect to server : 
```csharp
hostNetManager.Connect("192.168.1.11", 15000);
```

OnNetworkReceive : (i get the endpoint from server which client is my opponent)
```csharp
case (NET_DATA_TYPE.findPlayer):

OpponentEndPoint = reader.GetNetEndPoint();
```

when i want to send a package to c2 at any time i try to use this
```csharp
NetDataWriter netDataWriter = new NetDataWriter();

        netDataWriter.Reset();

        netDataWriter.Put((int)Consts.NET_DATA_TYPE.setReady);

        var pack = hostNetManager.PacketPool.GetWithData(PacketProperty.ReliableOrdered, netDataWriter);

        hostNetManager.SendRawAndRecycle(pack, OpponentEndPoint );
```

c2 never recieve this package. how can i send it to c2 and how can i recive it from c2.
```csharp

**Framework**: [Unity]

**OS**: [Android]

**Comment by RevenantX** [comment]
@onurigdi there is full example exists - https://github.com/RevenantX/LiteNetLib/blob/master/LibSample/HolePunchServerTest.cs
