### ISSUE TITLE
Handlers to use external (custom) logic for transparent encryption 

### ISSUE THREAD

**Issue by Greendq** [RevenantX/LiteNetLib#338]
As I see, there are some people interested in the encryption ability for this library.

I propose to add 2 callback handles, which will help to add almost any external logic for transparent data encryption, something like:

```csharp
// Ecrypt
byte[] BeforeSend(byte[] data);
```
and
```csharp
// Decrypt
byte[] BeforeReceive(byte[] data);
```

where BeforeSend() function result will replace the actual user's data buffer right before actual sending the UDP (without replacing library's service data from header) and BeforeReceive() will be called on actual data receiving, but BEFORE firing the NetworkReceiveEvent event.

Having just those 2 handlers will allow to implement AES encryption really easy.

Sure, the whole encryption logic implementation will remain on developer who will use the library - crypto-processor initialization, keys management, etc.

**Comment by yacuzo** [comment]
I want this too.

**Comment by RevenantX** [comment]
completed by @yacuzo
