### ISSUE TITLE
it is possible situations?

### ISSUE THREAD

**Issue by kwanggaeto** [RevenantX/LiteNetLib#341]
hi, i'm using the LiteNetLib with two network adaptors.

the one is connected local network, another is connected internet.

and, my work is a PC's Power control Manager app and client app, each app is tied as local network.

clients has two network adaptors but the server pc has only one network adaptor.

a client just send a survive signal(1byte) to server.
a manager send a magic packet through WOL or send a shutdown packet to clients.

but, a client cannot discover a server, cannot be communicate with a server.

i tested two ways, a way for communication using a specific server information and a way for communication  after discovering a server.

but, all of two ways is not working. 

for specifically, some PC is working but others PC is not working. 

more specifically, disconnect the internet of a PC worked, then a PC not worked is started working.

weird....

could it be because i used the LiteNetLib?

do you have a opinion about this case?

**Comment by RevenantX** [comment]
@kwanggaeto try use NetManager.Start(IPAddress addressIPv4, IPAddress addressIPv6, int port)
And provide to this method IP address that used for your local network (local ip of this PC).
Local IP you can get from https://revenantx.github.io/LiteNetLib/api/LiteNetLib.NetUtils.html#LiteNetLib_NetUtils_GetLocalIpList_LiteNetLib_LocalAddrType_

**Comment by kwanggaeto** [comment]
> @kwanggaeto try use NetManager.Start(IPAddress addressIPv4, IPAddress addressIPv6, int port)
> And provide to this method IP address that used for your local network (local ip of this PC).
> Local IP you can get from https://revenantx.github.io/LiteNetLib/api/LiteNetLib.NetUtils.html#LiteNetLib_NetUtils_GetLocalIpList_LiteNetLib_LocalAddrType_

Thanks, I'll try your solution.
