### ISSUE TITLE
Can't connect when used in Unity 2019.2.2f1

### ISSUE THREAD

**Issue by piller187** [RevenantX/LiteNetLib#342]
In Unity when I call Connect("127.0.0.1", 65000, "") in the Unity console I get the message:

[NM] DataReceived: bad!

For testing I create a normal C# console app and got LiteNetLib from nuget and I can connect to my test server console app just fine. So it seems like it's something with trying to connect from Unity.

The way I brought the library into Unity:
   1. download the source code from github
   2. copy the contents of the LiteNetLib folder to Assets/Plugins (I took out the csproj file though as I didn't think I'd need that)

Everything compiles just fine so it would seem it has everything it needs. It just won't connect.

The PeerDisconnectedEvent gets raised and the disconnectInfo reason just says ConnectionFailed.

I created the below script and attached to the camera for a dumbed down version of what I was trying to do. What's interesting is if I don't have the server running I don't get an error, but after 5 seconds I get the Disconnected notice in the console. If I have the server running I instantly get the [NM] DataReceived: bad! and then 5 seconds later the Disconnected notice in the console.

```
using UnityEngine;
using LiteNetLib;
using LiteNetLib.Utils;

public class TestConnection : MonoBehaviour
{
    private EventBasedNetListener listener;
    private NetManager network;

    // Start is called before the first frame update
    void Start()
    {
        // init network stuff
        listener = new EventBasedNetListener();
        network = new NetManager(listener);

        listener.PeerConnectedEvent += (peer) => 
        {
            Debug.Log("Connected!");
        };

        listener.PeerDisconnectedEvent += (peer, dcInfo) =>
        {
            Debug.Log("Disconnected");
        };

        network.Start();

        // testing
        network.Connect("127.0.0.1", 65000, "");
    }

    // Update is called once per frame
    void Update()
    {
        network.PollEvents();
    }
}

```

**Comment by RevenantX** [comment]
@piller187 are you using same LiteNetLib version? Because on github master - 0.9 and in nuget package is 0.8.3.1

**Comment by piller187** [comment]
I bet that's it. I'll check it out here shortly. Would you recommend I use 0.9 and just get the dlls for my server console app from github instead of nuget?

**Comment by RevenantX** [comment]
yes, better use 0.9 it has more functions and better speed.

**Comment by piller187** [comment]
OK thanks. Just tested it out where they were all on the same version (0.9) and it worked! Thanks for seeing my oversight on that :)
