### ISSUE TITLE
Undefined packet in NetDataReader

### ISSUE THREAD

**Issue by aidanv** [RevenantX/LiteNetLib#343]
LiteNetLib.Utils.ParseException: 'Undefined packet in NetDataReader' on .net core

I've made a client and server app, with "PacketProcessorExample.cs" all appears fine when client and server are both .net 3.5 however, I need to make my client Linux supported so I'm using .net core client side with a fresh netcoreapp2.1 build (LiteNetLib.dll) but receiving 'Undefined packet in NetDataReader' ERROR. Can confirm working when client and server are .net 3.5 but same code will not work on .net core client side.

**Comment by aidanv** [comment]
worked out that the client and server apps need to have the same namespace name :\

**Comment by RevenantX** [comment]
well this is covered in article 
" 64 bit hash of class name and namespace (8 bytes)."
