### ISSUE TITLE
Use Broadcast,When client have virtual network adapter will not found server!!

### ISSUE THREAD

**Issue by Archer4HDJ** [RevenantX/LiteNetLib#345]
Use Broadcast,When client have virtual network adapter will not found server!! but when I disable virtual network adapter ,zhe client can find server. when server have virtual network adapter it work ok. can you fix the bug

**Library version**: [commit id (9f2a1d1a8244510d9ec502cc002bfdddba666d09) or release version (0.9)]

**Framework**: [Mono, Unity, dotnetcore, .NET Framework]

**OS**: [Android, Windows, etc]

**Comment by RevenantX** [comment]
@Archer4HDJ use `netManager.Start` with IPAddress on client. 
https://revenantx.github.io/LiteNetLib/api/LiteNetLib.NetManager.html#LiteNetLib_NetManager_Start_System_Net_IPAddress_System_Net_IPAddress_System_Int32_

**Comment by RevenantX** [comment]
duplicate #341
