### ISSUE TITLE
WebSockets bridge for WebGL in Unity

### ISSUE THREAD

**Issue by Byte-Master-101** [RevenantX/LiteNetLib#346]
Before I start, I would like to thank you for your great effort @RevenantX .

I want to suggest the implementation of a WebSockets bridge for WebGL support. Such an implementation would use ".jslib" files on the client side (like [this library](https://github.com/endel/NativeWebSocket) or as shown in [Unity's documentation](https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html)). I know I'm asking for a lot, but this would allow game developers to publish multiplayer games that can run on any platform (including browsers).

This would need quite a bit of processor directives on the client side, but the important part is: it would need adding a WebSockets listener that can run in parallel with the UDP listener on the server side (treating all the clients the same way).

Doing so will make multiplayer development so much easier because a game developer would be dealing with a single codebase to make browser+standalone+mobile games.

I don't know much about the internal workings of LiteNetLib, but I can help with the development of such a feature if you are fine with that.

**Comment by RevenantX** [comment]
@Byte-Master-101 websocket is TCP. This doesn't make any sense to this library. Also i don't have time for this.

**Comment by Byte-Master-101** [comment]
Ok. Thank you for the consideration.
