### ISSUE TITLE
Host twice?

### ISSUE THREAD

**Issue by qtghost** [RevenantX/LiteNetLib#347]
one pc
same ip
same port
but i can host twice?
i don't think it should be happening

**Comment by RevenantX** [comment]
@qtghost can you show minimal example with reproduce?

**Comment by qtghost** [comment]
> @qtghost can you show minimal example with reproduce?

oh , realy simple
you can try to run three of your demo on one pc
[This Demo](https://github.com/RevenantX/NetGameExample)
```
two host
one connect
```
and something was wrong

**Comment by RevenantX** [comment]
@qtghost there is just no check to 
```csharp
 _netManager.Start(10515);
```
It failed but started actual gameplay, but you cannot connect to that instance.

**Comment by qtghost** [comment]
> @qtghost there is just no check to
> 
> ```cs
>  _netManager.Start(10515);
> ```
> 
> It failed but started actual gameplay, but you cannot connect to that instance.


i just found ur demo just fine
oops sorry for that

**Comment by qtghost** [comment]
> @qtghost there is just no check to
> 
> ```cs
>  _netManager.Start(10515);
> ```
> 
> It failed but started actual gameplay, but you cannot connect to that instance.

i try to host twice 
and use another demo to connect
then cant send packet to each other

Maybe we should check port occupancy before host?
Is there any way to check?

**Comment by RevenantX** [comment]
@qtghost 
```csharp
if(!_netManager.Start(10515))
{
    Debug.Log("Start failed: port occupied");
}
```

**Comment by qtghost** [comment]
> @qtghost
> 
> ```cs
> if(!_netManager.Start(10515))
> {
>     Debug.Log("Start failed: port occupied");
> }
> ```

appreciated that
thanks for reply
