### ISSUE TITLE
Server Run In IOS Crash 

### ISSUE THREAD

**Issue by Archer4HDJ** [RevenantX/LiteNetLib#348]
Use Unity 20174.35
IL2cpp IOS
when I start Server it will crash. error:"Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)",
 locate in NetSocket.BindSocket line170  Socket.IOControl api
my code run in windows ,android(no IL2cpp) is right

Can you fixed the bug

**Library version**: (0.9)]

**Framework**: [Mono, Unity, dotnetcore, .NET Framework]

**OS**: [IOS]

**Comment by RevenantX** [comment]
@Archer4HDJ fixed
