### ISSUE TITLE
Correct usage for P2P connection with UDP punchholing.

### ISSUE THREAD

**Issue by Ahmad45123** [RevenantX/LiteNetLib#349]
Hello!

I'd like to establish peer to peer connection between 2 clients using a server for initial address and port exchange. I already use a TCP connection for transferring the addresses to each client, etc.. 

Now I'd like to understand how to use LiteNetLib in P2P ? Can your library work without a server in this case ? I'm confused.

Any help appreciated :)

**Comment by Ahmad45123** [comment]
BUMP!

**Comment by RevenantX** [comment]
@Ahmad45123 there is sample https://github.com/RevenantX/LiteNetLib/blob/master/LibSample/HolePunchServerTest.cs
Also read about how this work in wiki https://en.wikipedia.org/wiki/UDP_hole_punching

**Comment by Ahmad45123** [comment]
Oh thank you! 

To be honest the code isn't very clear at first glance as I can't seperate what's the code that's gonna run on the server and what on the 2 clients. But regardless I'll give it a go and come back with further questions, if any. :)

**Comment by Ahmad45123** [comment]
Works :)
