### ISSUE TITLE
I think it is necessary to add an asynchronous heartbeat pack。

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#35]
Udp hole has time limit.If there is no data transfer for a long time（Generally dozens of seconds）, the UDP hole will fail。

And  "_lastPacketReceivedStart" Refresh requires the update function to execute。If the phone screen locks the screen, the update function will not execute。Then connection will time out.

I do not have the experience of the network library, so there is no confidence to contribute.。

**Comment by RevenantX** [comment]
> "_lastPacketReceivedStart" Refresh requires the update function to execute
Update function called in other thread, that started when you call ```Start``` method in NetManager(NetServer/NetClient). And there is heartbeat packet (ping)

**Comment by QiuBuZai** [comment]
This thread should only handle the logic of the received packet, and the send packet can only be executed by "MonoBehaviour.Update". I may not look carefully enough. But when I test P2P under different nat devices, lock a phone screen for some time, there will be connected to disconnect the event "TimeOut", and then in a while they can not communicate properly and "NetworkError" event, error The code is 10051.

**Comment by QiuBuZai** [comment]
I guess I know the reason, maybe I use the VPN caused by the network reasons, and lock screen is not directly related.
