### ISSUE TITLE
[Question] Does LiteNetLib work in the Unity Editor?

### ISSUE THREAD

**Issue by Toorah** [RevenantX/LiteNetLib#351]
Would it be possible to use LiteNetLib to create connections between 2 Unity Editor instances?
I would like to create a Master-Slave relationship between multiple machines, for some long-running heavy tasks, so I can free up my main workstation.
So simply, does it work in the Unity Editor (not runtime)?

**Comment by RevenantX** [comment]
@Toorah sure it works in Unity Editor o_O. There is almost no difference in integrated Mono in Runtime or Editor

**Comment by Toorah** [comment]
Just to clarify, I mean, for Unity as an Editor Tool. This is also what you meant, correct?

**Comment by RevenantX** [comment]
@Toorah there is no special specific "Editor" tools. This is just C# library, without specific bindings to Unity

**Comment by Toorah** [comment]
Ok, perfect. Thank you.
