### ISSUE TITLE
 iPhone and iPads running iOS 13.3.1 on Wi-Fi.

### ISSUE THREAD

**Issue by xafgun** [RevenantX/LiteNetLib#353]
At IOS build on Unity connection lost after peer connect. 

But works on iPhone 7+ 8+ Unity Standalone, Windows, Android.

**Branch 0.8**

Server : 

            NetDebug.Logger = this;
            _dataWriter = new NetDataWriter();
            _netServer = new NetManager(this);
            _netServer.Start(50900);
            _netServer.DiscoveryEnabled = true;
            _netServer.UpdateTime = 15;

Client :
            _netClient = new NetManager(this);
            _netClient.Start();
            _netClient.Connect(ipAdress, port, "game_key");

**Comment by RevenantX** [comment]
@xafgun any updates on this? Seems that there is no similar bug reports?

**Comment by xafgun** [comment]
Hello, no. I had same issue with Lidgren. Tried 1 more UDP socket and same error. Lasty I changed it Telephaty and it works with any problem. Can't find solutions but some other people realized that with other UDP socket libraries except Photon.

**Comment by RevenantX** [comment]
@xafgun this can be unity bug. Maybe report to them? Photon use native socket that's why it can possibly work. Also Telepathy is TCP.

**Comment by xafgun** [comment]
@RevenantX, Yes I think it is Unity bug, too :) Yes telephaty is TCP so I tried it and it works. I use network library for text based game so TCP is not big problem for me, but if I work on bigger project it is big problem. For testing purpuses I need to write some client and server codes but because of this covid I have too many works :)

**Comment by Yliria** [comment]
Did you find a solution ?

**Comment by RevenantX** [comment]
@Yliria i thinks solution is to write bug report to Unity team. I don't have a mac and/or ios device so i cannot check this.

**Comment by RevenantX** [comment]
@xafgun @Yliria i added possible fix https://github.com/RevenantX/LiteNetLib/commit/3f144397dd40d3de83ecbc6172a0803fd6a6eddd you can try enable in NetManager.IPv6Enabled = IPv6Mode.DualMode

**Comment by RevenantX** [comment]
@xafgun @Yliria seems that was some problem on Apple side because one user (Znahar90) mentioned that "After a many weeks of fights Apple review team pass our app. Seems that there are really was some issue on their side becase app was working on all devices and enviroments that they mentioned on their reviews."

**Comment by RevenantX** [comment]
Solution with TCP wrapper https://gist.github.com/RevenantX/e251b28a62d7c8caa570d352cd007c90
