### ISSUE TITLE
Is it possible to use the library source in Unity and a .dll that looks for LiteNetLib's dll files?

### ISSUE THREAD

**Issue by asusralis** [RevenantX/LiteNetLib#354]
I'm using a library that references LiteNetLib. When I import that library to Unity, it looks for LiteNetLib's .dll. However, it is recommended to use the library source directly in Unity for the #ifdefs. Is it possible to use both at the same time?

**Comment by RevenantX** [comment]
If you use unity only on desktop platforms (win/mac/linux) you can use just DLL. If you use mobile platforms - there can be problems with library that references LiteNetLib

**Comment by asusralis** [comment]
Thanks for the response. So there is no way to both satisfy my library and have the source files in Unity?

**Comment by RevenantX** [comment]
@asusralis you can change namespace of source code ( LiteNetLib to MyGame.LiteNetLib for example ).

**Comment by RevenantX** [comment]
Also for small questions better use discord: https://discord.gg/FATFPdy
