### ISSUE TITLE
"Only one usage of each socket address [...]" while connecting to server in Unity.

### ISSUE THREAD

**Issue by asusralis** [RevenantX/LiteNetLib#355]
Sorry for submitting two issues at once( I found a similar problem [here](https://github.com/RevenantX/LiteNetLib/issues/259), but I'm well past the commit where that was fixed (master). I also tried it on 8.3.x

I'm simply using .Start() on the client:

```csharp
_manager.Start();
```

The server says the client connects, but then I get this:

System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted.

  at System.Net.Sockets.Socket.Bind (System.Net.EndPoint localEP) [0x00043] in <ae22a4e8f83c41d69684ae7f557133d9>:0 
  at LiteNetLib.NetSocket.BindSocket (System.Net.Sockets.Socket socket, System.Net.IPEndPoint ep, System.Boolean reuseAddress) [0x000e3] in <00b26c8d9c4e42699eaae32532b782b8>:0 

**Library version**: commit id 3d2d7c720169f575e591ee5c2bea042a39cbffe0

**Framework**: Unity 2019.3.6f1. Server is running on .Net Core.

**OS**: Windows 10.

**Comment by RevenantX** [comment]
@asusralis are you calling `_manager.Stop` in `OnApplicationQuit` or `OnDestroy`?

**Comment by RevenantX** [comment]
@asusralis any info?

**Comment by asusralis** [comment]
Sorry for the late reply. No, I'm not calling Stop anywhere. 

It seems when I don't have a debugger attached it seems to not throw that exception, but my serializer is throwing an exception after my client receives data. I'm not sure why it isn't telling me there is a problem finding a port when it isn't attached. Is this the wrong way to read the bytes?

```
 byte[] bytes = new byte[reader.UserDataSize];

 reader.GetBytes(bytes, 0, reader.UserDataSize);

 // Use Ceras to deserialize the bytes 
```

This worked when I did a test outside of Unity, but I think my serializer is acting like the byte array is incomplete.

**Comment by RevenantX** [comment]
@asusralis you need to call netManager.Stop() in OnApplcationQuit

**Comment by asusralis** [comment]
It happens the first time I play Unity after restarting. How would calling Stop have to do with anything?

**Comment by RevenantX** [comment]
@asusralis Unity in editor always run mono runtime. So if you not call Stop() there will be background threads with active sockets that listening at the port you selected. Also check that you use port with number more than 1024 because 1-1024 are system reserved ports.

**Comment by rtsonneveld** [comment]
I'm having the same issue, but only when using IPV6. I call .Stop() on my NetManager on application quit, and it happens even when I just started a fresh Unity instance.

**Comment by RevenantX** [comment]
@rtsonneveld if it works after this - it is ok. Because there is some workarounds over unity3d bugs.
