### ISSUE TITLE
Initialization error on WebGL (Unity)

### ISSUE THREAD

**Issue by Siccity** [RevenantX/LiteNetLib#358]
As soon as NetManager is instantiated, an exception is thrown.

```csharp
netServer = new NetManager(this);
```

```
SocketException: Success
  at System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)
```

**Library version**: 748f2f7b23a0f564b1b8b0d674867d39821959f0

**Framework**: Unity

**OS**: Windows, Google Chrome, WebGL

**Comment by RevenantX** [comment]
@Siccity webgl is not supported.

**Comment by Siccity** [comment]
Bummer. Thanks for the quick response.

**Comment by RevenantX** [comment]
> 
> 
> How hard would it be to support WebGL?

Websockets is TCP only. No UDP support. So this out of scope of this library
