### ISSUE TITLE
HolePunchServerTest crashes

### ISSUE THREAD

**Issue by jahnotto** [RevenantX/LiteNetLib#359]
I'm trying to run the HolePunchServerTest sample. However, it crashes at the following location:

    LiteNetLib.NetManager.AddPeer(LiteNetLib.NetPeer) in NetManager.cs
    LiteNetLib.NetManager.OnConnectionSolved(LiteNetLib.ConnectionRequest, byte[], int, int) in NetManager.cs
    LiteNetLib.ConnectionRequest.AcceptIfKey(string) in ConnectionRequest.cs
    LibSample.HolePunchServerTest.Run.AnonymousMethod__10_1(LiteNetLib.ConnectionRequest) in HolePunchServerTest.cs
    LiteNetLib.EventBasedNetListener.LiteNetLib.INetEventListener.OnConnectionRequest(LiteNetLib.ConnectionRequest) in INetEventListener.cs
    LiteNetLib.NetManager.ProcessEvent(LiteNetLib.NetEvent) in NetManager.cs
    LiteNetLib.NetManager.PollEvents() in NetManager.cs
    LibSample.HolePunchServerTest.Run() in HolePunchServerTest.cs

The line _peersLock.EnterWriteLock() throws an exception: System.Threading.LockRecursionException: 'Recursive write lock acquisitions not allowed in this mode.'

Is this a bug or a problem in my end?

**Library version**: commit id 748f2f7b23a0f564b1b8b0d674867d39821959f0 (latest master)

**Framework**: .Net console application

**OS**: Windows

**Comment by RevenantX** [comment]
@jahnotto you didn't modified anything? and this is constantly crashes every run? Because i cannot find where is "recursion" write lock can be happen from this exception message.

**Comment by RevenantX** [comment]
@jahnotto hm, reproduced this. Thanks for report. I will look into this.

**Comment by jahnotto** [comment]
Thanks for following up so quickly @RevenantX . I have not changed anything (other than uncommenting this test in Program.cs). It crashes consistently every time.

**Comment by RevenantX** [comment]
@jahnotto fixed!

**Comment by jahnotto** [comment]
Wow, that was super quick! Thank you!
