### ISSUE TITLE
Identify peer on OnReceive event

### ISSUE THREAD

**Issue by joklbash** [RevenantX/LiteNetLib#36]
I'm changing some of my code to use the NetSerializer.Subscribe<T> event. How can I tell for sure what peer sent the information since the OnReceive for the Subscribe only includes the deserialized struct?

...
_netSerializer.Subscribe<SamplePacket>(OnSamplePacketReceived);
...
private void OnSamplePacketReceived(SamplePacket samplePacket)
{
// How to determine peer that sent here?
}

If multiple peers are sending, the OnNetworkReceive(...) event is too far removed to reliably determine peer associated with the OnReceive Action. In my situation, I'm receiving a request that expects a response.

**Comment by RevenantX** [comment]
Ok. I will add this possibility.

**Comment by joklbash** [comment]
Thank you. I'm enjoying this library a great deal and it has eased my Udp implementation so much.

**Comment by RevenantX** [comment]
Added support for any user data.
