### ISSUE TITLE
Current Master not threadsafe and sends additional grabbage

### ISSUE THREAD

**Issue by c0nnex** [RevenantX/LiteNetLib#360]
Current master is not Threadsafe for NetPacketProcessor.Send*/Write*
writer.Reset() will destroy any currently written packets. 
Fix: lock the writer in Send*/Write*

NetPacketProcesser sends additional garbage because writer is reused.
Possible Fix:  e.g. NetManager.SendToAll should use writer.Postition not writer.Length which is maybe a bigger number than the current packet.
(Noticed it because a 8 byte update packet had 1024 bytes, because previous packet was that big)
Still investigating though why the garbage contained came from a paket that was received by the sender! So maybe here a NetDataReader reuse problem as well.

**Library version**: commit id (748f2f7b23a0f564b1b8b0d674867d39821959f0) 

**Framework**: [dotnetcore]

**OS**: [Windows]

**Comment by RevenantX** [comment]
@c0nnex writer.Length is actually - position:
https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/Utils/NetDataWriter.cs#L103

Also yes NetPacketProcessor.Send/Write with internal netDataWriter isn't threadsafe. But i've never metioned that it is threadsafe :) For threadsafe - use Send/Write with local NetDataWriter for each thread.

>(Noticed it because a 8 byte update packet had 1024 bytes, because previous packet was that big)

This is result of internal pool. This is not received garbage. This packet just taken from pool and its size can be bigger than actual data size. But actual data size in NetDataReader UserDataSize and data offset at UserDataOffset

**Comment by c0nnex** [comment]
for now i added locking to the my NetpacketProcessor, which is currently enough. 

About the garbage all is fine then, just wondered as I dumped out the reader for debugging in OnNetworkReceive and was a bit confused.

Thanks for the quick reaction
