### ISSUE TITLE
How to measure/detect an outgoing queue backup?

### ISSUE THREAD

**Issue by mgamache** [RevenantX/LiteNetLib#363]
The 8.x versions had a `PacketsCountInReliableOrderedQueue` (for example). What is the preferred method in 9.x for measuring this? I want to know if I am backing up the queue so i can slow down transmission.  

thanks,
mark

**Comment by RevenantX** [comment]
Well one of the methods is use "DeliveryEvents" like here: https://github.com/RevenantX/LiteNetLib/issues/248#issuecomment-545681241

**Comment by mgamache** [comment]
That's a cool feature! As I am sending a lot of traffic so I would probably only send a small percentage with delivery notification. I am thinking of a timestamp so I can measure how behind the remote client is vs what I am sending. Unless there is a better way to measure that? 

thanks,
mark

**Comment by RevenantX** [comment]
added `GetPacketsCountInReliableQueue(byte channelNumber, bool ordered)`
