### ISSUE TITLE
Statistics don't work when using NetPacketProcessor

### ISSUE THREAD

**Issue by kascodingNL** [RevenantX/LiteNetLib#365]
Information about bug or feature

**Library version**: 0.8
**Framework**: .NET framework

**OS**: Windows

When using NetPacketProcessor, I never got server.Statistics to work.

**Comment by RevenantX** [comment]
Do you have DEBUG or STATS_ENABLED define?

**Comment by kascodingNL** [comment]
Could you please explain how to do that?

**Comment by RevenantX** [comment]
https://stackoverflow.com/questions/1995869/how-to-set-project-wide-define-in-c-sharp

**Comment by kascodingNL** [comment]
It is not really clearing up anything for me.

**Comment by RevenantX** [comment]
@kascodingNL and you are using library source code? If you use "clean" .net project - you need use sources, or recompile library with this defines and put by hands. Or use 0.9 version from master - there is just "netManager.StatsEnabled = true". Also this is doesn't relate to "usage of NetPacketProcessor"

**Comment by kascodingNL** [comment]
Ah okay, i will try it.

**Comment by kascodingNL** [comment]
@RevenantX we have upgraded the LiteNetLib into 0.9, and we enabled Statistics succesfully!

Thank you!
