### ISSUE TITLE
Disconnecting client after NatIntroductionSuccess in NAT hole punching scenario

### ISSUE THREAD

**Issue by amazedevil** [RevenantX/LiteNetLib#366]
I've met a disconnection scenario, it's quite unstable, but happens not so rarely. I'm using NAT hub server (dotnetcore on Linux) to connect two clients (Android phone and Unity editor on Windows 10) with NAT hole punching, it's quite a sample-like setup (HolePunchServerTest), with almost all listening got from there. In _some_ cases client that is connecting to other client, is like getting NatIntroductionSuccess event, but after that receiving connection request, accepting it and receiving more and more ones. All in all it ends with "connection failed". Maybe later I'll try to reproduce it in some test environment, but that's what I know for that moment. Is that somehow expected? Thanks!

**Library version**: 0.9.2

**Framework**: Unity + Unity editor + dotnetcore

**OS**: Unity: Android, Unity editor: Windows 10, dotnetcore: Linux

**Comment by RevenantX** [comment]
There is can be some problems when you try connect simultaneously from both sides (client1 to client2 and client2 to client1). I will look into this.

**Comment by sondreb** [comment]
Running the HolePunchServerTest in LibSample also results in similar behavior. 

![image](https://user-images.githubusercontent.com/309938/83438182-43782c00-a441-11ea-883f-7745b3d3474e.png)

**Comment by sondreb** [comment]
Running manually from the bin folder works fine. It's deterministic, running F5 debugging it will fail, but running from bin folder it works every time:

![image](https://user-images.githubusercontent.com/309938/83438666-17a97600-a442-11ea-8c80-0a632a6ff102.png)

**Comment by RevenantX** [comment]
@sondreb i know about bug and what cause it. It's just a bit complex to do this in 2 hours :)

**Comment by RevenantX** [comment]
@amazedevil @sondreb should be fixed in master. You can check on your sides. Will push into new release a bit later.

**Comment by sondreb** [comment]
Great work, thanks! Gave you a couple of coffee 👍

**Comment by RevenantX** [comment]
@sondreb thanks!
