### ISSUE TITLE
private void ProcessEvent(NetEvent evt) - CPU 20% Loaded

### ISSUE THREAD

**Issue by nurbat** [RevenantX/LiteNetLib#367]
Information about bug or feature

While(true) PollEvents...

**Library version**: Latest

**Framework**:NetStandart 2

**OS**: Win

**Comment by RevenantX** [comment]
@nurbat this is wrong way to call PollEvents in simple while(true) loop. You must use Thread.Sleep() after poll or in case of Unity3d just call this in `Update` method.

**Comment by nurbat** [comment]
I not used Unity3d

**Comment by nurbat** [comment]
I Find, 
1. Options.Listener.ConnectionRequestEvent += OnConnectionRequest;
2. request.Accept(); without check if
Result: 20% cpu
