### ISSUE TITLE
"NetworkWritter" is obsolete 

### ISSUE THREAD

**Issue by andrfgs** [RevenantX/LiteNetLib#368]
Considering the decision of making `NetworkWritter` obsolete, what should be used instead? The documentation lacks an explanation of what would be a better substitute for it. Could you please add more information on the documentation regarding this issue? 

And thank you in advance for this amazing library.

**Comment by RevenantX** [comment]
@andrfgs why do you think that "NetworkWriter" (do you mean NetDataWriter) is obsolete?? I never said this.

**Comment by andrfgs** [comment]
I deepely apologize, Unity seems to have a very close class named `NetworkWriter` which I seem to have confused with `NetDataWriter`, as I had to use them both in the same project.

I'm very sorry for this confusion.
