### ISSUE TITLE
NetSerializer. Structs or classes?

### ISSUE THREAD

**Issue by kkjamie** [RevenantX/LiteNetLib#370]
In NetSerializer, the serialize & deserialize functions both state in the documentation ` Serialize struct ` but the type parameter constraints require it to be a  class. I had a case in my project where I wanted to serialize a struct using the netSerializer. Would this be possible? Should this be possible or just a mistake in the documentation?

```
/// <summary>
/// Serialize struct to NetDataWriter (fast)
/// </summary>
/// <param name="writer">Serialization target NetDataWriter</param>
/// <param name="obj">Object to serialize</param>
/// <exception cref="InvalidTypeException"><typeparamref name="T"/>'s fields are not supported, or it has no fields</exception>
public void Serialize<T>(NetDataWriter writer, T obj) where T : class, new()
{
    RegisterInternal<T>().Write(obj, writer);
}
```

**Comment by RevenantX** [comment]
@kkjamie this is mistake in the documentation. Automatic serialization works only for classes. For structs you can implement "manual" serialization with `Serialize` `Deserialize` methods.

**Comment by RevenantX** [comment]
fixed mistake in documents
