### ISSUE TITLE
Sudden external port change in the middle of NAT connection

### ISSUE THREAD

**Issue by amazedevil** [RevenantX/LiteNetLib#371]
I've built NAT hole punching infrastructure: hub server (hs) and client1 (c1) are on the same cloud machine and I'm trying to connect with client2 (c2) over hs (I know I can connect to c1 directly, but because of sepcific reasons it should be configured that way), which is Unity app in editor.

1) c1 and c2 designated as host and client, its ok (it doesn't matter who is who, in any case it goes the same way)
2) c1 sends nat punching message to EP with port X
3) c2 sends nat punching message to EP with port Y
4) c1 receives nat punching message from EP with port Z
5) c2 receive connection request from c1

The problem is - punching message from step 2 are gone, c2 doesn't receive it at all.

I don't know if it's expected behaviour, than maybe somebody know how it should be handled properly? Thanks!

**Library version**: 0.9.2.1

**Framework**: Unity (editor on Windows), dotnetcore

**OS**: Windows, Linux

**Comment by RevenantX** [comment]
@amazedevil this is known thing. There is some little "cheat" used for some routers. From one of sides (in your case c2) sets socket.ttl to low value - to just open port on router. Some routers with greater TTL value can receive something like "connection closed" message - and close this port for incoming messages.

**Comment by amazedevil** [comment]
I see, thank you! Do you have any thoughts, how it can be handled properly?

**Comment by othman-fayed** [comment]
@RevenantX First of all, appreciate the work and effort. However, could you please put this TTL issue to come notes file in the project. I kind of wasted 2 days trying to figure out the issue! 😕

**Comment by RevenantX** [comment]
improved ttl hack.
