### ISSUE TITLE
error CS0029: Cannot implicitly convert type 'int' to 'LiteNetLibManager.SyncFieldInt'

### ISSUE THREAD

**Issue by Gui205** [RevenantX/LiteNetLib#372]
error CS0029: Cannot implicitly convert type 'int' to 'LiteNetLibManager.SyncFieldInt'

My code is something basic, so i dont understand why i got this error. MinProf return an int egal at 1 ... 

```csharp

public int MinProf = 1;
    [Header("Weather Profil Sync Fields")]
    [SerializeField]
    protected SyncFieldInt m_profileIndex = new SyncFieldInt();

 void Start()
    { if (IsServer)
        {
            m_profileIndex = MinProf;
        }

    }
```

**Library version**: 0.9.2.2

**Framework**: Unity

**OS**: Windows

**Comment by RevenantX** [comment]
@Gui205 this is wrong repo for this bug. https://github.com/insthync/LiteNetLibManager
