### ISSUE TITLE
Delay between players

### ISSUE THREAD

**Issue by Eloren1** [RevenantX/LiteNetLib#373]
If I stop the game, a delay appears between the players. How can it be removed? This delay also appears on Android when I close the game.

https://youtu.be/XiJBS4bkTXY

**Comment by RevenantX** [comment]
@Eloren1 you missed repo for bug: https://github.com/RevenantX/NetGameExample

**Comment by Eloren1** [comment]
But this also applies to the library. Is there any way to fix this? I may have the same bug

**Comment by RevenantX** [comment]
@Eloren1 this doesn't apply to library. This applies to implementation of game

**Comment by RevenantX** [comment]
@Eloren1 also always use "Run in backround" setting in unity. Or you will have some "bugs" like this.

**Comment by Eloren1** [comment]
OK, can I ask another question? Let's say I made a game. How to move it from a localhost to the server? Which side should I look at? Should it be some kind of build?

**Comment by RevenantX** [comment]
@Eloren1 there is chat link at main page for that questions https://discord.gg/FATFPdy
