### ISSUE TITLE
SubscribeReusable NetPeer is null

### ISSUE THREAD

**Issue by juhanikarlsson** [RevenantX/LiteNetLib#376]
Hi, 

I subscribe to 
netPacketProcessor.SubscribeNetSerializable<OnExamplePacket, NetPeer>(OnExamplePacket);
or
netPacketProcessor.SubscribeReusable<OnExamplePacket, NetPeer>(OnExamplePacket);

and for some reason the NetPeer is null. Is this expected behaviour?
Any idea what I´m possibly doing wrong : ))

This is with the latest release.

**Comment by RevenantX** [comment]
@juhanikarlsson hi! Look in example. Seems that you just not passing peer into ReadAllPackets method - but you should. Also use discord better for questions.

**Comment by juhanikarlsson** [comment]
Hi, 
You're right - I feel so stupid now : ) Thank you for your help!
Next time --> Discord!

Cheers,
- J
