### ISSUE TITLE
Why max channels count is 64?

### ISSUE THREAD

**Issue by anchernyaev** [RevenantX/LiteNetLib#377]
In our task, we need to use more than 64 channels in one connection. This is necessary to preserve the order of messages within one channel and not to develop protocol over the connection.

Can we increase the library limit on the number of channels from 64 to 256 in our fork? 
Will this break the logic of the library or not? Why is current limit set at 64? Is this the technical limitations of sockets?

**Comment by RevenantX** [comment]
this limitation is to reduce header size. (64 channels * 4 types of messages = 256 = 1 byte). And this is 64 per type of message. This is very rare usecase of 64 and more channels (many libraries allows only 32 channels maximum)

**Comment by anchernyaev** [comment]
I changed type of ChannelCount from byte to int and incrased it to 2500 of single connection in my prototype.

After it i faced with problem that the throughput of one channel decreased by 2 times relative to 64 channels. I incrased DefaultWindowSize in NetConstansts from 64 to 512 and now i have acceptable 
 performance with 64 channels and 2500.
Maybe I should pay attention to some other settings?

I plan to use 1 channel for transmission maximum 10 mbit/sec traffic. It can be lower, on most channels. 
If I run into maximum network throughput, i start thin out traffic on server side 
using message delivery notification from the client. But in some case (if i dont incrase DefaultWindowSize) i faced with problem that connection does not use maximum network throughput and and messages are not delivered on minimal time.

**Comment by RevenantX** [comment]
@anchernyaev what do you trying to achieve? If you need best speed and throughput use TCP it is best for high speed. RUDP is designed for different things.

**Comment by anchernyaev** [comment]
I need p2p connection for translate many video streams for clients and servers, which use NAT. Client and server can use 1gbit network, so they can send and receive 100-200+ streams. I want to translate 1 stream to 1 channel, is it right idea?

**Comment by RevenantX** [comment]
@anchernyaev if you use only ReliableChannel for this - is better to use TCP. It will be much faster.

**Comment by anchernyaev** [comment]
@RevenantX i need udp hole punching for punch NAT. How can i use TCP?

**Comment by RevenantX** [comment]
@anchernyaev https://en.wikipedia.org/wiki/TCP_hole_punching

**Comment by RevenantX** [comment]
@anchernyaev or use UDP protocol that designed for large data transfers like QUIC or uTP

**Comment by anchernyaev** [comment]
@RevenantX Do you know any good library for TCP pounching like this for UDP?

**Comment by RevenantX** [comment]
@anchernyaev you can do this with simple TCP sockets. You don't need any libraries.
