### ISSUE TITLE
Usage of ReaderWriterLockSlim without try...finally

### ISSUE THREAD

**Issue by Lunatix89** [RevenantX/LiteNetLib#378]
I just had a look at the current master and read a little bit through the code and I saw a couple of places where a `ReaderWriterLockSlim` was used without `try...finally` blocks.  

So for example, if whatever exception is being raised in the method `NetManager.Connect(IPEndPoint, NetDataWriter)` between `EnterUpgradeableReadLock` and `ExitUpgradeableReadLock` the lock will be broken from there on.  

Is this by design or maybe just a typo?

**Library version**: [commit id (17acdd9)]

**Framework**: [Unity]

**OS**: [Windows]

**Comment by RevenantX** [comment]
@Lunatix89 this is by desing. I checked all places and chance of error between that locks is epically small. If someone will hit such error i will add try/catch
