### ISSUE TITLE
Unity game crash on Android

### ISSUE THREAD

**Issue by vanoseva** [RevenantX/LiteNetLib#38]
Hi!

I have a problem when run my game (using Unity engine) on android. My game crashed when build with Scripting Backend IL2CPP, but working on Mono2x.

Enviroment:
- OS: macOS Sierra 10.12.3
- Unity 5.5.0f3
- LiteNetLib: latest commit fd58793

If I disable the code lines on NetSocket.cs (see the sample project in [LiteNetUnity.zip](https://github.com/RevenantX/LiteNetLib/files/835482/LiteNetUnity.zip)), game run without crash:

`_udpSocketv4.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.DontFragment, true);`
`_udpSocketv6.SetSocketOption(
                        SocketOptionLevel.IPv6, 
                        SocketOptionName.AddMembership,
                        new IPv6MulticastOption(MulticastAddressV6));`

I don't know what happen when disable it :)

Sorry for my poor English!

**Comment by RevenantX** [comment]
This is unity bug (IL2CPP). Better will be post this at unity bugtracker. 
I can add ```#if ... #endif``` but IPv6 users will remain without ```DiscoveryRequset``` method. And will have some other issuses.

**Comment by vanoseva** [comment]
Ah, this is bug of unity, I don't realize it 👍 

What kind of "some other issuses"? It will effect to use this library for multicast (using only IPv4) and natpunchthrough?

**Comment by RevenantX** [comment]
Try leave ```don't fragment``` option or use:
```csharp
_udpSocketv4.DontFragment = true
```
instead of
```csharp
_udpSocketv4.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.DontFragment, true);
```
It this helps - notify me)

**Comment by vanoseva** [comment]
I will try soon. Thank for your help.

**Comment by vanoseva** [comment]
Hi, sorry for my late.

In my old enviroment, it runs without crash when use your suggest:
`_udpSocketv4.DontFragment = true`

I my new enviroment, I upgraded Unity to latest version (5.5.2f1), use latest commit f62cfa1, and because Unity not support (Protocol option not supported), I disable only following code:
```
_udpSocketv6.SetSocketOption(
                        SocketOptionLevel.IPv6,
                        SocketOptionName.AddMembership,
                        new IPv6MulticastOption(MulticastAddressV6)); 
```
build Android with enabled IL2CPP support, and it' working!

Again, thanks for your help 👍

**Comment by RevenantX** [comment]
I make some updates. Try from latest version. This call almost always been in "try ... catch". Why it crashes...

**Comment by RevenantX** [comment]
Marking as fixed.

**Comment by phaseOne** [comment]
When building with IL2CPP on iOS, the above IPv6 `SocketOptionName.AddMembership` is causing a EXC_BAD_ACCESS crash.

Someone has submitted a bug report: https://forum.unity3d.com/threads/setsocketoption-for-ipv6-is-crashing.463832/

Can be worked around for those who don't need IPv6 by setting the `if` statement to `true` in [NetSocket.cs at line 130](https://github.com/RevenantX/LiteNetLib/blob/0.7.3/LiteNetLib/NetSocket.cs#L130).

**Comment by RevenantX** [comment]
@phaseOne better will be disable ipv6 multicasting by commenting line.

**Comment by dzmitry-lahoda** [comment]
Have somebody tried unmodified LiteNetLib iOS .NET Standard 2.0 IL2CPP on Unity 2018.1+ since than?
