### ISSUE TITLE
Use LEB128 encoded integers in NetDataReader/Writer

### ISSUE THREAD

**Issue by CallumDev** [RevenantX/LiteNetLib#383]
`PutArray` and `Put(string)` methods can be improved by implementing `PutVariableUInt` and `GetVariableUInt` methods, saving a few bytes per array and string.

See wikipedia page for LEB128 for pseudocode: https://en.wikipedia.org/wiki/LEB128

**Comment by RevenantX** [comment]
@CallumDev PutArray uses ushort. Also this can add more CPU usage for that encoding/decoding
