### ISSUE TITLE
Always uses smalles MTU 507 bytes on Mac?

### ISSUE THREAD

**Issue by vis2k** [RevenantX/LiteNetLib#388]
Hey,
I am combining several messages into one with DOTSNET + LiteNetLib.
For some reason my max MTU is always 507 bytes, even when server connects to client on same computer.

I just checked the code, and NetPeer constructor calls SetMTU(0), which would explain it.
I am sending over unreliable channel & reliable channel.

Am I doing something wrong?
If I send a message > 507 bytes then I get a TooBigPacketException.

But I am pretty sure that 1400 MTU should work on my local machine?

Thanks :)

**Comment by RevenantX** [comment]
@vis2k MTU is growing up after some time. (1-4 seconds). It will be always minimal from start

**Comment by vis2k** [comment]
Ok thanks.
