### ISSUE TITLE
Issue on queue lock

### ISSUE THREAD

**Issue by MarcoGuzzetti** [RevenantX/LiteNetLib#39]
Hi,
I have some problems with lock on queue(s), in particular when library check if queue.Count == 0 (eg. **SimpleChannel** on **SendNextPacket** method).
For resolving the issue I've moved the lock before the if statement. It's the correct way? Can you verify?

Plus question: There's some method for flushing the queue manually? Because if I call the client.Stop() method after the Send() method, the packet cannot arrive to destination. For now, in my implementation, I have settet the Update() on NetPeer file public and I call it before every Stop.

Thank you

**Comment by RevenantX** [comment]
Hi! 
> I have some problems with lock on queue(s), in particular when library check if queue.Count == 0 (eg. SimpleChannel on SendNextPacket method).

If you calling Update by hands from main thread then you will get problem)

>  There's some method for flushing the queue manually?

No. But if you need i can add.

**Comment by MarcoGuzzetti** [comment]
Thanks for the quick response.

> If you calling Update by hands from main thread then you will get problem)

Not always. If I make a Parallel.ForEach and i try to send 1000000 packet sometimes it happens (even without calling Update by hand). Why not use a ConcurrentQueue? From my test it seems fast as the "classic" queue with lock.

> No. But if you need i can add.

If you can it will be awsome! Thank you!

**Comment by RevenantX** [comment]
> Why not use a ConcurrentQueue?

Unity3d doesn't support it.

**Comment by fenglinnet** [comment]
Maybe a switch queue is a better choice for both produce and consume

**Comment by RevenantX** [comment]
Added flush and fixed locks.
