### ISSUE TITLE
Exception when trying to serialize List

### ISSUE THREAD

**Issue by Skleni** [RevenantX/LiteNetLib#390]
I'm trying to get the serialization of lists to work that was introduced with version 0.9.3
I'm already using the updated Nuget package - thank you for the fast fix after the problem reported by @feliwir!

This is the class I want to send:

```csharp
  public class SkirmishOrderPacket
  {
      public uint Frame { get; set; }
      public List<Order> Orders { get; set; }
  }
```
using this code:

```csharp
_writer = new NetDataWriter();
_processor = new NetPacketProcessor();            
_processor.RegisterNestedType<Order>(WriteOrder, ReadOrder);
_processor.Subscribe<SkirmishOrderPacket>(
    packet => { // handle packet },
    () => new SkirmishOrderPacket());

...
var packet = new SkirmishOrderPacket()
{
    Frame = scheduledFrame,
    Orders = orders
};

_writer.Reset();
_processor.Write(_writer, packet);
_manager.SendToAll(_writer, DeliveryMethod.ReliableOrdered);
```

However, I'm getting an `InvalidTypeException` with the message `Unsupported type: List<OpenSage.Network.Packets.SkirmishOrderPacket>` (I guess from [here](https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/Utils/NetSerializer.cs#L36)).

What's strange is that the message talks about `List<SkirmishOrderPacket>`, which I'm not using anywhere (rather `SkirmishOrderPacket` contains a list of orders).

**Library version**: 0.9.3.1

**Framework**: dotnetcore

**OS**: Windows

**Comment by RevenantX** [comment]
@Skleni this is strange. I tested this case (also added to tests). Maybe you can create minimal example with problem code?

**Comment by RevenantX** [comment]
@Skleni ah i found, i forgot to add support of this to RegisterNestedType with static methods.

**Comment by Skleni** [comment]
Thanks!
