### ISSUE TITLE
Too many build targets

### ISSUE THREAD

**Issue by Kaladrius2trip** [RevenantX/LiteNetLib#396]
Maybe should make one(or few) main target platform ?
Too many precompiler directives = too hard for implement new feature and improvements and also code readability in future.
Or separate old target compatibility version in own repository ?
What do you think about it ?

P.S. For example async/await, spans, read-only struct, and many other feature, too hard implement now.

**Comment by RevenantX** [comment]
There isnt too many precompiler directives. Only for netcore and unity specific bugs. Also async/await doesnt make sense in this library because all operations already async

**Comment by Kaladrius2trip** [comment]
Ok it's really not need for main library methods for now.
