### ISSUE TITLE
Multicast problem

### ISSUE THREAD

**Issue by wyrex** [RevenantX/LiteNetLib#4]
I tested LiteNetLib using Mono on Archlinux and on Windows 10 - hello world works over internet and locally. Today I gave the program to my friend who has Windows 7  and he gets error everytime there is to NetClient.Start() or NetServer.Start(). Samples don't work either.

 He gets this error in these lines in NetSocket.cs: 
```
_udpSocketv4.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.AddMembership, new MulticastOption(MulticastAddressV4, IPAddress.Any));
```
https://cdn.discordapp.com/attachments/210107559720386560/225974463064178690/unknown.png

```
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
   at System.Net.Sockets.Socket.setMulticastOption(SocketOptionName optionName, MulticastOption MR)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Object optionValue)
   at LiteNetLib.NetSocket.Bind(Int32 port) in E:\Projects\LiteNetLib\LiteNetLib\NetSocket.cs:line 96
   at LiteNetLib.NetBase.Start(Int32 port) in E:\Projects\LiteNetLib\LiteNetLib\NetBase.cs:line 188
   at Netcode.Server.Listen(Int32 port, Int32 maxConnections) in E:\TEMP\Telegram\NetCodes\NetCode\Server\litenet_server.cs:line 39
```
He CAN succesfully bind using this C# example code:
https://social.msdn.microsoft.com/Forums/en-US/d9951293-e5b6-4d95-ae81-e0f972d4b18d/cant-bind-a-udp-socket-to-a-port?forum=netfxnetcom

No idea why this line fails for him but his router is very restrictive.

**Comment by RevenantX** [comment]
Try fixed version from master.

**Comment by Shintaja** [comment]
So this happend, https://cdn.discordapp.com/attachments/210107559720386560/225988531896582144/unknown.png

**Comment by Shintaja** [comment]
@RevenantX So this happened, https://cdn.discordapp.com/attachments/210107559720386560/225988531896582144/unknown.png

**Comment by RevenantX** [comment]
@wyrex Thank you for info. Seems this is bug in Windows or old .NET or with some rights. Added try catch and log.

**Comment by wyrex** [comment]
@RevenantX It works after your last commit and gives no exception.

**Comment by RevenantX** [comment]
Okay) Thanks for bug reporting. Closing.
