### ISSUE TITLE
"Unreliable packet size exceeded maximum" for a reliable sequenced packet

### ISSUE THREAD

**Issue by aienabled** [RevenantX/LiteNetLib#403]
Hello!
When attempting to send a packet with `DeliveryMethod.ReliableSequenced` that requires fragmentation, an exception is thrown "Unreliable packet size exceeded maximum of...".

Here is the line of code resposible for this exception:
https://github.com/RevenantX/LiteNetLib/blob/1c33ccd583107ca7d455ddf5b5a3546af1a418ac/LiteNetLib/NetPeer.cs#L532
as we can see it doesn't handle case `DeliveryMethod.ReliableSequenced`.
If this is expected behavior, please correct the exception message.

Regards!

**Comment by RevenantX** [comment]
@aienabled this is expceted behaviour

**Comment by aienabled** [comment]
Then maybe it would be best to adjust the exception message to make it clear that it affects not only unreliable packets but also reliable sequenced packets.

But that's what I was afraid of...Is it possible to implement support for fragmented reliable sequenced packets? Or you have a concern that it's just not reasonable to have fragmented packets for sequential packets as it's not a good idea to send such large packets rapidly in a sequence?
I'm finally trying to replace Lidgren3 with LiteNetLib in our MMO game and this is one of the few major problems that I have.

**Comment by fdsagizi** [comment]
> @aienabled this is expected behavior

Not. 
In your docs, you say: Automatic fragmentation of reliable packets

**Comment by RevenantX** [comment]
@fdsagizi this doc was not updated after "ReliableSequenced" was added

**Comment by aienabled** [comment]
@RevenantX regarding the last commit:
1. `allowd`—typo in the exception text.
2. Please consider expanding the XML comment here to mention that with this delivery method the packet cannot be fragmented https://github.com/RevenantX/LiteNetLib/blob/7f9005a354cc2c1f228f16fd12eb3ff88a38a3d1/LiteNetLib/NetConstants.cs#L28
Maybe even consider renaming `ReliableSequenced` to something like `ReliableSequencedNoFragmentation` to ensure that nobody will attempt sending large packets with it... :-) I'm not serious but it could be a frustrating surprise to someone. An expanded XML comment would be sufficient!

Regards!
