### ISSUE TITLE
Check Which Channel Was Recieved On

### ISSUE THREAD

**Issue by Moe-Baker** [RevenantX/LiteNetLib#406]
Is there any way to check which channel the data was received on in this callback? the channel as in the byte value of course.

```csharp
void OnNetworkReceive(NetPeer peer, NetPacketReader reader, DeliveryMethod deliveryMethod);
```

**Library version**: [(0.9.3.2)]

**Framework**: [Unity, dotnetcore]

**OS**: [Linux, Windows]

**Comment by RevenantX** [comment]
@Moe-Baker there is currently no way to check which channel the data was received on, because in 99% cases this information is useless

**Comment by Moe-Baker** [comment]
I imagined that might be the case, my use case is somewhat unique after all, I'm using LiteNetLib for a relay server to bypass NATs and the such, so clients can send messages to each other through the relay.
I need that channel so I can have the server forward the clients' messages on the same channel they sent the data on.
Any chance for adding this? One little byte never hurt anyone :) .

**Comment by RevenantX** [comment]
@Moe-Baker for relay server it is better just to use simple udp socket because it will fit this needs by 100%. Also it will be much faster than "relaying" all packets through LiteNetLib

**Comment by Moe-Baker** [comment]
That's probably true, I'm just not keen on implementing my own RUDP protocol.
But nonetheless, it's not an essential feature for me, and not many more people are gonna need it anyway, so I'll try to implement it from the source.
Thank you for your support.

**Comment by RevenantX** [comment]
@Moe-Baker you don't need own RUDP protocol. You can pass LiteNetLib packets through simple UdpSocket by just sending all incoming bytes to client. Routing table you can store from LiteNetLib NAT pucnh module in Dictionary<IPEndPoint, IPEndPoint>

**Comment by Moe-Baker** [comment]
But how would I ensure reliability? .net's UDP Sockets don't have any form of reliability, right ?

**Comment by RevenantX** [comment]
@Moe-Baker yes, but if you just "relay" all packets from one LiteNetLib client to another it will works - because LiteNetLib maintains reliability.

**Comment by Moe-Baker** [comment]
Wait, what? you lost me, I think I gave you an insufficient explanation for what I want to do.
I'm trying to make a relay-based game networking service, something like Photon Unity Networking (PUN), so I have a game server running on an EC2 VPS and multiple clients connected to that VPS, the clients will communicate with each other through the game server by sending it packets that designate the target client to receive them.
I want the game server and client to utilize all of LiteNetLib's features: reliability, sequencing, channels, .... etc.
So, in this context, I'm not sure how I will implement UDP Sockets alongside LiteNetLib.

**Comment by RevenantX** [comment]
@Moe-Baker i talked about scheme when you just connect two clients that behind restricted NAT through relay
like LiteNetLib client1 -> simple udp relay -> LiteNetLib client2
It will work like SOCKS proxy server.

**Comment by RevenantX** [comment]
@Moe-Baker also info about channel already there it just not passed to function
