### ISSUE TITLE
Unity complains about missing nunit?

### ISSUE THREAD

**Issue by eddieparker** [RevenantX/LiteNetLib#407]
Cloning the repo and putting it in the Unity Asset folder yields a bunch of errors like:

```Assets\3rdparty\LiteNetLib\LiteNetLib.Tests\CommunicationTest.cs(9,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)```

I see that I already have unity's "custom NUnit" installed but that doesn't seem to work, and I'd rather not muck with your repo just to get it to work (deleting the tests seems to do the trick).

Is there a better way to do this?

**Comment by RevenantX** [comment]
@eddieparker you need to put only "LiteNetLib" folder to unity. Also for questions use https://discord.gg/FATFPdy
