### ISSUE TITLE
Is this lib support Symmetric NAT ?

### ISSUE THREAD

**Issue by amin10440** [RevenantX/LiteNetLib#418]
4 general types of NAT devices (I say general because NAT behavior isn't really standardized): Full-Cone NATs, Restricted-Cone NATs, and Port-Restricted-Cone NATs. NAT traversal will not work with Symmetric NATs, which are found mostly in corporate networks for enhanced security. is this lib support  A Symmetric NAT to Symmetric NAT traversal

**Comment by RevenantX** [comment]
No this is almost impossible on UDP level. Library cannot support unsupported things. Game will work with dedicated server but direct P2P isn't possible behind symmetric nat

**Comment by amin10440** [comment]
I thing its possible there is a lib in go work with  Symmetric NAT( [Gole](https://github.com/shawwwn/Gole)).
in this paper you can find [solutions()](https://www.researchgate.net/publication/228411948_A_New_Method_for_Symmetric_NAT_Traversal_in_UDP_and_TCP)

**Comment by RevenantX** [comment]
@amin10440 this is unstable and based on behaviour only of some symmetric NATs and a bit hard to implement soltions.
 But you can always do this at application level if you really need.
Anyways It is better just to use relay servers. They cost not so much. And some platforms like Steam has already this mechanism inside
