### ISSUE TITLE
C# 4 and .NET 3.5

### ISSUE THREAD

**Issue by backfromexile** [RevenantX/LiteNetLib#419]
I understand that it is important to support Unity. However, a lot changed since a few years ago.

Unity 2018.1 made .NET 4.6 the standard runtime with C# 6.0 support, while .NET 3.5 is legacy.
Since Unity 2018.3, .NET 4.6 is the standard runtime and even has C# 7 (I think even 7.3?) support.
There is even .NET Standard 2.0 support since at least Unity 2018.2.

I think it would be time to drop the C# 4 and .NET 3.5 constraints for v0.9.

**Comment by RevenantX** [comment]
@backfromexile there is some devs that develop multiplayer mods for "old" released games on Unity with .NET 3.5. Also newer .NETs doesn't give much things (sure, there is some) that can improve library.

**Comment by backfromexile** [comment]
While that's true, I don't see why there shouldn't be a "legacy" version for .NET 3.5 and an in development one for .NET 4+. You are already targeting .NET Standard 2.0 anyways, which 3.5 doesn't support at all, so there is a need for different compiler directives right now.

Well, newer .NET and C# versions give us access to a few useful things, for example:
- shorthand getter/setter expressions (=>)
- a proper enum generic type constraint, this could be useful for NetDataReader/Writer for first-class support of enums (either safe/unsafe) without the need to manually cast them to their base type
- Nullable reference types (C# 8.0) -> this is supported in Unity 2020.2+ as well
- Interpolated strings

While these things don't all improve the functionality library, they definitely help with maintaining and keeping the library up to date.

**Comment by RevenantX** [comment]
@backfromexile well maybe after 3 years (2018.3) it is a good idea.
