### ISSUE TITLE
Could I use more threads on _threadv4 ?

### ISSUE THREAD

**Issue by refox1** [RevenantX/LiteNetLib#423]
I found that only one thread was used to listen to the socket ,
performance may be wasted on multicore CPUs.
Thank you very much!

**Comment by RevenantX** [comment]
@refox1 there is no sense of more threads because low level receive method is synchronous. Also main performance problem will be from game logic. Also lesser CPU threads allows to run multiple server instances on one machine (thats why there is Manual mode)

**Comment by refox1** [comment]
hi RevenantX , thank you for your reply,
you are right in most cases , but only one thread is not enough for lockstep games, it's huge net package.
and the best number is CPU cores*2 threads by IOCP team answered. ok ,I'm not here to discuss this problem.
Now I tried to reform the network synchronizer to achieve the optimal ,
it's works good in multi threads, but only one logic thread can be used, it's not lock data there,
so I'm not clear whether the logical part will affect the network throughput.
I'm testing it recently. I'll let you know if some new ,
thanks again.
