### ISSUE TITLE
Question: Custom serializer with a nested List<INetSerializable>

### ISSUE THREAD

**Issue by Racso** [RevenantX/LiteNetLib#425]
Hello.

I'm trying to model this scenario for serialization:

```
class A
{
    public List<B> objectsB;
}

class B : INetSerializable
{
    public List<C> objectsC;

    public void Serialize(NetDataWriter writer)
    {
        // How should I serialize objectsC?
    }

    public void Deserialize(NetDataReader reader)
    {
        // How should I deserialize objectsC?    
    }
}

class C : INetSerializable
{
    public int Data;

    public void Serialize(NetDataWriter writer)
    {
        writer.Put(Data);
    }

    public void Deserialize(NetDataReader reader)
    {
        Data = reader.GetInt();
    }
}
```

As you can see, I'm missing the central piece: serializing class B. For that, I need to manually serialize a List<C>, but I can't find a way to do it.

Is what I'm trying to achieve possible? Thanks a lot for the help!

**Comment by RevenantX** [comment]
@Racso just put in writer list count and serialize items. like:
```cs
writer.Put(list.Count);
for(int i = 0; i < list.Count; i++)
{
    list[i].Serialize(writer);
}
```
And read with same logic.
Also for question better use discord instead of spawning issues: https://discord.gg/FATFPdy
