### ISSUE TITLE
Put/Get objects

### ISSUE THREAD

**Issue by Clayrok** [RevenantX/LiteNetLib#426]
Hi,

First, thanks a lot for your work, this library is amazing and is actually my first contact with networking :)

I tried to make a "request" system where the client can ask the server to invoke a request and back.
When a packet is sent it contains the request id (int) and all the needed parameters for the request function.
The problem is: as we have PutInt, PutBool, PutString, GetInt, GetBool, GetString I have so many if...else if...else if... else if... in my "Send" "Receive" methods. I know I could use a byte array but do you think it would be a good idea to have PutObject(object) and GetObject(size) in NetPacketWriter and NetPacketReader?

I'm a junior programmer so I don't have a lot of experience, I hope I don't say dumb things :)

Thanks again for the library!

Have a great day!

**Comment by RevenantX** [comment]
@Clayrok this is called "Serialization". And there is simple but fast build-in serializer - https://revenantx.github.io/LiteNetLib/articles/netserializerusage.html and documentation for it. Also you can use any other know serializer (Protobuf, MessagePack, Flatbuffers, etc)
