### ISSUE TITLE
SendNatIntroduceRequest() request fails because GetLocalIp() in NetUtils.cs returns a private local ip of range 169.254.xxx.xxx in case of multiple NICs

### ISSUE THREAD

**Issue by timematcher** [RevenantX/LiteNetLib#43]
Hi

**Bug Description:**
When there are **multiple** Network interfaces (WIFI and vmware network interfaces ), the **SendNatIntroduceRequest()** sends the incorrect Local IP to the server resulting in **SendNatIntroduceRequest()** never succeeding.

**Scenario detail:**
The problem is only produced when:

1. You separate out the Server component and client component into separate console apps from the provided sample in **HolePunchServerTest.cs
[HolePunchServerTest.txt](https://github.com/RevenantX/LiteNetLib/files/862629/HolePunchServerTest.txt)
**
2. You have multiple interfaces (when you have Vmware installed along with a WIFI adapter connected to the internet) on your client machine A and B
3. You run the client console app (based on the code from **HolePunchServerTest.cs**) on Client machine A and client Machine B
4. Your client machines A and B are both located on the same network and both are connected to the internet via their wireless network adapters.
5. Both have multiple virtual network adapters (in my case they exist because of VMWARE) but the situation can exist because of any 3rd party VPN software.
6. You run the server component on a machine on a (potentially) different network with a public IP address and an open/forwarded port (preferably on a different network than the client machines' network so that HOLD punching can be properly tested).
 
**What really happens?**

1. The **GetLocalIp()** method in **NetUtils.cs** class will return a private local ip address i.e **169.254.xxx.xxx** while the correct IP on your WIFI card would be something like **192.168.xxx.xxx**
2. The call **_c1.NatPunchModule.SendNatIntroduceRequest(new NetEndPoint(IpAddress, ServerPort), "token1");** will send that incorrect IP **169.254.xxx.xxx** as localEndpoint to the server.
3. As a result both client machines A and B will report their incorrect local IP Address as **169.254.xxx.xxx** , to the server, while their original IP address on their WIFI cards will probably be 192.168.10.3 and 192.168.10.4 (ip address for example case only, actual IPs may be of different range or values depending upon the router/DHCP server they get their IP addresses from)
4. The server will try to introduce machines with private IP address of range 169.254.xxx.xxx while the clients are necessary not listening on their corresponding local ip addresses.
5. As a result introduction will fail.
 

**FIX**

I fixed the problem by getting all local Ip address using the following piece of code i found somewhere on the internet.

**Put this method in Netutils.cs**

```
public static List<string> GetAllLocalIPAddresses(bool preferIPv4 = false)
        {
            return NetworkInterface.GetAllNetworkInterfaces()
                .SelectMany(adapter => adapter.GetIPProperties().UnicastAddresses)
                .Where(adr => adr.Address.AddressFamily == AddressFamily.InterNetwork && adr.IsDnsEligible)
                .Select(adr => adr.Address.ToString()).ToList();
        }

Next step: In NatPunchModule.cs locate the following method:
public void SendNatIntroduceRequest(NetEndPoint masterServerEndPoint, string additionalInfo)
        {
			if (!_netBase.IsRunning)
                return;

            //prepare outgoing data
            NetDataWriter dw = new NetDataWriter();
            var listOfIps = NetUtils.GetAllLocalIPAddresses();
            string networkIp = NetUtils.GetLocalIp(true);
            int networkPort = _netBase.LocalEndPoint.Port;
			
			NetEndPoint localEndPoint = new NetEndPoint(networkIp, networkPort);
			dw.Put(localEndPoint);
			dw.Put(additionalInfo, MaxTokenLength);

			//prepare packet
			var packet = _netBase.PacketPool.GetWithData(PacketProperty.NatIntroductionRequest, dw);
			_netBase.SendRawAndRecycle(packet, masterServerEndPoint);
	}

```
and replace the code with this method.

**New Code:**
```
public void SendNatIntroduceRequest(NetEndPoint masterServerEndPoint, string additionalInfo)
        {
            if (!_netBase.IsRunning)
                return;

            //prepare outgoing data
            NetDataWriter dw = new NetDataWriter();
            var listOfIps = NetUtils.GetAllLocalIPAddresses();
            string networkIp = NetUtils.GetLocalIp(true);
            int networkPort = _netBase.LocalEndPoint.Port;

            foreach (var address in listOfIps)
            {
                //NetEndPoint localEndPoint = new NetEndPoint(networkIp, networkPort);
                NetEndPoint localEndPoint = new NetEndPoint(address, networkPort);
                dw.Put(localEndPoint);
                dw.Put(additionalInfo, MaxTokenLength);

                //prepare packet
                var packet = _netBase.PacketPool.GetWithData(PacketProperty.NatIntroductionRequest, dw);
                _netBase.SendRawAndRecycle(packet, masterServerEndPoint);
            }

        }
```

Now I know that this is not an ideal solution. However, it gets the job done. The only cost is that it sends all the local ip addresses to the server and the server sends introduction packets to all these local ip addresses which might result in a little bit more traffic.

Maybe the code can be improved and fix is implemented by  @RevenantX  :)

Looking forward to hearing comments on this.
Regards
TM

**P.S I have also attached updated files with my modifications.** 

[NatPunchModule.txt](https://github.com/RevenantX/LiteNetLib/files/862613/NatPunchModule.txt)
[NetUtils.txt](https://github.com/RevenantX/LiteNetLib/files/862614/NetUtils.txt)

**Comment by boonkerz** [comment]
We should look at https://github.com/lidgren/lidgren-network-gen3/tree/a7468f4f1c0b337b814cc2c0f713a4459dc84299/Lidgren.Network/Platform

because its not the same on all platforms

**Comment by RevenantX** [comment]
I know about this bug. And i know how to fix it. I just don't have enough time for this.

**Comment by timematcher** [comment]
@boonkerz 
**The lidgren.network also suffers from the same issue.** 

As a matter of fact, I had a working app based on Lidgren.Network but the problem appeared when VMWARE or any 3rd party ap with virtual interfaces is installed then even the Lidgren's code get's the incorrect adapter (virtual adapter of vmware in this case).

I tested this again by copying code from [PlatformWin32.cs](https://github.com/lidgren/lidgren-network-gen3/blob/a7468f4f1c0b337b814cc2c0f713a4459dc84299/Lidgren.Network/Platform/PlatformWin32.cs)/ I called the **GetMyAddress()** from the Lidgren's code as linked. Here is the result.

![image](https://cloud.githubusercontent.com/assets/11568346/24252619/c124b62a-0fff-11e7-917a-628639bc6f53.png)

Now this result is incorrect because the following logic returns vmware adapter instead of the correct WIFI or ethernet adapter. Here is the relevant code which results in this behavior:
`/ make sure this adapter has any ipv4 addresses
                IPInterfaceProperties properties = adapter.GetIPProperties();
                foreach (UnicastIPAddressInformation unicastAddress in properties.UnicastAddresses)
                {
                    if (unicastAddress != null && unicastAddress.Address != null && unicastAddress.Address.AddressFamily == AddressFamily.InterNetwork)
                    {
                        // Yes it does, return this network interface.
                        **return adapter;** //<----This is faulty logic. and this yields the wrong interface.
                    }
                }
`

So essentially, we might take some inspiration from Lidgren's code but ultimately we need to test scenarios with additional virtual network intefaces which are always connected (like vmware etc) and ignore such adapters based on some intelligent logic.

Finally, @RevenantX  might have some interesting idead and I hope he finds some free time to look into this implement such a logic :)

**Comment by timematcher** [comment]
Based on [this answer on stackoverflow](http://stackoverflow.com/a/19198248/248700) I just found out that vmware network interfaces donot have a gateway address.

 So I came up with this code which seems to return the correct One) IP address:

```
public static List<string> GetAllLocalIPAddresses(bool preferIPv4 = false)
        {
            var ipAddresses = NetworkInterface.GetAllNetworkInterfaces()
                .Where(ni => ni.NetworkInterfaceType != NetworkInterfaceType.Loopback 
&& ni.NetworkInterfaceType != NetworkInterfaceType.Unknown
                && ni.IsReceiveOnly == false && ni.OperationalStatus == OperationalStatus.Up 
&& ni.SupportsMulticast == true
                && ni.GetIPProperties().GatewayAddresses.Count > 0)
                .SelectMany(adapter => adapter.GetIPProperties().UnicastAddresses)
                .Where(adr => adr.Address.AddressFamily == AddressFamily.InterNetwork 
&& adr.IsDnsEligible)
                .Select(adr => adr.Address.ToString())
                .ToList();
            return ipAddresses;
        }
```
Of course there is a change that a person may have set gateway address to a vmware virtual network adapter, lets say for experimentation purposes, then we can even explicitly rule out vmware network interfaces by excluding their names along with the gateway address exclusion logic:

```
public static List<string> GetAllLocalIPAddresses(bool preferIPv4 = false)
        {
            var ipAddresses = NetworkInterface.GetAllNetworkInterfaces()
                .Where(ni => ni.NetworkInterfaceType != NetworkInterfaceType.Loopback && ni.NetworkInterfaceType != NetworkInterfaceType.Unknown
                && ni.IsReceiveOnly == false && ni.OperationalStatus == OperationalStatus.Up && ni.SupportsMulticast == true
                && ni.GetIPProperties().GatewayAddresses.Count > 0)
                .SelectMany(adapter => adapter.GetIPProperties().UnicastAddresses)
                .Where(adr => adr.Address.AddressFamily == AddressFamily.InterNetwork && adr.IsDnsEligible
                && adr.Address.ToString().ToLower().Contains("vmware") == false)
                .Select(adr => adr.Address.ToString())
                .ToList();
            return ipAddresses;
        }
```

There are two other points which still need to be taken care of:

1. What if the code is being run inside a VM? What if vmware's network adapter is the only network adapter in the machine.?
2. What if there are other virtual network adapters in the system besides vmware which match all the conditions?

Answer to these could be the following:

1. We can add additional checks to see how many network adapters are in the system that are up, physical, and whether or not a virtual adapter is the only adapter in the system. Using a configuration value, we can control whether the app should dynamically use a different **exclusion criteria** when ruling out adapters and ip addresses.
2. We can make a list of all known vendors which provide and ship virtual network adapters use that list to exclude the network adapters. The list can be supplied via a config file instead of hard coding in the code so that exlcusion criteria can be dynamically adjusted.

@RevenantX When you get some time, please share your thoughts on this.

Cheers! :)

**Comment by timematcher** [comment]
I wrote a very long reply before I had to erase it and say.

**This commit really seems to fix the issue!** 🥇 

I still need to do a little more test with some scenarios and will report accordingly !

Great job! 👍

**Comment by RevenantX** [comment]
i just added gateway checking...

**Comment by RevenantX** [comment]
@timematcher i can close issue?

**Comment by timematcher** [comment]
@RevenantX  Yes I think we are good to go. Thanks for your great work! 👍
