### ISSUE TITLE
Where can i find information about the RUDP protocol used in this server ?

### ISSUE THREAD

**Issue by meiry** [RevenantX/LiteNetLib#433]
hey 
its not a bug but i will like to know if this server support RUDP and if yes , where can i read about the implemantion 
thanks

**Comment by RevenantX** [comment]
@meiry this is not "server" this is transport layer library. It works like RUDP but not RFC one. This is custom implementation of reliable/unreliable layer on top of simple UDP. Implementation is inside NetPeer/NetManager/NetSocket
