### ISSUE TITLE
NetManager error

### ISSUE THREAD

**Issue by timikrutik** [RevenantX/LiteNetLib#438]
Information about bug or feature
An error occurred in the NetManager class in line #1620. " _logicThread.Join();". Wrote _logicThread == null. The reference does not point to an instance of the class. The problem was solved by the usual null-value check: 

> if (_logicThread != null) _logicThread.Join ();

  instead of 

> _logicThread.Join();

**Library version**: [commit id (9f2a1d1a8244510d9ec502cc002bfdddba666d09) or release version (0.7.7.1)]

**Framework**: [.NET Framework]

**OS**: [Windows]

**Comment by RevenantX** [comment]
@timikrutik this is very strange because LogicThread cannot be null here. Maybe you calling Stop from different threads?

**Comment by timikrutik** [comment]
Yes, I use it))). Thanks a lot.

I'll try to fix it (different threads), or leave the check for a null value. So it seems to work
