### ISSUE TITLE
Network bandwidth

### ISSUE THREAD

**Issue by timikrutik** [RevenantX/LiteNetLib#439]
Maybe there is a way to somehow check the network bandwidth using LiteNetLib?

**Library version**: [commit id (9f2a1d1a8244510d9ec502cc002bfdddba666d09) or release version (0.7.7.1)]

**Framework**: [Mono, Unity, dotnetcore, .NET Framework]

**Comment by RevenantX** [comment]
@timikrutik No, because there is fixed window size, better use TCP for this. But you can try check it using RTT values. Also for questions use discord https://discord.gg/FATFPdy
