### ISSUE TITLE
GC issues

### ISSUE THREAD

**Issue by refox1** [RevenantX/LiteNetLib#440]
Hello,I found some problems in performance testing recently .
When data is very frequent, GC frequency is high.
I guess maybe "new NetPacket" or "new NetEvent" cause the problem.

so I tried a very simple program like this:
                
float fps = 0.05f;
if ( time > fps )
{
     time -= fps;
     dataWriter.Reset();
     dataWriter.Put( "chat message." );
     clientListener.netPeer.Send( dataWriter , DeliveryMethod.Unreliable );
}

and always call  "new NetPacket(size)" in NetPacketPool. that's why cause GC.
Is this a bug or am I using it incorrectly?
Thank you very much.

**Comment by refox1** [comment]
Oh,,I'm wrong , it's not new XXX() program ,
maybe C# socket bug.

send&recv 20pkgs./sec. 10-20k GC/sec .
too much GC.

**Comment by RevenantX** [comment]
Thing that you put string like this dataWriter.Put( "chat message." ); will spawn garbage at least.
Also use on both sides on receive Recycle() method or use NetManager.AutoRecycle. Also latest version in master fixes one problem that a bit increases garbage, so it will be less.

**Comment by refox1** [comment]
Ok I fixed my program.
and I found it's not new XXX() problem.

// echo msg.
float fps = 0.05f;
if ( time > fps )
{
     time -= fps;
     dataWriter.Reset();
     dataWriter.Put(  1  );
     clientListener.netPeer.Send( dataWriter , DeliveryMethod.Unreliable );
}
public void OnNetworkReceive( NetPeer peer , NetPacketReader reader , DeliveryMethod deliveryMethod )
{
     reader.Recycle();
 }

still high GC.
send&recv 20pkgs./sec. 10-20kGC/sec

so I guess maybe C# socket bug.
I write a simple socket to send&recv ,

simple  one thread socket like this:

int tmp = socket.Send( oBuffer.getBuffer() , oBuffer.getOffset() , len , SocketFlags.None , out error );
int count = socket.Receive( iBuffer.getBuffer() , iBuffer.getOffset() + iBuffer.getLen() , iBuffer.getSpace() , SocketFlags.None , out error );

send&recv 20pkgs./sec. 100bytes-200bytesGC/sec

so ,I'm pretty sure there's a problem somewhere in LiteNetLib.
Thank you very much.

**Comment by RevenantX** [comment]
@refox1 can you put full sources of your program?

**Comment by refox1** [comment]
Sure,I'll sort out and upload to GitHub.

**Comment by RevenantX** [comment]
@refox1 and where you watching GC/sec values? In Unity3d?

**Comment by refox1** [comment]
yes, In unity,

**Comment by refox1** [comment]
Maybe not exactly. I'm going to migrate to the command line.

**Comment by refox1** [comment]
https://github.com/foxgame/LiteNetLibTest/blob/main/LibSample.zip

empty gc 0.5-0.8k/sec.
simple send 20pkgs/sec. gc 1.5-1.8k/sec.
LiteNetLib send 20pkgs/sec. gc  5.xk/sec.

**Comment by refox1** [comment]
fixed simple send .
simple send 20pkgs/sec. gc 0.5-0.8k/sec.
C# socket works great, no GC.
BitConverter.GetBytes cause  GC.

**Comment by refox1** [comment]
I think I found the problem,,
Some API cause GC.

GC -> GetBytes(String) When overridden in a derived class, encodes all the characters in the specified string into a sequence of bytes. 
NoGC -> GetBytes(String, Int32, Int32, Byte[], Int32) When overridden in a derived class, encodes a set of characters from the specified string into the specified byte array.

**Comment by refox1** [comment]
And I found something in .Net Memory profiler.
byte[] ,IPAddress,String SocketAddress,Uint16[],IPEndPoint,String[],IntPtr[],Char[],
keep increasing.

**Comment by refox1** [comment]
I remove this function NetDebug.Write 
String[],string, reduced 1.xk/sec.

**Comment by refox1** [comment]
I removed this function NetDebug.Write
String[],string, reduced 1.xk/sec.

**Comment by refox1** [comment]
@RevenantX 
I found some serious problems.
I removed try/catch , and socket.Send/Receive instead of socket.SendTo/ReceiveFrom, GC disappeared magically.
You can try this.

**Comment by RevenantX** [comment]
@refox1 socket Send and Receive is isn't UDP methods. It dissappeared because it doesnt working

**Comment by RevenantX** [comment]
> so I think ,It should bind many sockets and one socket one user,that would be better.

No, this isn't good idea in UDP

**Comment by RevenantX** [comment]
Also check that things in Release mode not in Debug. Also there is NativeSockets mode in latest version without C# sockets GC things.

**Comment by RevenantX** [comment]
@refox1 And in Unity IL2CPP version and in .NET 5.0 socket allocations also fixed

**Comment by refox1** [comment]
@RevenantX  I tested it in.Net5.0 /IL2CPP release , also high GC, maybe C# bug.

**Comment by RevenantX** [comment]
@refox1 then if you really worried about such GC allocations (which is really low and doesn't affect performance too much) for server side - enable NetManager.NativeSockets (get latest version of library from Git master branch)

**Comment by refox1** [comment]
@RevenantX Better now, 20pkgs/sec , 2.xk GC/sec,
unity limit is 200bytes/ frame 10k/sec? in mobile mode .
It's still difficult to use a mobile as a host.

**Comment by refox1** [comment]
@RevenantX 
I checked some information, UDP can get some performance improvement through connect.
It's not real conncet , just bind Endpoint.also can use send/recv ,important is there are no GC.
So I think binding more sockets may improve the performance.
That's what some say, but I need to test it.

**Comment by refox1** [comment]
@RevenantX 
https://blog.grijjy.com/2018/08/29/creating-high-performance-udp-servers-on-windows-and-linux/

**Comment by refox1** [comment]
@RevenantX 
As I understand it, 
send/recv , bind->send-recv->send->xxx->close
sendto/recvfrom bind->send->close bind->recv->close,
send/recv should improve some efficiency.
and sendto/recvfrom maybe used for broadcast or uncertain port mainly .

**Comment by RevenantX** [comment]
@refox1 checked for allocations. 104b per send, a bit more on receive - and this is internal allocations. With NativeSockets 0 allocations

**Comment by refox1** [comment]
@RevenantX I tested in .net5/IL2CPP release,
Send/Receive works great and no gc.
In server I use Recvfrom to confirm endpoint first then connect client.

**Comment by refox1** [comment]
@RevenantX It also runs well on Android and no gc.

**Comment by RevenantX** [comment]
> 
> 
> @RevenantX
> https://blog.grijjy.com/2018/08/29/creating-high-performance-udp-servers-on-windows-and-linux/

Thanks. This is interesting. I will test this approach later
