### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by nongvantinh** [RevenantX/LiteNetLib#452]
I spend some time trying to understand **LiteNetLib library version 0.9.5.1** by experiment it with **_Godot engine mono version 3.3.2._**
And want to share my knowledge about this library to help someone get started quickly.

**Requiments:**
- [Godot engine mono version 3.3.2](https://downloads.tuxfamily.org/godotengine/3.3.2/)
- OpenGL 2.1 / OpenGL ES 2.0 compatible hardware
- MSBuild (from [Visual Studio Build Tools](https://visualstudio.microsoft.com/downloads/?q=build+tools)  or the [Mono SDK](https://www.mono-project.com/download/stable/))

**Getting started**
 - First open project and click _**build solution**_ in the top right corner.
 - Open the **Main** scene and uncheck **Server Build**
 - Now go to: **Project** -> **Export** -> **add export preset** for your desktop and click **Export Project**
 - Return to the editor and check **Server Build** then click **Play** or **F5**
 - After the server has been running, open your client build and run it.

**Results:**

1. [client connect to server.zip](https://github.com/RevenantX/LiteNetLib/files/7018411/test-lite-net-lib.zip)
- This example provider-client/server model.
- On application start, client connect to the server and the server print out a message when the client is trying to connect to.

2. [server accept client and send client a message.zip](https://github.com/RevenantX/LiteNetLib/files/7018436/test-lite-net-lib.zip)

- This example give you basic writing and reading using **LiteNetLib**.

3. [Server send client serializable packet.zip](https://github.com/RevenantX/LiteNetLib/files/7876299/test-lite-net-lib.zip)
- This example show you the way **LiteNetLib** serialize packets.
- On connected, Server send a snapshot packet to client.
- On client side, whenever client press "space" key it send a "ClientInputMessage" to server to demonstrate sending message from client side.

4. [Test memory leak.zip](https://github.com/RevenantX/LiteNetLib/files/7876331/test-lite-net-lib.zip)
- In the past, I tried yojimbo library (C# version, not C++), and it causes memory leak, This test make sure lite net lib pass the test about memory leak.

**Remark**:
- There is another way to serialize packet, by define your own static Serialize/Deserialize function, and send by using method 2, but I see it redundant, so I leave it alone.
- You can only use one method in 3 ways that I give above to serialize your packet.
- For games, method 3 is definitely the way to go.

I will add more example usage by adding more future base on the original project I give above.

**Comment by jfaz1** [comment]
Hi,

Have you gotten this working on Godot 3.4? I just opened an issue here:
https://github.com/RevenantX/LiteNetLib/issues/470

I tried on 3.3.2 and it works fine, however on 3.4 and above the game crashes.

**Comment by nongvantinh** [comment]
[image: Screenshot from 2022-01-16 09-34-17.png]
Godot 3.4.2 works fine!. Godot 4.0 is still in the development stage and
the mono build of 4.0 is broken.

Vào CN, 16 thg 1, 2022 vào lúc 03:44 jfaz1 ***@***.***> đã
viết:

**Comment by RevenantX** [comment]
This is issues place. I understand your help :) Thanks but better post in #tutorials_and_articles channel in discord
