### ISSUE TITLE
LiteNetLib is forcing a disconnection on "NetworkUnreachable" errors instead of waiting timeout

### ISSUE THREAD

**Issue by henriquelalves** [RevenantX/LiteNetLib#455]
My project is a mobile game, running on iOS and Android.

**Framework**: Unity

**OS**: Any

The problem I was investigating was the fact that there were a lot of disconnections during online matches in the game - more so than what we thought would be natural, since we set the reconnection timeout to 10s (plenty of time to ignore internet hiccups in most devices). When testing on the mobile device, quickly turning on and off "Airplane mode" would trigger a disconnection, with no connection retries whatsoever, with a "NetworkUnreachable" error. Further inspecting the source code of LiteNetLib I found this piece of code on the `SendRaw` method, in `NetManager.cs`:

```
                case SocketError.HostUnreachable:
                    if (TryGetPeer(remoteEndPoint, out fromPeer))
                        DisconnectPeerForce(fromPeer, DisconnectReason.HostUnreachable, errorCode, null);
                    CreateEvent(NetEvent.EType.Error, remoteEndPoint: remoteEndPoint, errorCode: errorCode);
                    return -1;
                case SocketError.NetworkUnreachable:
                    if (TryGetPeer(remoteEndPoint, out fromPeer))
                        DisconnectPeerForce(fromPeer, DisconnectReason.NetworkUnreachable, errorCode, null);
                    CreateEvent(NetEvent.EType.Error, remoteEndPoint: remoteEndPoint, errorCode: errorCode);
                    return -1;
```

Which forces a disconnection on "HostUnreachable" and "NetworkUnreachable" errors. We are tempted to simply change this `DisconnectPeerForce` to `DisconnectPeer`, thus not forcing a disconnection in those cases - but are there any drawbacks in doing so? What was the motive of forcing a disconnection in those cases?

**Comment by RevenantX** [comment]
@henriquelalves Added option to disable this behavior in this commit: https://github.com/RevenantX/LiteNetLib/commit/eaa0925bda9fd27b24d3ad2306f55075dad6641a

**Comment by henriquelalves** [comment]
That's exactly what we needed! We tested just removing the switch cases for the Network Unreachable and Host Unreachable errors, and the game really had a more reliable connection on Android devices (e.g. we could enter airplane mode quickly and back, without disconnecting from a match).
I believe this issue can be closed now that this commit is on the master branch.
