### ISSUE TITLE
The OnNetworkLatencyUpdate event is processed for the first time, and the latency value must be 0.

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#46]
Whether it is internal or external network

I would like to get a correct ping before the OnPeerConnected event call

**Comment by QiuBuZai** [comment]
I have used this library in my project. Will this problem be processed? If handled, I will not modify the source code. Thank you.

**Comment by RevenantX** [comment]
Ehm... Ping calculated only after connection. Becuase this logic inside ```NetPeer.Update``` method. And for precise ping you must wait until special packets will be sent to calculate RTT.

**Comment by RevenantX** [comment]
You can do this by Unconnected messages.
Send one from client and measure response (by sending unconnected message from server) time.
