### ISSUE TITLE
Code fails to handle the fact that `IPV6_V6ONLY` is different on Linux compared with Windows

### ISSUE THREAD

**Issue by iamgreaser** [RevenantX/LiteNetLib#462]
NOTE: I have not run any code here, this is from a quick skim of the code.

While doing some research to see if Neos supported IPv6 through LiteNetLib, I wanted to see if the library supported dual-mode v4+v6 sockets. Turns out it does, but relies on magic numbers for `IPV6_V6ONLY` which differ between operating systems.

Fortunately, the code as it stands should work fine on FreeBSD, as like Windows it uses `27` for the value of `IPV6_V6ONLY`. But on Linux, the value is `26`, and setting `27` accidentally sets the state of `IPV6_JOIN_ANYCAST` instead.

You may want to detect the OS at runtime for this unless there is genuinely no reason LNL can run entirely from .NET bytecode.

`LiteNetLib/NetSocket.cs` has the following code snippets relying on a magic number:

```csharp
//Set IPv6Only
socket.SetSocketOption(SocketOptionLevel.IPv6, (SocketOptionName)27, true);
socket.Bind(ep);
```

```csharp
//Disable IPv6 only mode
socket.SetSocketOption(SocketOptionLevel.IPv6, (SocketOptionName)27, false);
```

**Library version**: commit id (d9ff92e68a228b6e32e6fc036e679242722ba0c9)

**Framework**: All

**OS**: Linux

**Comment by RevenantX** [comment]
@iamgreaser well i checked this. And .NET core uses some interlayer in C that converts SocketOption to UNIX specific. I changed this number to just DualMode setting (that does same thing). But maybe Unity implements it in some another way and this will help.
