### ISSUE TITLE
Deterministic/Rollback LockStep?

### ISSUE THREAD

**Issue by Shadowblitz16** [RevenantX/LiteNetLib#463]
Could we get PerFrame Deterministic/Rollback LockStep implementation in this library?
I don't know if its possible but the idea in my head is we would call some sort of method and pass a option delta time.

**Comment by RevenantX** [comment]
@Shadowblitz16 this is just transport library. For high-level things (like rollbacks) use Mirror/MLAPI/RailgunNet and similar things.
