### ISSUE TITLE
Linux: IPv6Mode.DualMode fails to bind socket

### ISSUE THREAD

**Issue by CallumDev** [RevenantX/LiteNetLib#464]
When running under .NET 5.0 on Linux, the socket fails to bind when IPv6Mode is set to DualMode with the following exception:

`System.Net.Sockets.SocketException (92): Protocol not available`

This happens in line 104 of NetSocket.cs when trying to run this line:

`_udpSocketv4.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.HopLimit, value);`

**Library version**: commit 62324bd (master)

**Framework**: .NET 5.0

**OS**: Linux

**Comment by RevenantX** [comment]
@CallumDev fixed https://github.com/RevenantX/LiteNetLib/commit/7109b3c8ea62c10f669e46b48f499496cea49e26
