### ISSUE TITLE
Port is not released after stop() is called.

### ISSUE THREAD

**Issue by fantasyz** [RevenantX/LiteNetLib#466]
If I call stop(), it will fail to bind the port number thus unable to start the service again. It cannot be solved even if I set the NetManager to null and there is no Dispose() method that could release the port. Thus I am not able to restart a service without restarting the app.

```csharp
// stop current running server
mManager.Stop();

// start again later but it return false
if (!mManager.Start(port))
    throw new Exception($"Failed to start server on port: {port} ({name})");

```

**Library version**: release version (0.9.5.2)

**Framework**: Unity

**OS**: Windows

**Comment by RevenantX** [comment]
@fantasyz are you sure that you calling stop in `MonoBehaviour.OnApplicationQuit` and/or `MonoBehaviour.OnDestroy` And check that first time it starts successfully? Because sometimes you can connect to previous "not stopped" instance.

**Comment by fantasyz** [comment]
@RevenantX  

Hi, it is not connecting to the previous "not stopped" instance. The problem is I cannot Start() a server. I was testing it just like the sample code above, calling Start() right after calling Stop() trying to do a server restart and it failed to start. Netstat show that the port is not released from calling Stop().

I am not calling stop in those cases. I want to be able to pause the server anytime I want and resume it later during development.

New unity version has a new setting to skip "domain reload" which allows us to skip recompiling the code to enter play mode quickly. I cannot use this feature now because I currently have no choice but to depends on domain reload to have the port released from the last play session.

With domain reload off, when I enter play mode the first time, the net lib start and serve client correctly. After the play session, I quit play mode as usual but since code is not recompiled without domain reload, the port some how is not released. I even try to set the manager class to null during shutdown but the result somehow is the same. The next time enter play mode, I end up not able to start the server due to the port being occupied already.
