### ISSUE TITLE
Godot crash when connecting a client or starting a server

### ISSUE THREAD

**Issue by jfaz1** [RevenantX/LiteNetLib#470]
Trying to set up `LiteNetLib` with Godot, unfortunately my game crashes when calling `server.Start()` or `client.Connect()`. Came across this following this guide:
https://dev.to/deagahelio/getting-started-with-litenetlib-2fok

Here's the error:
```
E 0:00:01.006   System.Net.Sockets.Socket..ctor(System.Net.Sockets.AddressFamily , System.Net.Sockets.SocketType , System.Net.Sockets.ProtocolType ): System.Net.Sockets.SocketException: The operation completed successfully.

  <C++ Error>   Unhandled exception
  <C++ Source>  :0 @ System.Net.Sockets.Socket..ctor(System.Net.Sockets.AddressFamily , System.Net.Sockets.SocketType , System.Net.Sockets.ProtocolType )()
  <Stack Trace> :0 @ System.Net.Sockets.Socket..ctor(System.Net.Sockets.AddressFamily , System.Net.Sockets.SocketType , System.Net.Sockets.ProtocolType )()
                NetSocket.cs:294 @ Boolean LiteNetLib.NetSocket.Bind(System.Net.IPAddress , System.Net.IPAddress , Int32 , Boolean , LiteNetLib.IPv6Mode , Boolean )()
                NetManager.cs:1345 @ Boolean LiteNetLib.NetManager.Start(System.Net.IPAddress , System.Net.IPAddress , Int32 )()
                NetManager.cs:1371 @ Boolean LiteNetLib.NetManager.Start(Int32 )()
                Server.cs:16 @ void Server._Ready()()
```

My code is identical to the guide. Using latest version of Godot (3.4 Mono) and latest NuGet version of `LiteNetLib`. I also tried the source/Unity build of `LiteNetLib`, and the master branch .dll, and I get the exact same error. Any help would be appreciated.

**Library version**: 0.9.5.2

**Framework**: Godot Mono

**OS**: Windows

**Comment by jfaz1** [comment]
[LiteNetTest.zip](https://github.com/RevenantX/LiteNetLib/files/7875844/LiteNetTest.zip)
Here's a sample project with the bare minimum to reproduce the issue.

**Comment by jfaz1** [comment]
Closing this as it's clearly an issue with Godot and not LiteNetLib

**Comment by nongvantinh** [comment]
Are you sure?
Please follow. https://github.com/RevenantX/LiteNetLib/issues/452
My game running on mobile, desktop(Windows + Linux) using Godot 3.4.2, and it works fine.

**Comment by jfaz1** [comment]
> Are you sure? Please follow. #452 My game running on mobile, desktop(Windows + Linux) using Godot 3.4.2, and it works fine.

Yeah, please look at the following issue: https://github.com/godotengine/godot/issues/54758
Did you compile the engine yourself? It seems the issue might be with the binary build.

**Comment by nongvantinh** [comment]
I uses the official build.

Vào 11:30, CN, 16 thg 1, 2022 jfaz1 ***@***.***> đã viết:

**Comment by jfaz1** [comment]
Interesting! Did you disable IPv6? This seems to make it work.

**Comment by JamzOhJamz** [comment]
How do i disable ipv6. I can't find it anywhere. Super frustrated  and having this same issue.

**Comment by juse4pro** [comment]
@JamzOhJamz We did it this way.
`NetManager netManager = new NetManager(someNetEventsListenerObject)
{
	IPv6Enabled = IPv6Mode.Disabled
};
netManager.Start();`

or (if you are not familiar with object initializers)
`NetManager netManager = new NetManager(someNetEventsListenerObject);
netManager.IPv6Enabled = IPv6Mode.Disabled;
netManager.Start();`
