### ISSUE TITLE
Reconnecting the client causes a rare timeout loop

### ISSUE THREAD

**Issue by ddakebono** [RevenantX/LiteNetLib#476]
I've been tracking a bit of an issue with LiteNetLib in my application, been trying to discover the exact trigger for the issue.

What appears to be happening is that when a user has a network dropout, and my logic attempts to reconnect them every once in a while they get stuck in a loop where the client appears to not actually receive anything from the server, then it times out and tries again forever.

Out of about 160 concurrent users 3 are stuck in this loop, so it's rather rare, but it's proven to be quite annoying to debug as I can't figure out the exact trigger for the bug, I've had it personally happen to me once when my network appeared to have a hiccup, but once it stabilized I was left in the reconnection loop. 

When the issue occurred to myself even manually disconnecting and reconnecting didn't result in success.

Wondering if this might be something that's been encountered before, or if there was some idea about what to poke at?

Reconnection code:
```csharp
        public void OnPeerDisconnected(NetPeer peer, DisconnectInfo disconnectInfo)
        {
            Con.Msg(TWNetClient.Instance.ExpectedDisconnect
                ? $"Connection to TWNet has been closed! ({disconnectInfo.Reason})"
                : $"Connection to TWNet has been lost! Attempting to reconnect! ({disconnectInfo.Reason})");

            Main.Instance.MainThreadQueue.Enqueue(() =>
            {
                if (Menus.OnlineCount != null)
                    Menus.OnlineCount.Title = $"Online Users: Disconnected!";
            });

            TWNetClient.OnTWNetDisconnected?.Invoke();

            if (disconnectInfo.AdditionalData != null && disconnectInfo.AdditionalData.AvailableBytes > 0)
                NetPacketProcessor.ReadPacket(disconnectInfo.AdditionalData);

            if (TWNetClient.Instance.ExpectedDisconnect || disconnectInfo.Reason == DisconnectReason.RemoteConnectionClose) return;

            TWNetClient.Instance.ReconnectCount++;
            int reconnectTimeAdjustment = TWNetClient.Instance.ReconnectCount / 5;
            TWNetClient.Instance.NetManager.ReconnectDelay = 5000 * reconnectTimeAdjustment + 1000;
            
            if(disconnectInfo.Reason == DisconnectReason.NetworkUnreachable || disconnectInfo.Reason == DisconnectReason.HostUnreachable)
                Thread.Sleep(TWNetClient.Instance.NetManager.ReconnectDelay);

            Con.Msg($"Attempting to reconnect to TWNet... (Attempts: {TWNetClient.Instance.ReconnectCount} | Delay: {TWNetClient.Instance.NetManager.ReconnectDelay / 1000}s)");

            TWNetClient.Instance.ConnectClient();
        }
```

**Library version**: [commit id (465426a3b5e717717d6ba69ad180be2157da6ebd)]

**Framework**: .NET Framework/Unity (Client), dotnetcore (Server)

**OS**: Windows (Client), Linux(Server)

**Comment by RevenantX** [comment]
@ddakebono first of all don't use Sleep in this method and better create reconnect code in your logic rather than in LiteNetLib events. This can be issue
