### ISSUE TITLE
Can't compile on iOS.

### ISSUE THREAD

**Issue by gunderwulde** [RevenantX/LiteNetLib#477]
Just trying to compile for iOS.

**Comment by RevenantX** [comment]
@gunderwulde any info about how you trying to compile and what errors you get?

**Comment by gunderwulde** [comment]
All related to #if UNITY_IOS && !UNITY_EDITOR on file NetManager.Socket.cs:

- Line 44  
      if (!Socket.Start(BindAddrIPv4, BindAddrIPv6, Port, Reuse, IPv6, ManualMode))
      error CS1501: No overload for method 'Start' takes 6 arguments

- Lines 308 & 310
      _unitySocketFix.Reuse = reuseAddress;
      _unitySocketFix.IPv6 = ipv6Mode;
      Think must be capitalized.
