### ISSUE TITLE
If I disconnect the connection immediately after sending the message, the message will not be received.

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#48]
`                            peer.Send(_dataWriter, SendOptions.ReliableOrdered);
                            _netManager.DisconnectPeer(peer);`
External network communication.
If it is not sorted the message can be received.

Is this a BUG?

**Comment by boonkerz** [comment]
yea i think the disconnectpeer does not wait until all packets are send.

the problem should be increase with bigger messages. because the are splited (mtu size)

**Comment by RevenantX** [comment]
>Is this a BUG?
No. This is by desing. I can add method that waits until remaining packets will send. But you can do this by hands. Or use disconnect additional data (but this data is unreliable)

**Comment by RevenantX** [comment]
@QiuBuZai you can try use ```netManager.Flush()``` method.

**Comment by QiuBuZai** [comment]
OK,Thanks.

**Comment by RevenantX** [comment]
@QiuBuZai is ```netPeer.Flush()``` method helped you?

**Comment by RevenantX** [comment]
@QiuBuZai fixed in "packetprocessor" branch. Please help me to test)

**Comment by RevenantX** [comment]
fixed https://github.com/RevenantX/LiteNetLib/commit/0250bd358979800c661b3a452ad56f4c8143a257
