### ISSUE TITLE
How to explicitly control when messages are read and sent?

### ISSUE THREAD

**Issue by chrisnobrega** [RevenantX/LiteNetLib#480]
I'm looking to explicitly control when messages are read and sent.

Psuedo code (desired):

```
void Update ()
{
    // Read incoming messages as fast as possible (120fps+)

    LiteNetLib.ReadIncomingMessages ();

    // Send outgoing messages when certain conditions are met (e.g. variable tickrate)

    if (true)
    {
        LiteNetLib.SendOutgoingMessages ();
    }
}
```

What's the best approach to accomplish this with LiteNetLib?

**Library version**: [commit id (17b48a5690a8e8648addc518af32bd3a8aa3f9bb)]

**Framework**: [Unity]

**OS**: [Windows]

**Comment by RevenantX** [comment]
@chrisnobrega for questions better use discord channel https://discord.gg/FATFPdy
read is `NetManager.PollEvents()` to sync with calling thread. If you want faster receive as possible - use unsynced receive (but `OnNetworkReceive` will be called from "receive" thread, so you need to sync your data using locks or concurrent collections)

For send - use `NetManager.TriggerUpdate()` which calls send methods.
