### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by emre-sahinn** [RevenantX/LiteNetLib#481]
Readme file says 4 byte for reliable but documentation claims 3 byte for reliable, which one is correct?
Here is readme:
![image](https://user-images.githubusercontent.com/30238276/163866511-4983ec72-1825-4b01-92f5-504474425645.png)
https://github.com/RevenantX/LiteNetLib/blob/master/README.md

Here is doc:
![image](https://user-images.githubusercontent.com/30238276/163866576-7fedf1ab-8991-4f08-980c-02435b1c1f48.png)
https://revenantx.github.io/LiteNetLib/index.html

**Comment by RevenantX** [comment]
4 bytes is correct. It's just a bit outdated page in docs.

**Comment by RevenantX** [comment]
Also you can just look at https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/NetConstants.cs#L46

**Comment by emre-sahinn** [comment]
ok, thanks!
