### ISSUE TITLE
Sending files with litenetlib

### ISSUE THREAD

**Issue by Gencturk-m** [RevenantX/LiteNetLib#490]
I am using this framework to send files in desktop application. When I try to send 100mb+ it throws too big packet exception. How can i make this.

**Framework**: dotnetcore, .NET Framework

**OS**: Windows

**Comment by RevenantX** [comment]
https://discord.com/channels/501682175930925058/501682176404750337/991618770449739846

**Comment by SR84** [comment]
The link points to an empty Discord page. I am also interested in transferring large amounts of data. Unfortunately, only 64kb is received each time. I suspect that segmentation is being used here. And now, I lack the knowledge (documentation) to request or resend the missing packets.

Can you help me with this?

**Comment by RevenantX** [comment]
@SR84 join discord for questions: https://discord.gg/FATFPdy also this will allow you to see comment
![image](https://github.com/RevenantX/LiteNetLib/assets/825465/aded8609-ebc0-4849-b9f1-a4d2aaebd986)
