### ISSUE TITLE
Can't convert string back to NetPeer

### ISSUE THREAD

**Issue by ps5cfw** [RevenantX/LiteNetLib#50]
Trying to send a whole NetPeer as a string using .ToString() command for convenience purposes works properly, but there's no way to actually convert back the string to a NetPeer as it once was.

What are the current options to convert a NetPeer as a string and then back to NetPeer?

**Comment by RevenantX** [comment]
@ps5cfw NetPeer is not intended for converting to string. Why you need that?

**Comment by ps5cfw** [comment]
I need to send a list of NetPeers, but the actual method of sending data is through String, doing otherwise could result in a very complex situation that I would like to avoid.

**Comment by RevenantX** [comment]
@ps5cfw ehm... There is NetSerializer for classes and some structures. NetPeer is complex class for internal logic of message processing. If you send list of peer ids or peer ips - you can build your own list and send it.
```
var peers = netManager.GetPeers();
var writer = new NetDataWriter();
writer.Put(peers.Length);
for(int i = 0; i < peers.Length; i++)
{
    writer.Put(peers[i].Id);
}
netManager.SendToAll(writer, SendOptions.ReliableOrdered);
```
But better will be to make your own structure (or class) describing player ( peer ) with fields that you need (name, hp, money, etc.). And make it serializable with any serialization framework what you need.

**Comment by ps5cfw** [comment]
So let me understand, can I create a connection between two clients by using their IDs and IPs while Boeing connected to the server?

How am I supposed to get the serialized data?

**Comment by boonkerz** [comment]
yea thats what https://github.com/RevenantX/LiteNetLib/blob/master/LibSample/HolePunchServerTest.cs 
does.

puncher = server
c1 client no. 1
c2 client no. 2

**Comment by RevenantX** [comment]
@ps5cfw if you want direct connection you can use hole punching. Or send from server to each peer - other peers ips ( ```netDataWriter.Put( peer.EndPoint )``` ).
If you want send some data from one peer to another over server - you need write by hands that logic (it very simple).
