### ISSUE TITLE
Any chance for a Unity .net 4.x compatibility?

### ISSUE THREAD

**Issue by Shinnonda** [RevenantX/LiteNetLib#501]
I did previous tests for learning using 2.0 and worked perfectly, but i got into a project now that needs 4.x, it took me some time to realize that it doesn't work fully, the code itself is working fine and the project works really well in editor, but if i build it, a lot of inconsistent behaviour start to happen.

Local player can connect  to server and receive all server data, remote players can connect but not receive data, sometimes not even send if the remote peer is not the first one to connect, or the server seems having problems listening.

Since i saw "Lite reliable UDP library for .NET Standard 2.0 (Mono, .NET Core, .NET Framework)" on the description, it might be a 4.x compatibility issue?

**Comment by RevenantX** [comment]
@Shinnonda https://github.com/RevenantX/LiteNetLib/tree/0.9 this branch and 0.9.5.2 version is working with 4.x
It is pretty stable but doesn't have some features.

**Comment by RevenantX** [comment]
@Shinnonda .NET 4.x should work. Are you using sources with Unity?

**Comment by Shinnonda** [comment]
Okay, i did some testing and looks like is a issue happening on Unity 2020.3.30f1, i tried it on 2021.3.10f1 and the problem is not happening anymore.

**Comment by Shinnonda** [comment]
Okay, i installed Unity 2021.3.10f1 and started with ontly the sample code, (i was using 2020.3.30f1 before), remote players cannot connect, but now i have a "Connection Failed" error message on remote, what does that mean?

**Comment by RevenantX** [comment]
> Okay, i installed Unity 2021.3.10f1 and started with ontly the sample code, (i was using 2020.3.30f1 before), remote players cannot connect, but now i have a "Connection Failed" error message on remote, what does that mean?
> 
> [CLIENT] We disconnected because ConnectionFailed UnityEngine.Debug:Log (object) GameClient:OnPeerDisconnected (LiteNetLib.NetPeer,LiteNetLib.DisconnectInfo) (at Assets/GameClient.cs:97) LiteNetLib.NetManager:ProcessEvent (LiteNetLib.NetEvent) LiteNetLib.NetManager:PollEvents () GameClient:Update () (at Assets/GameClient.cs:27)

What version of library? Are you using same version on both sides? Are you accepting connections on "server" side?

**Comment by Shinnonda** [comment]
I tried the last 3 releases (0.9.5.2, 0.9.5.1, 0.9.5).
Tried also to straight connect to it instead of leaving the discovery broadcast do the work.
Also checked the Port/IP firewall and por forwarding just to make sure, everything is wide open for the client to reach the server, server didn't even log that an client is trying to connect.

**Comment by Shinnonda** [comment]
> > Okay, i installed Unity 2021.3.10f1 and started with ontly the sample code, (i was using 2020.3.30f1 before), remote players cannot connect, but now i have a "Connection Failed" error message on remote, what does that mean?
> > [CLIENT] We disconnected because ConnectionFailed UnityEngine.Debug:Log (object) GameClient:OnPeerDisconnected (LiteNetLib.NetPeer,LiteNetLib.DisconnectInfo) (at Assets/GameClient.cs:97) LiteNetLib.NetManager:ProcessEvent (LiteNetLib.NetEvent) LiteNetLib.NetManager:PollEvents () GameClient:Update () (at Assets/GameClient.cs:27)
> 
> What version of library? Are you using same version on both sides? Are you accepting connections on "server" side?

i tried the last 3 releases.
Double checked all the ports, IP, port forwarding (even tho still LAN) and tried to straight connect instead of using the discovery broadcast. but the client is not even reaching the server, at least the server is not showing any log of a attempt to connect.

**Comment by RevenantX** [comment]
@Shinnonda disable windows firewall (it block unity udp by default)

**Comment by Shinnonda** [comment]
>

**Comment by Shinnonda** [comment]
ops, missclick, i'll double check that, i remember doing that while testing the first time.

**Comment by Shinnonda** [comment]
> @Shinnonda disable windows firewall (it block unity udp by default). Or remove unity rule

i checked, still happening even with firewall off in all clients and server.

**Comment by Shinnonda** [comment]
Okay, After searching like crazy, i find out that it was a culture problem.
I had to enforce my Unity project to a Invariant Culture cause my computers are using two different languages.

I added:
`
using System.Globalization;
void Start()
}
        CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
}
`

Sorry for not having the proper information before.
