### ISSUE TITLE
Simple Peer-Peer communications program

### ISSUE THREAD

**Issue by pmobley001** [RevenantX/LiteNetLib#505]
Hello all,

I have a quick question, I am looking to make a drop dead simple peer-peer communications program to test a device that I have working through Ethernet. All I need is to send commands and display the reply from the controller on a text box.

Anyways, to accomplish this, would I use this library to setup both a client and a server in my C# program so that the program can send out the commands and listen for the reply?

**Comment by RevenantX** [comment]
@pmobley001 for questions use please https://discord.gg/FATFPdy
For simple communication (this is always p2p because UDP.): there is example: https://github.com/RevenantX/LiteNetLib/blob/master/LibSample/EchoMessagesTest.cs
