### ISSUE TITLE
Custom serializable class arriving with default values

### ISSUE THREAD

**Issue by brzaknemanja** [RevenantX/LiteNetLib#510]
Hello, I followed documentations and example projects on how to send custom class as a packet, but on the server side I receive default values. I'm adding a code example and result in screenshots.
I don't have a clue why it is not working.
Can you please help me?

![Server](https://user-images.githubusercontent.com/20777345/216850355-87095439-080e-4b43-b4c5-1578f7507ac2.PNG)
![client](https://user-images.githubusercontent.com/20777345/216850357-712bf90b-2607-4105-95ad-0d18ac87350f.PNG)
![custom packet](https://user-images.githubusercontent.com/20777345/216850358-ff70693c-0594-43bb-b2cf-2f0f06055c8c.PNG)
![result](https://user-images.githubusercontent.com/20777345/216850362-383debd9-d092-420a-93b2-b919a2ad8279.PNG)

**Comment by RevenantX** [comment]
@brzaknemanja if you using INetSerializable then use method [SendNetSerializable](https://revenantx.github.io/LiteNetLib/api/LiteNetLib.Utils.NetPacketProcessor.html#LiteNetLib_Utils_NetPacketProcessor_SendNetSerializable__1_LiteNetLib_NetManager___0__LiteNetLib_DeliveryMethod_)
