### ISSUE TITLE
Android - PC connection doesn't seem to work (Unity)

### ISSUE THREAD

**Issue by laggyluk** [RevenantX/LiteNetLib#52]
Unity sample works fine when launching two instances on same PC, also works between two android devices. But doesn't seem to work between PC and android despite I've added it to firewall exceptions.
Great work btw! 👍

**Comment by RevenantX** [comment]
@laggyluk this is very strage. Because i tested this case. Can you provide more information and logs. Unity log from android ADB and client log.

**Comment by laggyluk** [comment]
My bad, I had my local network on PC set to 'public' instead of 'private', works great now.

**Comment by RevenantX** [comment]
ok. Closing.
