### ISSUE TITLE
Poll Single Event

### ISSUE THREAD

**Issue by NamelessPerson** [RevenantX/LiteNetLib#528]
Currently NetManager can only poll all pending events. However we have logic that may want us to pause processing events after a certain event has been received. It would be helpful to have a `PollSingleEvent()` or `PollEvents(int count)` code path.

**Comment by RevenantX** [comment]
@NamelessPerson that events contains not only "receive" events but also disconnect/connect/errors and many others. It's better implement "pause" in application code by storing incoming packets in Queue, and then just process them when your game "unpaused"
