### ISSUE TITLE
Packet fragmentation does not seem to work

### ISSUE THREAD

**Issue by ZeoWorks** [RevenantX/LiteNetLib#532]
Hi, 
When sending a reliable packet with a huge amount of data; it seems to not fragment into smaller chunks.

**Comment by RevenantX** [comment]
@ZeoWorks there is limit for auto fragmentation. MTU * 65535 (in case of base MTU 1024 * 65535 ~ 67mb)

**Comment by ZeoWorks** [comment]
What about unreliable fragmentation?

**Comment by RevenantX** [comment]
@ZeoWorks unreliable is not auto-fragmented. It's better to separate packets by hands when you can take some data from one fragment if other fragments lost.

**Comment by ZeoWorks** [comment]
Hi, does reliable sequence fragment automatically?
I do not want a large traffic from reliable, thanks!
