### ISSUE TITLE
ReadOnlyMemory<byte> support vs. byte[] and async/Task support?

### ISSUE THREAD

**Issue by Simonl9l** [RevenantX/LiteNetLib#535]
Hi iI'm a newbie to using you library so please excuse my question if Im just not getting it - yet. This library look massively powerful! Thanks for maintaining it!

I'm trying to plug your library onto an existing solution where our data is available as a `ReadOnlyMemory<byte>`, and we'd like to, in the `NetManager.SendToAll()`, not have to use `ReadOnlyMemory<byte>.ToArray()` as that allocates a new Array. 

Do you have any plans to support `ReadOnlyMemory<byte>` natively?

Additionally, do you have any plans to support `Task` and `async` semantics with `CancelationTokens`, understandably only supported by .Net Core and possibly Unity?   

```csharp
EventBasedNetListener _listener = new();
NetManager _client;
IPEndPoint _ipEndpoint;

_ipEndpoint = new IPEndPoint(ipAddress, port);
_client = new NetManager(_listener);
_client.Start();
_client.Connect(_ipEndpoint, "key");

// Hander that its called:
 public  Task<bool> SendEventAsync(ReadOnlyMemory<byte> packet, CancellationToken token = default)
    {
        try
        {
            _client.SendToAll(packet.ToArray(), DeliveryMethod.ReliableOrdered);
            return Task.FromResult(true);
        }
        catch (Exception e)
        {
            Log.Error(e, "{Message}", e.Message);
            return Task.FromResult(true);
        }
    }

```

**Library version**: Nuget: 1.1.0

**Framework**: Net 8.0

**OS**: All

**Comment by RevenantX** [comment]
@Simonl9l also there is NetPeer.Send with ReadOnlySpan support.

**Comment by RevenantX** [comment]
@Simonl9l it's mainly developed for realtime multiplayer games. There is almost no cases to use "Cancelation tokens" or something like this. Just NetManager.Stop - that stops all internal threads, also there is Manual mode that disables thread at all and in this scenario you possibly will need your own threading code/async or if it's game server it can work with just 1 main thread.

**Comment by RevenantX** [comment]
Added SendToAll with ReadOnlySpan<byte> argument
