### ISSUE TITLE
Serializing nested classes 

### ISSUE THREAD

**Issue by QPRocky** [RevenantX/LiteNetLib#54]
Not sure, if this is bug or design, but following doesnt seem to work:

`public class MainClass`
`{`
    `public SubClass Sub { get; set; }`
`}`

`public class SubClass`
`{`
`    public string Something { get; set; }`
`}`

System.Exception: 'Unknown property type: SubClass'

**Comment by RevenantX** [comment]
From wiki: 

> It does not supports nested structs or classes.
But you can register custom type processor.
That usefull for game engine types such as Vector3 and Quaternion (in Unity3d).

https://github.com/RevenantX/LiteNetLib/wiki/NetSerializer-usage
