### ISSUE TITLE
NetConstants configurable at runtime

### ISSUE THREAD

**Issue by emrys90** [RevenantX/LiteNetLib#541]
It would be nice if NetConstants could be modified at runtime, that way you do not have to modify source code to tweak settings. It would make updating to newer versions easier with less risk of forgetting to change something.

**Comment by RevenantX** [comment]
@emrys90 most constants is really constants. Also this is critical for performance

**Comment by emrys90** [comment]
Alright. The only reason I wanted it was to increase DefaultWindowScale to 128. I believe this feature request would cover that anyways though which would make this one not needed.
https://github.com/RevenantX/LiteNetLib/issues/110
