### ISSUE TITLE
Using SimulateLatency/SimulatePacketLoss

### ISSUE THREAD

**Issue by shouldice** [RevenantX/LiteNetLib#546]
This is a help/support question.

Hi there! I'm having a great time learning about networking with this library. Thank you!

I'm trying to use `SimulateLatency` and `SimulatePacketLoss` but I'm not noticing any change in behaviour when those are turned on. The docs say they only work in DEBUG mode, but I'm not sure what that means. Adding `#define DEBUG` to my own project doesn't seem to help. Is DEBUG mode a LiteNetLib compile-time flag? Do I need to compile the dll myself instead of using the nuget version?

Sorry if this is a basic C# question; I'm still learning. :) 

**Library version**: 1.2.0 via nuget
**Framework**: MonoGame
**OS**: Windows

**Comment by JamDoggie** [comment]
Yeah it does seem like these only features only work when compiling LiteNetLib itself as Debug. This seems unnecessary IMO and I personally think this functionality has no reason not to work in Release mode as well.

**Comment by RevenantX** [comment]
@JamDoggie it slowdowns library much, because there additional checks and lists that contains delayed packets. Use Clumsy to test release https://jagt.github.io/clumsy/

**Comment by RevenantX** [comment]
Fixed by https://github.com/RevenantX/LiteNetLib/pull/557
