### ISSUE TITLE
Clone/Copy NetPacketReader 

### ISSUE THREAD

**Issue by vanhaodev** [RevenantX/LiteNetLib#554]
I see that all clients use the same NetPacketReader, how can I make each client have its own NetPacketReader?
Or you can copy NetPacketReader to use at the desired time.
Thanks

**Comment by RevenantX** [comment]
@vanhaodev they don't use same reader. There is new (or from cache) reader for each message. If you turn off AutoRecycle - they won't be recycled until you call .Recycle on them
