### ISSUE TITLE
Question about Port Checkers

### ISSUE THREAD

**Issue by Andrew1431** [RevenantX/LiteNetLib#559]
I'm currently trying to resolve an issue where a LiteNetLib being handled by a NetManager is causing most UDP port checkers to show that the port is closed or has been rejected. 

I've added handlers for every event from the listener, but none are being called when the port checker call is made. 

My theory (i'm super junior with C#) is that perhaps the litenetlib is not processing the packet at all since it probably isn't valid for however your library works. 

Would this feature be possible with LiteNetLib or would I need some kind of wrapper to LiteNetLib that forwards the packets if they're recognized as litenetlib packets?

No implementation details needed, just curious from a technical approach how this would be done!

Thanks :)

**Comment by RevenantX** [comment]
Port checkers use ICMP response for UDP. This is no such thing as library support. Every UDP game/engine/library uses own packet format.
https://success.qualys.com/support/s/article/000006121
