### ISSUE TITLE
Thread Safty

### ISSUE THREAD

**Issue by NVentimiglia** [RevenantX/LiteNetLib#57]
When messages are received, is it possible that they raised on a background thread ? or are you handling the thread dispatching internally (perhaps from the poll method call)?

The same goes for other INetEventListener events (errors, latency, etc).

Also, when sending messages I saw it noted that I should send messages from a background thread, but it looks like you are putting these messages in a queue and doing that already. Is sending from a background thread still a best practice?

**Comment by RevenantX** [comment]
> When messages are received, is it possible that they raised on a background thread ? or are you handling the thread dispatching internally (perhaps from the poll method call)?

All methods of ```INetEventListener``` called directly in ```PollEvents()```. 

> Also, when sending messages I saw it noted that I should send messages from a background thread, but it looks like you are putting these messages in a queue and doing that already.

Messages automatically enqueued for reliability and flow control (if enabled). Socket send method called in background thread that starts when you call ```netManager.Start()```

**Comment by NVentimiglia** [comment]
Thats what I was looking for.
