### ISSUE TITLE
iOS Exceptions/Crashes

### ISSUE THREAD

**Issue by Figbash** [RevenantX/LiteNetLib#59]
Hi, I'm using LiteNetLib in a project but I'm having a few issue with iOS support.

Unity 5.6.0 IL2CPP
Various iOS devices

On the demo, on an older device (iPad Mini 1) I'm getting:
SocketException: Not enough buffer space is available
  at System.Net.Sockets.Socket.SetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.Socket.set_ReceiveBufferSize (Int32 value) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetSocket.Bind (Int32 port) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetManager.Start (Int32 port) [0x00000] in <filename unknown>:0 
  at GameClient.Start () [0x00000] in <filename unknown>:0 

If I use a newer device (iPhone 7) or change SocketBufferSize in NetConstants, I get a crash:
<img width="1952" alt="screen shot 2017-06-20 at 11 13 43 am" src="https://user-images.githubusercontent.com/1824057/27346239-c5b78efc-55a9-11e7-9a8d-c0cd48c64fb4.png">

**Comment by RevenantX** [comment]
Try set SocketBufferSize in NetConstants.cs (23 line) to something lower (1024*1024)

**Comment by Figbash** [comment]
I get the second crash when I do that, but commenting IPv6Support = Socket.OSSupportsIPv6; seems to fix that crash. There is a comment (//Unity3d .NET 2.0 throws exception.), but I wasn't aware of it. I wonder if there's a better way to fix it, because the unity sample doesn't seem to work on iOS until you delete the DLL and copy in the code and comment that line, which is a little confusing :)

**Comment by RevenantX** [comment]
@Figbash 

> There is a comment (//Unity3d .NET 2.0 throws exception.)
Some versions before - unity throws exception in this place. But not crash (they must fix this. This is not my bug :) )
> because the unity sample doesn't seem to work on iOS until you delete the DLL and copy in the code and comment that line, which is a little confusing :)
For ios better use library source in project. And add compilation flag UNITY to project settings.

**Comment by RevenantX** [comment]
Fixed
https://github.com/RevenantX/LiteNetLib/commit/a7d94d2fc36e1ae2485392472ac11a031f3b1799
