### ISSUE TITLE
Disconnect AdditionalData corrupt?

### ISSUE THREAD

**Issue by JeriXNet** [RevenantX/LiteNetLib#61]
I think I found a bug
Tried to read known packet from disconnect additional data and got exception about type hash not found
Different data offsets used on those lines:
https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/NetManager.cs#L277
https://github.com/RevenantX/LiteNetLib/blob/master/LiteNetLib/NetManager.cs#L582
It worked ok when I changed them to magic number 9 :)

**Comment by RevenantX** [comment]
Oh. True. I will fix.

**Comment by RevenantX** [comment]
Fixed and added test)
