### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by SixFive7** [RevenantX/LiteNetLib#62]
Hi,

This awesome library is only missing a nuget package so we can easily use it from visual studio. Could you add a nuspec?

A random tutorial for an auto updating nuget package:
https://weblogs.asp.net/bsimser/automatically-publishing-nuget-packages-from-github

Thanks!

**Comment by RevenantX** [comment]
Hi! I can try. I don't have big experience in creating nuget packages for all platforms (.net framework, .net core, .net standart)

**Comment by SixFive7** [comment]
Awesome!

**Comment by RevenantX** [comment]
Added
https://github.com/RevenantX/LiteNetLib/commit/3f106b755de29d4279e9a359b5b00517e9758fdd
Url: https://www.nuget.org/packages/LiteNetLib/

**Comment by RevenantX** [comment]
Oh there is something wrong with classic .net package...

**Comment by RevenantX** [comment]
fixed https://github.com/RevenantX/LiteNetLib/commit/f767cdc2e0a62eb3a53c310d7ec0ed35570640a7

**Comment by Thraka** [comment]
@RevenantX Awesome, thanks!!

**Comment by SixFive7** [comment]
The nuget package works. Awesome! Best fast support ever :-)
