### ISSUE TITLE
Connect to Node.js (UNITY)

### ISSUE THREAD

**Issue by farzadi** [RevenantX/LiteNetLib#64]
can we use LiteNetLib unity with node.js  ?

**Comment by RevenantX** [comment]
Only if you implement LiteNetLib protocol in node.js. 
But you can make transport with TCP or unix socket. Small application in C# (with LiteNetLib) that receives packets and sends to node.js socket.

**Comment by farzadi** [comment]
In fact, we want to have a version of LiteNetLib to require in our node js(server.js) and run on the linux server.
Have you planned to develop a node js version in the near future?

**Comment by RevenantX** [comment]
No, i don't have plans to create "nodejs" version, sorry.
Why you need that? :) UDP often used in games with "shared" logic (lockstep games and shooters) that implemented in one language and used in client and server. Maybe TCP will be enough for your purposes?

**Comment by farzadi** [comment]
exactly, we're developing a first person shooter game  :)
At the moment we have developed the game with unity in client and node js dgram in server side.
When we saw your library we found it very helpful in managing the package loss. but unfortunately, it doesn't support node js :(

**Comment by RevenantX** [comment]
@farzadi Better will be implement server in C# too (using mono or dotnetcore). Or you will write logic code twice (in C# and nodejs) that leads to many potential bugs. Because you need resimulate logic for all players based on input and send correct result (positions, health and other stuff) back.
I have homemade shooter game (https://www.youtube.com/watch?v=ZplywasMfPM) - and i know what i'm talking about.

**Comment by RevenantX** [comment]
@yaynick this is not UDP wrapper. This is Reliable-UDP library with internal specific protocol. It has MTU detection, auto fragmentation, packet merging and some other things that RAW UDP doesn't have.

**Comment by RevenantX** [comment]
@yaynick why you can need this? There also special connection/disconnection mechanism and ping (keep-alive) things. If you need simple UDP then use simple UDP (C# has simplier UdpClient helper classes). There is no sense to use this library with node.js (and especially without reliability) server in any case.
