### ISSUE TITLE
NetUtils.GetLocalIpList() returns undesired network interfaces

### ISSUE THREAD

**Issue by gubicsz** [RevenantX/LiteNetLib#65]
Currently, NetUtils.GetLocalIpList() returns network interfaces that have operation status 'Down', like disabled "LogMeIn Hamachi Virtual Ethernet Adapter" or "Hyper-V Virtual Switch." And because of this NetUtils.GetLocalIp() usually returns the wrong address.

I managed to fix this by adding the following check to NetUtils.GetLocalIpList():

`foreach (NetworkInterface ni in NetworkInterface.GetAllNetworkInterfaces())`
`{`
`//Skip loopback`
`if (ni.NetworkInterfaceType == NetworkInterfaceType.Loopback || ni.OperationalStatus != OperationalStatus.Up)`
`continue;`

`var ipProps = ni.GetIPProperties();`
`...`

More info on [OperationalStatus](https://msdn.microsoft.com/en-us/library/system.net.networkinformation.operationalstatus(v=vs.110).aspx)

Would be great to include this fix in the next update.

**Comment by RevenantX** [comment]
I know about OperationalStatus but i removed it https://github.com/RevenantX/LiteNetLib/commit/e31b758fd8464c332d541c7ffc2ce346ee65da0a
There was bug in Unity3d. I hope they fixed it.
