### ISSUE TITLE
MTU on sequenced only 505 Bytes

### ISSUE THREAD

**Issue by SynergiAios** [RevenantX/LiteNetLib#66]
Why is the MTU on sequenced bytes (Not reliable) only 505 Bytes?

`Exception: Unreliable packet size > allowed (505)
LiteNetLib.NetPeer.Send (System.Byte[] data, System.Int32 start, System.Int32 length, LiteNetLib.SendOptions options) (at <e2e830be00234c20a6c7fd24d51fda63>:0)
LiteNetLib.NetPeer.Send (System.Byte[] data, LiteNetLib.SendOptions options) (at <e2e830be00234c20a6c7fd24d51fda63>:0)`

I'm not that deeply in the networking layers, but shouldn't the standard MTU on current networking be ~1500 - some overhead?

**Comment by RevenantX** [comment]
You can change in NetConstants - PossibleMtu. Just remove first line (576)

**Comment by SynergiAios** [comment]
> It automatically grows up after some time to check maximum MTU

Does it really grow? I tested with my SnapShoting mechanism. At some point the SnapShot grows bigger then 505 bytes. And I keep getting errors over errors. Nothing changes. This also occurs after 2 hours running the server and then suddenly raising the snapShot size.

So does the detection really work? Or wait is it maybe setting itself to 505 because I was only testing vie local loopback interface?

I mean I see I could remove the first max MTU size in the PossibleMTU[] in NetConstants.cs and I will mostly do it. I just want to know if there is maybe a further issue of detecting the max MTU x)

But anyways thx for the quick response

**Comment by RevenantX** [comment]
> Does it really grow? I tested with my SnapShoting mechanism. At some point the SnapShot grows bigger then 505 bytes. And I keep getting errors over errors. Nothing changes. This also occurs after 2 hours running the server and then suddenly raising the snapShot size.
Checked now - all works. You can try add some logs and print "peer.Mtu". If you have awlays 508 - i will try find bug.

**Comment by SynergiAios** [comment]
> Checked now - all works. You can try add some logs and print "peer.Mtu". If you have awlays 508 - i will try find bug.

Awesome I will try it later and represent you the log.

**Comment by SynergiAios** [comment]
I have logged the MTU and it's raising really quickly up to ~7800 on my local loopback interface. So the MTU grow does work. So why is then an exception raised, that tells, that the max size for unreliable packets is > 505?

**Comment by RevenantX** [comment]
This is very strange. What version of library in your project?
Do you have this exception at local network (or you have exception at remote server)?

**Comment by SynergiAios** [comment]
Version is - 72ba49c6faec10f5161acaf1dc1e426bd2c3abdf

Exception occurs at local network. I use the local loopback itnerface so server and client running on same machine in same os.

**Comment by RevenantX** [comment]
>  This also occurs after 2 hours running the server and then suddenly raising the snapShot size.

Maybe this happens only when you connect to server after two hours? But when client connected right after server started then after 2 hours - there no exceptions?

**Comment by SynergiAios** [comment]
I will dig deeper into it later. For now I know a quick solution to fix it (remove the smallest MTU setting) Thx for that x) I will try to build something out of unity to build a reproducable error solution. If you don't hear any fruther of me, see this as closed. x) thx

**Comment by RevenantX** [comment]
Ok! :) I always ready to help)

**Comment by huangzejie0810** [comment]
TooBigPacketException: Unreliable packet size exceeded maximum of 1431 bytes

**Comment by RevenantX** [comment]
@huangzejie0810 https://github.com/RevenantX/LiteNetLib/issues/357#issuecomment-608557088
