### ISSUE TITLE
Reliable sequenced network delivery method

### ISSUE THREAD

**Issue by aienabled** [RevenantX/LiteNetLib#68]
Currently, LiteNetLib doesn't have the reliable sequenced network delivery method, only unreliable sequenced. Lidgren library has this method and it's very useful.
Was discussed here https://github.com/RevenantX/LiteNetLib/issues/67#issuecomment-316962256

In some cases, it's necessary to have reliable sequenced delivery. For example, health stat - it's very useful to have, reliably, latest health stat value. But it doesn't make sense to use reliable ordered delivery - on poor connections it increases traffic amount due to resending, it also increases lag as fresher packet cannot be used because previous packet(s) not arrived yet, and on very bad connections it could easily lead to traffic overwhelming and network stall - as sometimes health stat need to be updated very often (damaging, health regeneration, etc). Using the reliable sequenced network delivery method will easily resolve the problem and minimize the network traffic.

Also, it will be useful when porting applications/games which are based on Lidgren library.

Regards!

**Comment by DanisJoyal** [comment]
Hi,

I  guest that it can be done easily by using PacketProperty. 5 bits (21 properties) + 1 bit Fragmented. Maybe add one for multichannel 0x20; or support only 4 channels: 0x60. Easy to do it quickly, maybe not :)

Cheers

**Comment by RevenantX** [comment]
@DanisJoyal this already implemented in almost that way
