### ISSUE TITLE
What is the meaning of a thread lock?

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#71]
Thread lock is meaningless. Because those properties are not accessible to other threads. Can i remove these useless locks?

**Comment by RevenantX** [comment]
There 3 threads in library. 1 for IPv4 receiving. 1 for IPv6 receiveng and 1 for library logic and sending messages. And don't forget your main thread.

**Comment by QiuBuZai** [comment]
I forgot that I removed the ipv6 related code. Sorry.

**Comment by RevenantX** [comment]
@QiuBuZai then 3 theads left. First for receive, second for send, third - main thread.
Some locks you can remove (if you removed IPv6 code). But only if you know where you can do this. But i don't recommend do that.

And why you need that? You have performance issues?

**Comment by QiuBuZai** [comment]
Thank you

**Comment by QiuBuZai** [comment]
@RevenantX Because I was rewriting the library with golang, encountered a problem of thread lock
