### ISSUE TITLE
What the purpose for limiting max connections?

### ISSUE THREAD

**Issue by Agasper** [RevenantX/LiteNetLib#72]
What the purpose for limiting max connections?
Why we can't just change `_peerList` in `NetPeerCollection` from `Array` to `List` ?
That allows me to keep a lot of lazy connections (without ping) without allocating huge array.

**Comment by RevenantX** [comment]
This was added for fast automaticaly drop connections above limit (any shooter game, and many others have player limit on servers)
In next update there will be new system. And i will change some limitations.

**Comment by Agasper** [comment]
Thanks. Will wait for new update
