### ISSUE TITLE
HailMessage on connect

### ISSUE THREAD

**Issue by Agasper** [RevenantX/LiteNetLib#74]
Lidgren had useful feature, you can attach custom packet to the connection packet to provide fast and simple authentication:

`public override NetConnection Connect(NetEndPoint remoteEndPoint, NetOutgoingMessage hailMessage)`

In that case i can just check the data and deny (or accept) the connection, otherwise i have to accept the connection, check auth and drop later in case of invalid credentials

**Comment by RevenantX** [comment]
This in progress (in packetprocessor branch)

**Comment by Agasper** [comment]
How soon are you going to merge it with master ?

**Comment by RevenantX** [comment]
@Agasper oh. This is hard question) Right now i'm busy a little with main work.
I think at end of next week - i will merge.

**Comment by ValooFX** [comment]
I'd be interested in this too. It would be nice to see it included in a release soon.

**Comment by RevenantX** [comment]
@ValooFX i am trying to complete this. Its almost done but have some problems. And i don't have time. Main work take all time.
