### ISSUE TITLE
How do I know I connected successfully?

### ISSUE THREAD

**Issue by Thraka** [RevenantX/LiteNetLib#75]
When I use `new NetManager().Connect(new NetEndPoint(Server, Port));` how do I know if I connected successfully? 

If I connect and the server is not there listening, the peer count (on the client) shows 1. If the server is there and listening, the peer count (on the client) still shows 1.

How do I know that I connected?

**Comment by RevenantX** [comment]
If you connected successfully - OnPeerConnected will be called in INetEventListener.
And there is NetPeer.ConnectionState:
```csharp
    public enum ConnectionState
    {
        InProgress,
        Connected,
        Disconnected
    }
```

**Comment by Thraka** [comment]
But why do I get a connectedpeers == 1 when I don't actually connect?

**Comment by RevenantX** [comment]
There is no method `connectedpeers`. There is method `GetPeers` which return peers in different states, and `PeersCount` property. 
But i agree - there is some inaccuracy in documentation.

**Comment by Thraka** [comment]
Sorry, I do mean that.. The PeersCount is 1 after I call connect but connect doesn't have a real endpoint

**Comment by RevenantX** [comment]
What you mean as "real endpoint"?
If i remove unconnected peers from "PeersCount" - how you will know that connection in progress?

**Comment by Thraka** [comment]
OK, I don't think I understood how the process worked. Doing this solved my issue.

1. Call start
2. Call connect
3. Get the "first connected peer"
4. Loop x times waiting for `peer.ConnectionState == ConnectionState.Connected`

**Comment by RevenantX** [comment]
You can just wait for `OnPeerConnected` event.
