### ISSUE TITLE
Continuous voice transfer and MTU error.

### ISSUE THREAD

**Issue by LiptonOlolo** [RevenantX/LiteNetLib#76]
Hello. I've been using the library a long time, but now I have a problem with the voice transfer. If you do not keep track of packets and always send data, the MTU-related error, of course tracking the packets, I don't want to bet because that would significantly reduce the speed of the voice transfer, which I don't need. What can you recommend?
And yes, I'm sorry about my bad English, I'm from Russia.
Oh yes, I'm sending about 3000 bytes.

**Comment by RevenantX** [comment]
Лучше напиши на русском)

**Comment by LiptonOlolo** [comment]
@RevenantX Привет, я даже забыл, что ты - Русский. В общем делема такая: если постоянно слать голос без гарантии доставки, то вылетает Exception в этом месте: [http://joxi.ru/eAOq5P7txj5vNm.png](url). Отправляю примерно по 3000 byte. Голос, естественно, сжимаю через ZStd, в чистом виде там получается по 4800 байт, в сжатом - 3к (примерно, пустой звук вообще по 300 байт). Как мне быть? Может я что-то не так делаю?

**Comment by RevenantX** [comment]
Максимальный размер пакета без гарантии доставки - это размер MTU (который обычно 1500 байт).
Данный пакет автоматом не фрагментируется. Так что тебе нужно фрагментировать его руками. Есть метод у класса NetPeer: `public int GetMaxSinglePacketSize(SendOptions options)` который возвращает максимальный размер данных которые ты можешь переслать за 1 пакет. Используй его, чтобы фрагментировать пакет вручную и собирать на другой стороне.

На 7-ой шарп не могу перевести из-за поддержки Unity3d (а это одна из основных целей).

**Comment by LiptonOlolo** [comment]
Но почему 1500? Стандартный UdpClient легко справляется с 3000 (и даже с 4000)

**Comment by RevenantX** [comment]
@LiptonOlolo вероятно у него включена фрагментация на уровне UDP. Которая может вести себя очень нестабильно. Не все роутеры поддерживают её и могут просто отбросить пакет который превышает MTU.
Ну а на Localhost - MTU вообще не ограничен.

**Comment by LiptonOlolo** [comment]
Как бы ни было не странно, но и локально все так же... (

**Comment by RevenantX** [comment]
@LiptonOlolo MTU автоматом поднимается со временем (примерно за секунд 5-7). С минимального значения (576 - MaxUdpHeaderSize) до максимального ( 7981 - MaxUdpHeaderSize  //WLAN ).

**Comment by LiptonOlolo** [comment]
@RevenantX  Так же будет и с удаленкой?

**Comment by RevenantX** [comment]
@LiptonOlolo да, но скорей всего MTU будет 1500.

**Comment by LiptonOlolo** [comment]
@RevenantX Понятно, спасибо за ответ. Значит буду думать че да как

**Comment by RevenantX** [comment]
@LiptonOlolo фрагментируй пакеты. Если у тебя голос ты можешь руками длительность примерно порезать и отправить двумя пакетами с опцей Sequenced. Это будет намного лучше - чем автофрагментация  в UDP сокете.
В библиотеке есть автоматическая фрагментация нормальная. Но она работает только для Reliable и ReliableOrdered пакетов.

**Comment by LiptonOlolo** [comment]
@RevenantX Уже решил проблему, решил использовать WebSocket, тоже справляется на "ура")
Спасибо что объяснил, удачи в разработке)
