### ISSUE TITLE
Is the MTUCheck package unreliable?

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#77]
If so, this will make MTU inaccurate.
Set the value of MaxMtuCheckAttempts larger, then you can reduce the impact of packet loss?

**Comment by RevenantX** [comment]
> Is the MTUCheck package unreliable?

Yes

> Set the value of MaxMtuCheckAttempts larger, then you can reduce the impact of packet loss?

This is sometimes hard to tune. Because MTU check packet will eat some traffic. For mobile phones this can be critical.
