### ISSUE TITLE
Socket receiveBuffer every time must be new?

### ISSUE THREAD

**Issue by QiuBuZai** [RevenantX/LiteNetLib#78]
Do you have a problem with the same receiveBuffer?

  Socket socket = (Socket)state;
            EndPoint bufferEndPoint = new IPEndPoint(socket.AddressFamily == AddressFamily.InterNetwork ? IPAddress.Any : IPAddress.IPv6Any, 0);
            NetEndPoint bufferNetEndPoint = new NetEndPoint((IPEndPoint)bufferEndPoint);
            byte[] receiveBuffer = new byte[NetConstants.PacketSizeLimit];

**Comment by RevenantX** [comment]
> Do you have a problem with the same receiveBuffer?
No
> Socket receiveBuffer every time must be new? 
Socket receiveBuffer always reused. it creates at start in thread method. Because there is two threads. 
First for IPv4 and second for IPv6.

And can you please just write to my email? Without issues on github?

**Comment by QiuBuZai** [comment]
No problem, but I can not find your email address. What is your email address?

**Comment by RevenantX** [comment]
@QiuBuZai doomrevx (at) gmail . com
