### ISSUE TITLE
Deserialize is misspelled

### ISSUE THREAD

**Issue by Thraka** [RevenantX/LiteNetLib#79]
The `INetSerializable` interface has **Deser`e`ialize** misspelled. 😢 breaking change to fix .. yikes.
```csharp
public interface INetSerializable
{
    void Desereialize(NetDataReader reader);
    void Serialize(NetDataWriter writer);
}
```

**Comment by RevenantX** [comment]
Oh. I see. Sorry for that. I will fix :) (not so breaking change)

**Comment by Thraka** [comment]
Yeah refactor isn't too bad 👍
