### ISSUE TITLE
Additional data with Disconnect message

### ISSUE THREAD

**Issue by ashoulson** [RevenantX/LiteNetLib#8]
Would it be possible to add support for sending and receiving a ushort with the Disconnect message?

**Comment by RevenantX** [comment]
I can add some data to disconnect message. But this message is unreliable and you can always send some messages before. I will investigate this question.

**Comment by ashoulson** [comment]
It's fine if it's unreliable. It would just be nice for notifying clients if possible. I've been digging through the code a little and I'm currently in the process of adding a few things:

1) A ConnectReject message that's sent if the server rejects a connection, either due to the ConnectKey not matching or due to the server being full. See [this commit in my fork](https://github.com/ashoulson/LiteNetLib/commit/2f6fc95c5826bc5f2630203ed7f6fdb8bd4213f2).

2) A user-specified disconnect data token, just an additional byte, as I requested in this issue.

3) The option to add an additional string on connection aside from the ConnectKey, that will be passed up to the application when a client connects (to be used for session/authentication tokens).

**Comment by ashoulson** [comment]
Feature completed in [this commit](https://github.com/ashoulson/LiteNetLib/commit/7d056db44e883b129257d6fa2296277876eb2c56). The server can now include a 1-byte code when force-disconnecting a peer or shutting down and disconnecting all peers. Note that this is sent unreliably. I can start a pull request if it's something you'd like to add to the main repo.

**Comment by RevenantX** [comment]
You can create pull request with any features you want) This will be good feature)

**Comment by RevenantX** [comment]
Done.
