### ISSUE TITLE
Question: UnsyncedEvents and reliable with order channel

### ISSUE THREAD

**Issue by SixFive7** [RevenantX/LiteNetLib#80]
Hi RevenantX,

First off, awesome library!
Quick question. If I enable the UnsyncedEvents feature and consume incoming messages by implementing the events; how is the treading actually done? Is it potentially another thread from the threadpool per message? If so, this feature doesn't make sense in combination with a reliable with order channel right? As multiple simultaneous threads cannot guarantee the ordering. Shouldn't this option then not be possible when using a reliable with order channel? Just to prevent users (like me) from shooting themselves into their own foot.
Or is the treading implementation behind the events implemented entirely different?
Also, what does it mean that the feature is "experimental"?

Kind regards!

**Comment by NVentimiglia** [comment]
I believe it is coming off of a dedicated receiver thread. I did not see the use of the thread pool in a quick search (Thank god, it produces a ton of garbage). So, that said, It is ordered, on that main thread. It just is not queued and pull from the main thread.

**Comment by RevenantX** [comment]
Unsynced messages come from socket receive threads ( 1 for IPv4 and 1 for IPv6).

**Comment by SixFive7** [comment]
Hi Nicholas and Ruslan,

Thank you for the quick and clarifying responses. I like how it's still ordered and I don't mind the thread unsafety as we already have thread safe consuming code.

Kind regards!

**Comment by RevenantX** [comment]
>Also, what does it mean that the feature is "experimental"?

There can be some sync bugs, because this feature rarely used and maybe not well tested. But if you find some feel free to report)

**Comment by SixFive7** [comment]
> But if you find some feel free to report)

Will do. Thank you :-)

**Comment by xmedeko** [comment]
Hi, sorry for addinf to the old closed question. I've found that the `NetSerializer` is not thread safe. So, when a server has IPv4 and IPv6, then the `OnNetworkReceive` using one `NetSerializer` may have race conditions? Thanks.

**Comment by RevenantX** [comment]
@xmedeko there can be race condition only if you are using `Unsynced Events`

**Comment by xmedeko** [comment]
Yes, this question is about `UnsyncedEvents`, thank you for the answer.
