### ISSUE TITLE
UpdateTime

### ISSUE THREAD

**Issue by pax83** [RevenantX/LiteNetLib#81]
What happens if I set the UpdateTime to 1?
I need a server that processes messages as quickly as possible and sends responses. Are there any recommendations on this?

**Comment by RevenantX** [comment]
Update time will increase send rate and internal logic update rate. But check CPU usage after this. 
For fastest receive you can use "UnsyncedEvents" option. But then all events will be called from different threads (socket receive threads and logic thread). So you need manually synchronize this (if needed).

**Comment by pax83** [comment]
Thanks for the answer.
UnsyncedEvents is ok.
One more question. Will the number of transmitted service packets be increased(such as ACK etc) if I set UpdateTime to 1?

**Comment by RevenantX** [comment]
> One more question. Will the number of transmitted service packets be increased(such as ACK etc) if I set UpdateTime to 1?
Only ack packet (for reliable packets) send rate will be increased.

**Comment by pax83** [comment]
Thank you, I will test it.
