### ISSUE TITLE
SimulationPacketLossChance works wrong

### ISSUE THREAD

**Issue by marsermd** [RevenantX/LiteNetLib#82]
Hi!
To check if packet should be lost there is following code:
`_randomGenerator.Next(100/SimulationPacketLossChance) == 0`
This is obviously a bad idea:
- SimulationPacketLossChance might be zero
- if SimulationPacketLossChance is 51 or higher, probability of getting 0 equals 1, so the packet will be dropped. 

The simplest way around is to do exactly what probability in percentages is:
`_randomGenerator.Next(101) < SimulationPacketLossChance`
I put 101 here, because else probability of 99 percent would trigger every time. This is quite obviously not an accurate solution, probability of one percent here is actually 1/101 instead of 1/100. But it is because of using discrete values. Another option would be:
`(_randomGenerator.NextDouble() * 100 < SimulationPacketLossChance` 
This is obviously an accurate way, but a soon as I know it is slower. Although it shouldn't be a problem, since this code executes for debug purposes only.

**Comment by marsermd** [comment]
Please tell me what you think:)
I would like to add a pull request, but i'm not sure what is the right way to contribute in this project. Is there anywhere a document?

**Comment by RevenantX** [comment]
@marsermd Hi! Yes there is some bad code) You can add pull request. Just use code style like in all project)

**Comment by marsermd** [comment]
@RevenantX Thank you for fast response!
What is your branching policy? Should I create a separate branch?

Also I'd like to add `Put(char c)` and `GetChar()` to `NetDataWriter` and `NetDataReader` respectfully. Should I create issue for that or I can proceed to creating a pull request?

**Comment by RevenantX** [comment]
Do it in master branch. And add char methods if you want in that pull request)

**Comment by marsermd** [comment]
It took me longer to setup VS to run tests then to write code:D
But now I can contribute :) 

Looking forward to further collaboration.
