### ISSUE TITLE
it will add tcp and webgl support is great

### ISSUE THREAD

**Issue by cnbryan** [RevenantX/LiteNetLib#86]
for unity3d
tcp udp webgl support at on lib

**Comment by NVentimiglia** [comment]
Why not just use a websocket library if that is what you want ? There are plenty to choose from.

**Comment by RevenantX** [comment]
Main goal of this library is Reliable UDP. WebGL doesn't support UDP at the moment.
And TCP doesn't need library. TCP very easy (for user) protocol.
