### ISSUE TITLE
.net core serverside implementation 

### ISSUE THREAD

**Issue by A-H-B-Gh** [RevenantX/LiteNetLib#87]
hello thanks for your great project.

I want to implement server for game but I can't understand how to implement that in .net core project.
can you give some example?
 
I should use it as a middle ware? or what are apis to start that?

**Comment by NVentimiglia** [comment]
I use it in a console app (not an ASP.NET web application). I do not use it as middle ware as this does not go through the HTTP pipeline.

**Comment by A-H-B-Gh** [comment]
I have done that in console app. but I was wondering about .net core library that it has.
thanks for your help

**Comment by RevenantX** [comment]
@A-H-B-Gh .net core will be almost same as simple console app.
