### ISSUE TITLE
Exception policy

### ISSUE THREAD

**Issue by marsermd** [RevenantX/LiteNetLib#89]
#Hi! After accidentialy sending too large packet, I got an exception. And it is a pretty obvious thing to happen. 
But since library raises exceptions, one would think that they should be:
a) [Documented](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/xmldoc/exception)
b) Either custom exception classes or standard exceptions like ArgumentException

Reasoning for documentation:
It is *extremly* useful to understand what are the points of failure of your application. And something like sending a packet bigger than needed is very easy to overlook. 

Reasoning for not using plain Exception class: 
First of all Exception can't be handled properly: some exceptions like big packet size can occur and it would be nice not to crash. But adding an `catch (Exception e)` [is a bad idea](https://softwareengineering.stackexchange.com/questions/164256/is-catching-general-exceptions-really-a-bad-thing) since it catches *any* possible exception, which is mostly not desired.

If you agree on this, I will create a pull request with updated exceptions.

**Comment by marsermd** [comment]
@RevenantX , did you get a chance to take a look at this?
I am proposing to replace all 
`throw new Exception()`
with
`BadPacketException()`, `ArgumentException`, `InvalidOperationException`, ...
And write doc comments explaining when these exceptions can be thrown.

And I will do it if you agree:)

**Comment by RevenantX** [comment]
> @RevenantX , did you get a chance to take a look at this?

Yes!) This is cool idea. But i must to do some "work in progress" parts with new features. 

> And I will do it if you agree:)

I agree. Thanks) But wait for new release. I just need some time. :)

**Comment by marsermd** [comment]
No problem!

**Comment by marsermd** [comment]
@RevenantX, can I start with exceptions enhancements? Or should I wait?:)

**Comment by RevenantX** [comment]
@marsermd please wait)

**Comment by RevenantX** [comment]
@marsermd if you want to help - now this time)

**Comment by marsermd** [comment]
@RevenantX, ok. Most probably will make a PR today.
