### ISSUE TITLE
Can add a event like this?

### ISSUE THREAD

**Issue by cnbryan** [RevenantX/LiteNetLib#90]
server.OnSend(NetPeer peer, NetDataReader reader)
{
  if ( check_heartbeat_timeout())
   {
                 peer.NetManager.DisconnectPeer(peer);
   }
}
i want to do a heartbeat check;
  at every time OnSend
client send heartbeat every two second; server flush heartbeat time; 

i want the server disconnectPeer realtime

**Comment by cnbryan** [comment]
or how about make a configurable Heart Beat in the lib

**Comment by RevenantX** [comment]
@cnbryan 
There is two settings that do that thing automatically.
**UpdateTime**
library logic update (and send) period in milliseconds
default value: 100 msec. For games you can use 15 msec (66 ticks per second)

**DisconnectTimeout**
if client or server doesn't receive any packet from remote peer during this time then connection will be closed
(including library internal keepalive packets)
default value: 5000 msec.
