### ISSUE TITLE
Block version of PollEvents

### ISSUE THREAD

**Issue by watsonsong** [RevenantX/LiteNetLib#95]
I want my server program block on message and timer but not to update and take all of the CPU.
So what I need is a block version of PollEvents, so I can put it onto a work thread. Right now I put the network manager poll loop on a thread and sleep on each loop to avoid CPU usage, but I think it not a good implement.
My code is like this:
`
this.netManager.Start(port);
this.netThread = new Thread(() =>
{
    while (this.netManager.IsRunning)
    {
        this.netManager.PollEvents();
        Thread.Sleep(0);
    }
});

this.netThread.Start();
`

**Comment by watsonsong** [comment]
BTW, I am worry about the UpdateTime. Is it delay my package when I sending or receiving?
Why the package can not just send immidately, if I change it to a real small value, 1 for example, will it very cost performance?

**Comment by RevenantX** [comment]
@watsonsong UpdateTime - is delay betwen sends.
> Why the package can not just send immediately

You can call NetManager.Flush() to send all packets immediately.

This feature is needed for packets merging. It merges small packets into one big for faster data sending.

**Comment by watsonsong** [comment]
I see there has an experimental feature is "UnsyncedEvents".
Can I use this event to implement the true block version of server? As the event should be invoke on the working thread, I can pass it to my own scheduler.

**Comment by RevenantX** [comment]
@watsonsong usyncedevent flag enables instant calls of INetEventListener methods in library receive thread.  So you can dispatch these calls to your thread. (And possibly to sync use some AutoResetEvent or Monitor.Pulse)

**Comment by RevenantX** [comment]
@watsonsong soo... you can use this for "block version of server")

**Comment by watsonsong** [comment]
I just test and it correct, no need this loop and no worry about the sleep anymore:
`
while (this.netManager.IsRunning)
{
    this.netManager.PollEvents();
    Thread.Sleep(1);
}
`

Thank you~

**Comment by RevenantX** [comment]
@watsonsong so i can close this?)

**Comment by watsonsong** [comment]
Sure, thank you~
