### ISSUE TITLE
NetManager.Start support to bind on different address.

### ISSUE THREAD

**Issue by watsonsong** [RevenantX/LiteNetLib#96]
For example, my server has two different IP address, one address is export to the internet, the other one is internal usage.
I want to specify which address my socket bind to. So I think the NetManager.Start not just specify the port, but also the address.

**Comment by watsonsong** [comment]
I think it simple, just pass one more parameter to NetSocket.Bind, and change the BindSocket invoke:
if (!BindSocket(_udpSocketv4, new IPEndPoint(IPAddress.Any, port)))

**Comment by RevenantX** [comment]
@watsonsong yes it simple. But i'm very busy right now with main work. If you want you can create pull request that adds that functionality.

**Comment by RevenantX** [comment]
@watsonsong inspected this a little. You need two adresses (IPv4 and IPv6). WP8.1 api doesn't support this. It supports network adapter selection.

**Comment by watsonsong** [comment]
This feature usually used on the server side, the client usually just connect to the server. But the server usually has two different IP, specially on the cloud ECS. So I think WP platform maybe does't need this.
I think some API maybe different on different platform, if there is no way to provide the same API. Even the unity3D is provide some different API for different platform.
How about it?

**Comment by RevenantX** [comment]
@watsonsong added to new version in "packetprocessor" branch. Please help in testing)

**Comment by watsonsong** [comment]
Thank you~ and I have some problem.
Is it necessary I have to bind both ipv4 and ipv6. If my network is ipv4 only, it seems there is no need to open an udp socket for ipv6. I think there is no way let me to **just bind** one ipaddress?
Maybe I make something wrong, but in my environment there is no ipv6 address, and I am afraid there is some bad guys attack to some port that I only tent to internal usage.
