### ISSUE TITLE
Can integrated KCP protocol?

### ISSUE THREAD

**Issue by andyhebear** [RevenantX/LiteNetLib#97]
Can integrated KCP protocol?
KCP - A Fast and Reliable ARQ Protocol for mobile client
c: https://github.com/skywind3000/kcp
csharp: https://github.com/limpo1989/kcp-csharp

**Comment by RevenantX** [comment]
Hi! Why you need this if there already exists C# implementation?

**Comment by andyhebear** [comment]
A network library wants to include different solutions that can be applied between the server and the server, or between the client and the client. like p2p with mobile 4g zhe KCP  protocol is better , and in server use other protocol is better.

**Comment by andyhebear** [comment]
The entire protocol has only two source files, ikcp.h and ikcp.c, which can be easily integrated into the user's own protocol stack. You may realize a P2P, or a UDP based protocol, and the lack of a comprehensive and reliable ARQ protocol, then simply copy the two files to the existing project, a written two lines of code, you can use.

**Comment by RevenantX** [comment]
@andyhebear maybe better will be create some benchmark to compare LitenetLib and KCP?

**Comment by andyhebear** [comment]
Mature project KCP integration
 kcptun:https://github.com/xtaci/kcptun
dog-tunnel:https://github.com/vzex/dog-tunnel
v2ray：https://www.v2ray.com/
shadowsocks-android: https://github.com/shadowsocks/shadowsocks-android
----------------
and business game use KCP protocol 👍 

Game K17：https://www.taptap.com/app/50664
moba game:https://www.taptap.com/app/27242

**Comment by sgf** [comment]
> Hi! Why you need this if there already exists C# implementation?

The advantage of KCP is not only reliable transmission, the most important thing is to reduce network delay and jitter. Especially in the long distance (physically) all over the world, it has better performance in the environment of high packet loss rate.

Of course, it does not manage connections, nor does it handle UDP. It is just an intermediate layer. If compared with this repo,the current project is more specific.
