### ISSUE TITLE
Send to self

### ISSUE THREAD

**Issue by jamesbrooks** [RevenantX/LiteNetLib#98]
As far as I can tell (as a very recent user of this library) you can send a message to a connected peer (`NetPeer`), but is it possible to send a message to yourself?

A implementation reason for wanting this would be logic for a listen game server where the service is also a client, so that commands for that client could be treated in the exact same way as they are for the other connected clients.

Is this possible currently with this library? A loop-back NetPeer per-say :). If not it's not something that would be too difficult to work around, but if the library supports it out of the box I'd rather use that!

**Comment by RevenantX** [comment]
Why you cannot just call receiving method directly?

**Comment by jamesbrooks** [comment]
That is currently what I'm doing, it just introduces a slight code-smell where when I sent a message to each Player the server iterates through the connected peers, and then also, calls the receiving method directly (rather than being able to do just the first part if a local NetPeer did exist).

That's ok though - it's not a deal-breaker :)

**Comment by NVentimiglia** [comment]
I would wrap a light business logic layer around LiteNetLib and handle it there. If connected, echo. Im not sure how I feel about putting this type of branching in the socket.

**Comment by RevenantX** [comment]
@jamesbrooks you can create local loop peer. But this will consume more CPU and RAM. And can introduce some transfer delays.

Better call method directly. Or as @NVentimiglia said.
